// packages/reelkit-react-reel-player/src/lib/ReelPlayerOverlay.tsx
/* eslint-disable react-hooks/exhaustive-deps */
import React, { type ReactNode, useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { ChevronUp, ChevronDown, ImageOff } from 'lucide-react';
import {
  noop,
  createSignal,
  createContentLoadingController,
  createContentPreloader,
  createDisposableList,
  reaction,
  observeDomEvent,
  captureFocusForReturn,
  createFocusTrap,
  Reel,
  Observe,
  type ReelApi,
  type ReelProps,
  SoundProvider,
  useSoundState,
} from '@reelkit/react';
import { useBodyLock } from '@reelkit/react';
import type {
  BaseContentItem,
  ContentItem,
  ControlsRenderProps,
  NavigationRenderProps,
  NestedSlideRenderProps,
  SlideRenderProps,
  TimelineMode,
  TimelineRenderProps,
} from './types';
import MediaSlide from './MediaSlide';
import { captureFrame } from '@reelkit/react';
import PlayerControls from './PlayerControls';
import SlideOverlay from './SlideOverlay';
import { shared as sharedVideo } from './VideoSlide';
import { TimelineProvider, useTimelineState } from './TimelineState';
import TimelineBar from './TimelineBar';
import './ReelPlayerOverlay.css';

/**
 * Subset of {@link ReelProps} that are forwarded to the underlying `Reel`
 * component. These control the slider's transition, gesture, and
 * navigation behavior.
 */
export type ReelProxyProps = Pick<
  ReelProps,
  | 'transitionDuration'
  | 'swipeDistanceFactor'
  | 'loop'
  | 'enableNavKeys'
  | 'enableWheel'
  | 'wheelDebounceMs'
>;

/**
 * Props for the {@link ReelPlayerOverlay} component.
 *
 * Generic over `T`: pass any type extending {@link BaseContentItem} to use
 * custom data. Defaults to {@link ContentItem} for backward compatibility.
 *
 * @typeParam T - Content item type. Must have `id` and `media` fields at minimum.
 */
export interface ReelPlayerOverlayProps<T extends BaseContentItem = ContentItem>
  extends ReelProxyProps {
  /**
   * Aspect ratio (width / height) for the player container on desktop.
   * On mobile (< 768px viewport), the player always uses full viewport.
   *
   * @default 0.5625 (9:16)
   * @example
   * ```tsx
   * // Standard 9:16 (default)
   * <ReelPlayerOverlay aspectRatio={9 / 16} ... />
   *
   * // Wider 3:4
   * <ReelPlayerOverlay aspectRatio={3 / 4} ... />
   * ```
   */
  aspectRatio?: number;

  /** When `true`, the overlay is rendered and body scroll is locked. */
  isOpen: boolean;

  /**
   * Accessible label for the dialog region. Announced by screen readers
   * when the overlay opens.
   *
   * @default 'Video player'
   */
  ariaLabel?: string;

  /** Array of content items to display as vertical slides. */
  content: T[];

  /** Zero-based index of the initially visible slide. Defaults to `0`. */
  initialIndex?: number;

  /**
   * Whether the built-in playback timeline bar renders over the active video.
   *
   * @default 'auto'
   */
  timeline?: TimelineMode;

  /**
   * Minimum video duration (seconds) for `timeline='auto'` to render the
   * built-in bar. Short looping clips below this threshold are suppressed.
   *
   * @default 30
   */
  timelineMinDurationSeconds?: number;

  /**
   * Ref to access the Reel API
   */
  apiRef?: React.MutableRefObject<ReelApi | null>;

  /**
   * Callback fired after slide change
   */
  onSlideChange?: (index: number) => void;

  /** Callback to close the overlay. Triggered by close button or Escape key. */
  onClose: () => void;

  /**
   * Custom overlay on top of each slide. Replaces default SlideOverlay.
   * Return `null` to hide the overlay entirely.
   */
  renderSlideOverlay?: (item: T, index: number, isActive: boolean) => ReactNode;

  /**
   * Custom full slide renderer. Receives all props needed to render
   * `VideoSlide`, `ImageSlide`, or `NestedSlider` (multi-media) with
   * proper playback and drag coordination.
   *
   * Return `null` to fall back to the default MediaSlide + overlay.
   * Use `props.defaultContent` to wrap the default rendering with your
   * own additions.
   */
  renderSlide?: (props: SlideRenderProps<T>) => ReactNode | null;

  /**
   * Custom controls. Replaces default PlayerControls.
   */
  renderControls?: (props: ControlsRenderProps<T>) => ReactNode;

  /**
   * Custom playback timeline bar. Invoked only when the gating rules would
   * render the default bar. Return `null` to hide it for that slide.
   *
   * Use `props.defaultContent` to wrap the built-in {@link TimelineBar}, or
   * return a fully custom element driven by `props.timelineState` signals.
   */
  renderTimeline?: (props: TimelineRenderProps<T>) => ReactNode;

  /**
   * Custom navigation arrows. Replaces default ChevronUp/Down.
   */
  renderNavigation?: (props: NavigationRenderProps) => ReactNode;

  /**
   * Custom navigation for the nested horizontal slider (multi-media posts).
   * Replaces default ChevronLeft/Right arrows inside nested slides.
   */
  renderNestedNavigation?: (props: NavigationRenderProps) => ReactNode;

  /**
   * Custom slide renderer for nested horizontal slider items (multi-media posts).
   * Use `props.defaultContent` to wrap the default ImageSlide/VideoSlide with your own styles.
   */
  renderNestedSlide?: (props: NestedSlideRenderProps) => ReactNode;

  /** Custom loading indicator. Replaces default wave loader. */
  renderLoading?: (props: { item: T; activeIndex: number }) => ReactNode;

  /** Custom error indicator. Replaces default error icon. */
  renderError?: (props: { item: T; activeIndex: number }) => ReactNode;
}

const _kDefaultAspectRatio = 9 / 16;
const _kMobileBreakpoint = 768;
const _kPreloadRange = 2;
const _kDefaultTimelineMinDurationSeconds = 30;

const preloader = createContentPreloader({ maxCacheSize: 1000 });

/**
 * Inner content of the player overlay. Renders the `Reel` slider, controls,
 * navigation arrows, and manages video/sound/resize lifecycle.
 *
 * Must be rendered inside a {@link SoundProvider}.
 * @internal
 */
function ReelPlayerContent<T extends BaseContentItem = ContentItem>(
  props: ReelPlayerOverlayProps<T>,
) {
  const { initialIndex = 0, apiRef } = props;

  const propsRef = useRef(props);
  propsRef.current = props;

  const internalSliderRef = useRef<ReelApi>(null);
  const sliderRef = apiRef ?? internalSliderRef;
  const innerSliderRef = useRef<ReelApi>(null);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const videoPausedOnDragRef = useRef(false);
  const overlayRef = useRef<HTMLDivElement | null>(null);
  const soundState = useSoundState();
  const timelineState = useTimelineState();

  const [
    {
      sizeSignal,
      loadingCtrl,
      indexSignal,
      innerMediaTypeSignal,
      getSize,
      handleBeforeChange,
      handleAfterChange,
      handleSlideDragStart,
      handleSlideDragEnd,
      handleSlideDragCanceled,
      handlePrev,
      handleNext,
      itemBuilder,
    },
  ] = useState(() => {
    const getSize = (): [number, number] => {
      if (typeof window === 'undefined') return [0, 0];
      const ratio = propsRef.current.aspectRatio ?? _kDefaultAspectRatio;
      const windowWidth = window.innerWidth;
      const windowHeight = window.innerHeight;

      if (windowWidth < _kMobileBreakpoint) {
        return [windowWidth, windowHeight];
      }

      let width = windowHeight * ratio;
      let height = windowHeight;

      if (width > windowWidth) {
        width = windowWidth;
        height = windowWidth / ratio;
      }

      return [width, height];
    };

    const sizeSignal = createSignal<[number, number]>(getSize());
    const loadingCtrl = createContentLoadingController(true, initialIndex);
    const indexSignal = createSignal(initialIndex);
    const innerMediaTypeSignal = createSignal<'image' | 'video' | null>(null);

    const hasVideoContent = (index: number): boolean => {
      const item = propsRef.current.content[index];
      return item?.media.some((m) => m.type === 'video') ?? false;
    };

    const handleVideoRef = (ref: HTMLVideoElement | null) => {
      videoRef.current = ref;
    };

    const handleActiveMediaTypeChange = (type: 'image' | 'video') => {
      innerMediaTypeSignal.value = type;
    };

    const overlayNode = (item: T, index: number, isActive: boolean) => {
      const { renderSlideOverlay } = propsRef.current;
      if (renderSlideOverlay) {
        return renderSlideOverlay(item, index, isActive);
      }
      const record = item as Record<string, unknown>;
      const author =
        'author' in item
          ? (record['author'] as { name: string; avatar: string } | undefined)
          : undefined;
      const description =
        'description' in item
          ? (record['description'] as string | undefined)
          : undefined;
      const likes =
        'likes' in item ? (record['likes'] as number | undefined) : undefined;
      return (
        <SlideOverlay author={author} description={description} likes={likes} />
      );
    };

    return {
      sizeSignal,
      loadingCtrl,
      indexSignal,
      innerMediaTypeSignal,
      getSize,
      handleVideoRef,
      handleActiveMediaTypeChange,
      handleBeforeChange: () => {
        soundState.disabled.value = true;
        if (videoRef.current) {
          videoRef.current.pause();
          const key = videoRef.current.dataset['slideKey'];
          const frame = captureFrame(videoRef.current);
          if (key && frame) {
            sharedVideo.capturedFrames.set(key, frame);
          }
        }
      },
      handleAfterChange: (index: number) => {
        loadingCtrl.setActiveIndex(index);
        const src = propsRef.current.content[index]?.media[0]?.src;
        if (src && preloader.isErrored(src)) {
          loadingCtrl.onError(index);
        } else if (src && preloader.isLoaded(src)) {
          loadingCtrl.onReady(index);
        }
        innerMediaTypeSignal.value = null;
        if (hasVideoContent(index)) {
          soundState.disabled.value = false;
        }
        indexSignal.value = index;
        propsRef.current.onSlideChange?.(index);
      },
      handleSlideDragStart: () => {
        innerSliderRef.current?.unobserve();
        if (videoRef.current && !videoRef.current.paused) {
          videoRef.current.pause();
          videoPausedOnDragRef.current = true;
        }
      },
      handleSlideDragEnd: () => {
        innerSliderRef.current?.observe();
      },
      handleSlideDragCanceled: () => {
        if (videoPausedOnDragRef.current && videoRef.current) {
          videoRef.current.play().catch(noop);
        }
        videoPausedOnDragRef.current = false;
      },
      handlePrev: () => {
        sliderRef.current?.prev();
      },
      handleNext: () => {
        sliderRef.current?.next();
      },
      itemBuilder: (
        index: number,
        _indexInRange: number,
        itemSize: [number, number],
      ) => {
        const {
          content: items,
          renderSlide: render,
          renderNestedNavigation: nestedNav,
          renderNestedSlide: nestedSlide,
          enableWheel: wheel = true,
        } = propsRef.current;
        const item = items[index] as T;
        const isActive = index === indexSignal.value;
        const onReady = () => {
          loadingCtrl.onReady(index);
          const src = item.media[0]?.src;
          if (src) preloader.markLoaded(src);
        };
        const onWaiting = () => loadingCtrl.onWaiting(index);
        const onError = () => {
          const src = item.media[0]?.src;
          if (src) preloader.markErrored(src);
          loadingCtrl.onError(index);
        };

        const defaultContent = (
          <>
            <MediaSlide
              content={item}
              isActive={isActive}
              size={itemSize}
              innerSliderRef={innerSliderRef}
              enableWheel={wheel}
              onVideoRef={isActive ? handleVideoRef : undefined}
              onReady={onReady}
              onWaiting={onWaiting}
              onError={onError}
              onActiveMediaTypeChange={
                isActive ? handleActiveMediaTypeChange : undefined
              }
              renderNestedNavigation={nestedNav}
              renderNestedSlide={nestedSlide}
            />
            {overlayNode(item, index, isActive)}
          </>
        );

        if (render) {
          const custom = render({
            item,
            index,
            size: itemSize,
            isActive,
            slideKey: item.id,
            onVideoRef: isActive ? handleVideoRef : undefined,
            innerSliderRef,
            onActiveMediaTypeChange: isActive
              ? handleActiveMediaTypeChange
              : undefined,
            renderNestedNavigation: nestedNav,
            enableWheel: wheel,
            defaultContent,
            onReady,
            onWaiting,
            onError,
          });
          if (custom !== null) {
            return (
              <div
                className="rk-reel-slide-wrapper"
                role="group"
                aria-roledescription="slide"
                aria-label={`Slide ${index + 1} of ${items.length}`}
                style={{
                  width: itemSize[0],
                  height: itemSize[1],
                  position: 'relative',
                }}
              >
                {custom}
              </div>
            );
          }
        }

        return (
          <div
            className="rk-reel-slide-wrapper"
            role="group"
            aria-roledescription="slide"
            aria-label={`Slide ${index + 1} of ${items.length}`}
            style={{
              width: itemSize[0],
              height: itemSize[1],
              position: 'relative',
            }}
          >
            {defaultContent}
          </div>
        );
      },
    };
  });

  useBodyLock(true);

  useEffect(() => {
    const disposables = createDisposableList();

    disposables.push(captureFocusForReturn());
    const overlayEl = overlayRef.current;
    if (overlayEl) {
      overlayEl.focus({ preventScroll: true });
      disposables.push(createFocusTrap(overlayEl));
    }

    const preloadNeighbors = () => {
      const items = propsRef.current.content;
      const idx = indexSignal.value;
      const start = idx - _kPreloadRange < 0 ? 0 : idx - _kPreloadRange;
      const end =
        idx + _kPreloadRange > items.length - 1
          ? items.length - 1
          : idx + _kPreloadRange;
      for (let i = start; i <= end; i++) {
        if (i === idx) continue;
        for (const m of items[i].media) {
          if (m.type === 'video') {
            if (m.poster) preloader.preload(m.poster, 'image');
          } else {
            preloader.preload(m.src, 'image');
          }
        }
      }
    };

    disposables.push(
      observeDomEvent(window, 'resize', () => {
        sizeSignal.value = getSize();
        sliderRef.current?.adjust();
      }),
      observeDomEvent(window, 'keydown', (e) => {
        if (e.key === 'Escape') {
          propsRef.current.onClose();
        }
      }),
      reaction(() => [indexSignal], preloadNeighbors),
    );

    preloadNeighbors();

    const initialIdx = indexSignal.value;
    const initialSrc = propsRef.current.content[initialIdx]?.media[0]?.src;
    if (initialSrc) {
      disposables.push(
        preloader.onLoaded(initialSrc, () => loadingCtrl.onReady(initialIdx)),
      );
    }

    return disposables.dispose;
  }, []);

  return createPortal(
    <div
      ref={overlayRef}
      className="rk-reel-overlay"
      role="dialog"
      aria-modal="true"
      aria-label={props.ariaLabel ?? 'Video player'}
      tabIndex={-1}
    >
      <div className="rk-reel-container">
        <Observe signals={[sizeSignal]}>
          {() => {
            const {
              content: items,
              loop: loopProp = false,
              enableNavKeys: navKeys = true,
              enableWheel: wheel = true,
              wheelDebounceMs: wheelMs,
              transitionDuration: duration,
              swipeDistanceFactor: swipeFactor,
              initialIndex: startIndex = 0,
            } = propsRef.current;
            return (
              <Reel
                count={items.length}
                size={sizeSignal.value}
                direction="vertical"
                loop={loopProp}
                enableNavKeys={navKeys}
                enableWheel={wheel}
                wheelDebounceMs={wheelMs}
                transitionDuration={duration}
                swipeDistanceFactor={swipeFactor}
                initialIndex={startIndex}
                apiRef={sliderRef}
                beforeChange={handleBeforeChange}
                afterChange={handleAfterChange}
                onSlideDragStart={handleSlideDragStart}
                onSlideDragEnd={handleSlideDragEnd}
                onSlideDragCanceled={handleSlideDragCanceled}
                itemBuilder={itemBuilder}
              />
            );
          }}
        </Observe>

        <Observe
          signals={[loadingCtrl.isLoading, loadingCtrl.isError, indexSignal]}
        >
          {() => {
            const idx = indexSignal.value;
            const {
              renderLoading,
              renderError,
              content: items,
            } = propsRef.current;
            const currentItem = items[idx] as T;

            if (loadingCtrl.isError.value) {
              return renderError ? (
                <>{renderError({ item: currentItem, activeIndex: idx })}</>
              ) : (
                <div
                  className="rk-reel-media-error"
                  role="img"
                  aria-label="Content unavailable"
                >
                  <ImageOff size={48} strokeWidth={1.5} aria-hidden="true" />
                  <span className="rk-reel-media-error-text">
                    Content unavailable
                  </span>
                </div>
              );
            }
            if (loadingCtrl.isLoading.value) {
              return renderLoading ? (
                <>{renderLoading({ item: currentItem, activeIndex: idx })}</>
              ) : (
                <div className="rk-reel-loader" />
              );
            }
            return null;
          }}
        </Observe>

        <Observe signals={[indexSignal, innerMediaTypeSignal]}>
          {() => {
            const activeIndex = indexSignal.value;
            const innerType = innerMediaTypeSignal.value;
            const { renderControls, onClose, content } = propsRef.current;
            const hasVideo =
              content[activeIndex]?.media.some((m) => m.type === 'video') ??
              false;
            const multiMedia = content[activeIndex]?.media.length > 1;
            const soundDisabled = multiMedia && innerType === 'image';

            if (renderControls) {
              return (
                <>
                  {renderControls({
                    item: content[activeIndex] as T,
                    onClose,
                    soundState,
                    activeIndex,
                    content,
                  })}
                </>
              );
            }
            return (
              <PlayerControls
                onClose={onClose}
                showSound={hasVideo}
                soundDisabled={soundDisabled}
              />
            );
          }}
        </Observe>

        <Observe
          signals={[indexSignal, innerMediaTypeSignal, timelineState.duration]}
        >
          {() => {
            const idx = indexSignal.value;
            const item = propsRef.current.content[idx];
            const mode: TimelineMode = propsRef.current.timeline ?? 'auto';
            const minDuration =
              propsRef.current.timelineMinDurationSeconds ??
              _kDefaultTimelineMinDurationSeconds;
            if (!item) return null;
            if (mode === 'never') return null;

            const anyVideo = item.media.some((m) => m.type === 'video');
            const isSingle = item.media.length === 1;
            const activeMediaIsVideo = isSingle
              ? item.media[0]?.type === 'video'
              : innerMediaTypeSignal.value === 'video';

            if (mode === 'always') {
              if (!anyVideo) return null;
            } else {
              if (!activeMediaIsVideo) return null;
              if (timelineState.duration.value < minDuration) return null;
            }

            const defaultContent = <TimelineBar />;

            const renderTl = propsRef.current.renderTimeline;
            if (renderTl) {
              return (
                <>
                  {renderTl({
                    item: item as T,
                    activeIndex: idx,
                    timelineState,
                    defaultContent,
                  })}
                </>
              );
            }
            return defaultContent;
          }}
        </Observe>
      </div>

      <Observe signals={[indexSignal]}>
        {() => {
          const idx = indexSignal.value;
          const { renderNavigation: renderNav, content: items } =
            propsRef.current;

          if (renderNav) {
            return (
              <>
                {renderNav({
                  item: items[idx],
                  onPrev: handlePrev,
                  onNext: handleNext,
                  activeIndex: idx,
                  count: items.length,
                })}
              </>
            );
          }
          return (
            <div className="rk-reel-nav-arrows">
              <button
                onClick={handlePrev}
                className="rk-reel-button rk-reel-nav-button"
                aria-label="Previous"
              >
                <ChevronUp size={28} />
              </button>
              <button
                onClick={handleNext}
                className="rk-reel-button rk-reel-nav-button"
                aria-label="Next"
              >
                <ChevronDown size={28} />
              </button>
            </div>
          );
        }}
      </Observe>
    </div>,
    document.body,
  );
}

/**
 * Full-screen, Instagram/TikTok-style vertical reel player overlay.
 *
 * Renders a portal containing a virtualized vertical slider with media
 * playback, gesture/keyboard/wheel navigation, and optional sound controls.
 * Supports full customization via render props for overlays, slides,
 * controls, and navigation.
 *
 * Wraps content in a {@link SoundProvider} for shared mute/unmute state.
 * Locks body scroll while open. Closes on Escape key.
 *
 * @typeParam T - Content item type. Defaults to {@link ContentItem}.
 *
 * @example Basic usage with default ContentItem
 * ```tsx
 * <ReelPlayerOverlay
 *   isOpen={isOpen}
 *   onClose={() => setOpen(false)}
 *   content={items}
 * />
 * ```
 *
 * @example Custom data type
 * ```tsx
 * interface MyItem extends BaseContentItem {
 *   title: string;
 * }
 *
 * <ReelPlayerOverlay<MyItem>
 *   isOpen={isOpen}
 *   onClose={close}
 *   content={myItems}
 *   renderSlideOverlay={() => null}
 * />
 * ```
 *
 * @example Custom controls with sub-components
 * ```tsx
 * <ReelPlayerOverlay
 *   isOpen={isOpen}
 *   onClose={close}
 *   content={items}
 *   renderControls={({ onClose }) => (
 *     <>
 *       <CloseButton onClick={onClose} />
 *       <SoundButton />
 *     </>
 *   )}
 * />
 * ```
 */
export function ReelPlayerOverlay<T extends BaseContentItem = ContentItem>(
  props: ReelPlayerOverlayProps<T>,
): React.ReactElement | null {
  if (!props.isOpen) return null;

  return (
    <SoundProvider>
      <TimelineProvider>
        <ReelPlayerContent {...props} />
      </TimelineProvider>
    </SoundProvider>
  );
}

// packages/reelkit-angular-reel-player/src/lib/reel-player-overlay/reel-player-overlay.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  Injector,
  NgZone,
  ViewEncapsulation,
  afterNextRender,
  computed,
  contentChild,
  effect,
  inject,
  input,
  linkedSignal,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import { DOCUMENT, NgTemplateOutlet } from '@angular/common';
import {
  LucideAngularModule,
  LucideIconProvider,
  LUCIDE_ICONS,
  ChevronUp,
  ChevronDown,
} from 'lucide-angular';
import {
  noop,
  clamp,
  captureFrame,
  captureFocusForReturn,
  createFocusTrap,
  BodyLockService,
  ReelComponent,
  RkReelItemDirective,
  toAngularSignal,
  createContentLoadingController,
  createContentPreloader,
  type ReelApi,
  type ContentLoadingController,
  type ContentPreloader,
} from '@reelkit/angular';
import { SoundStateService } from '../sound-state/sound-state.service';
import { TimelineStateService } from '../timeline-state/timeline-state.service';
import { RkTimelineBarComponent } from '../timeline-bar/timeline-bar.component';
import { RkMediaSlideComponent } from '../media-slide/media-slide.component';
import { shared as sharedVideo } from '../video-slide/video-slide.component';
import { RkSlideOverlayComponent } from '../slide-overlay/slide-overlay.component';
import { RkCloseButtonComponent } from '../player-controls/close-button.component';
import { RkSoundButtonComponent } from '../player-controls/sound-button.component';
import {
  RkPlayerSlideDirective,
  RkPlayerSlideOverlayDirective,
  RkPlayerControlsDirective,
  RkPlayerTimelineDirective,
  RkPlayerNavigationDirective,
  RkPlayerNestedSlideDirective,
  RkPlayerNestedNavigationDirective,
  RkPlayerLoadingDirective,
  RkPlayerErrorDirective,
} from '../template-slots/player-template-slots';
import type {
  BaseContentItem,
  ContentItem,
  MediaType,
  PlayerSoundState,
  PlayerTimelineState,
  TimelineMode,
} from '../types';

const _kDefaultAspectRatio = 9 / 16;
const _kMobileBreakpointPx = 768;
const _kDefaultTimelineMinDurationSeconds = 30;

/**
 * Full-screen, Instagram/TikTok-style vertical reel player overlay.
 *
 * Renders a portal-like overlay containing a virtualized vertical `rk-reel`
 * slider with media playback, gesture/keyboard/wheel navigation, and optional
 * sound controls. Supports full customization via `@ContentChild` template
 * slots for overlays, slides, controls, and navigation.
 *
 * Locks body scroll while open. Closes on Escape key.
 * Provides `SoundStateService` at the component level.
 *
 * @example
 * ```html
 * <rk-reel-player-overlay
 *   [isOpen]="isOpen"
 *   [content]="items"
 *   (closed)="isOpen = false"
 * />
 * ```
 */
@Component({
  selector: 'rk-reel-player-overlay',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    SoundStateService,
    TimelineStateService,
    {
      provide: LUCIDE_ICONS,
      useValue: new LucideIconProvider({ ChevronUp, ChevronDown }),
      multi: true,
    },
  ],
  imports: [
    NgTemplateOutlet,
    LucideAngularModule,
    ReelComponent,
    RkReelItemDirective,
    RkMediaSlideComponent,
    RkSlideOverlayComponent,
    RkCloseButtonComponent,
    RkSoundButtonComponent,
    RkTimelineBarComponent,
  ],
  template: `
    @if (isOpen()) {
      <div
        #overlayEl
        class="rk-reel-overlay"
        role="dialog"
        aria-modal="true"
        [attr.aria-label]="ariaLabel()"
        tabindex="-1"
      >
        <div
          class="rk-reel-container"
          [style.width.px]="size()[0] || null"
          [style.height.px]="size()[1] || null"
        >
          <rk-reel
            [count]="content().length"
            [size]="size()"
            direction="vertical"
            [loop]="loop()"
            [enableNavKeys]="enableNavKeys()"
            [enableWheel]="enableWheel()"
            [wheelDebounceMs]="wheelDebounceMs()"
            [transitionDuration]="transitionDuration()"
            [swipeDistanceFactor]="swipeDistanceFactor()"
            [initialIndex]="initialIndex()"
            (apiReady)="onApiReady($event)"
            (beforeChange)="onBeforeChange()"
            (afterChange)="onAfterChange($event)"
            (slideDragStart)="onSlideDragStart()"
            (slideDragEnd)="onSlideDragEnd()"
            (slideDragCanceled)="onSlideDragCanceled()"
          >
            <ng-template rkReelItem let-index let-itemSize="size">
              @let item = content()[index];
              @let isActive = activeIndex() === index;

              <div
                class="rk-reel-slide-wrapper"
                role="group"
                aria-roledescription="slide"
                [attr.aria-label]="
                  'Slide ' + (index + 1) + ' of ' + content().length
                "
                [style.width.px]="itemSize[0]"
                [style.height.px]="itemSize[1]"
              >
                @if (slideTemplate()) {
                  <ng-container
                    [ngTemplateOutlet]="slideTemplate()!.templateRef"
                    [ngTemplateOutletContext]="{
                      $implicit: item,
                      index: index,
                      size: itemSize,
                      isActive: isActive,
                      slideKey: item.id,
                      onReady: getOnReady(index),
                      onWaiting: getOnWaiting(index),
                      onError: getOnError(index),
                    }"
                  />
                } @else {
                  <rk-media-slide
                    [content]="item"
                    [isActive]="isActive"
                    [width]="itemSize[0]"
                    [height]="itemSize[1]"
                    [enableWheel]="enableWheel()"
                    [onReady]="getOnReady(index)"
                    [onWaiting]="getOnWaiting(index)"
                    [onError]="getOnError(index)"
                    [nestedSlideTemplate]="
                      nestedSlideTemplate()?.templateRef ?? null
                    "
                    [nestedNavTemplate]="
                      nestedNavTemplate()?.templateRef ?? null
                    "
                    (videoRef)="isActive && onVideoRef($event)"
                    (innerMediaType)="isActive && onInnerMediaType($event)"
                    (innerApiReady)="onInnerApiReady($event)"
                  />

                  @if (slideOverlayTemplate()) {
                    <ng-container
                      [ngTemplateOutlet]="slideOverlayTemplate()!.templateRef"
                      [ngTemplateOutletContext]="{
                        $implicit: item,
                        index: index,
                        isActive: isActive,
                      }"
                    />
                  } @else {
                    @let asContent = asContentItem(item);
                    <rk-slide-overlay
                      [author]="asContent?.author"
                      [description]="asContent?.description"
                      [likes]="asContent?.likes"
                    />
                  }
                }
              </div>
            </ng-template>
          </rk-reel>

          @if (isError()) {
            @if (errorSlot()) {
              <ng-container
                [ngTemplateOutlet]="errorSlot()!.templateRef"
                [ngTemplateOutletContext]="{
                  $implicit: activeIndex(),
                  item: content()[activeIndex()],
                  innerActiveIndex: null,
                }"
              />
            } @else {
              <div
                class="rk-reel-media-error"
                role="img"
                aria-label="Content unavailable"
              >
                <svg
                  width="48"
                  height="48"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  aria-hidden="true"
                >
                  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                  <circle cx="8.5" cy="8.5" r="1.5" />
                  <polyline points="21 15 16 10 5 21" />
                  <line x1="4" y1="4" x2="20" y2="20" />
                </svg>
                <span class="rk-reel-media-error-text"
                  >Content unavailable</span
                >
              </div>
            }
          } @else if (isLoading()) {
            @if (loadingSlot()) {
              <ng-container
                [ngTemplateOutlet]="loadingSlot()!.templateRef"
                [ngTemplateOutletContext]="{
                  $implicit: activeIndex(),
                  item: content()[activeIndex()],
                  innerActiveIndex: null,
                }"
              />
            } @else {
              <div class="rk-reel-loader"></div>
            }
          }

          @if (controlsTemplate()) {
            <ng-container
              [ngTemplateOutlet]="controlsTemplate()!.templateRef"
              [ngTemplateOutletContext]="{
                $implicit: closeFn,
                item: content()[activeIndex()],
                activeIndex: activeIndex(),
                content: content(),
                soundState: soundStateFacade,
                onClose: closeFn,
              }"
            />
          } @else {
            <rk-close-button (clicked)="close()" />
            @if (activeSlideHasVideo()) {
              <rk-sound-button [isDisabled]="isSoundDisabled()" />
            }
          }

          @if (shouldRenderTimeline()) {
            @if (timelineTemplate()) {
              <ng-container
                [ngTemplateOutlet]="timelineTemplate()!.templateRef"
                [ngTemplateOutletContext]="{
                  $implicit: content()[activeIndex()],
                  activeIndex: activeIndex(),
                  timelineState: timelineStateFacade,
                }"
              />
            } @else {
              <rk-timeline-bar />
            }
          }
        </div>

        @if (navigationTemplate()) {
          <ng-container
            [ngTemplateOutlet]="navigationTemplate()!.templateRef"
            [ngTemplateOutletContext]="{
              $implicit: onPrevFn,
              item: content()[activeIndex()],
              activeIndex: activeIndex(),
              count: content().length,
              onPrev: onPrevFn,
              onNext: onNextFn,
            }"
          />
        } @else {
          <div class="rk-reel-nav-arrows">
            <button
              class="rk-reel-button rk-reel-nav-btn"
              (click)="onPrev()"
              aria-label="Previous slide"
              [disabled]="!loop() && activeIndex() === 0"
              [attr.aria-disabled]="!loop() && activeIndex() === 0"
            >
              <lucide-angular [img]="ChevronUpIcon" [size]="28" />
            </button>
            <button
              class="rk-reel-button rk-reel-nav-btn"
              (click)="onNext()"
              aria-label="Next slide"
              [disabled]="!loop() && activeIndex() === content().length - 1"
              [attr.aria-disabled]="
                !loop() && activeIndex() === content().length - 1
              "
            >
              <lucide-angular [img]="ChevronDownIcon" [size]="28" />
            </button>
          </div>
        }
      </div>
    }
  `,
})
export class RkReelPlayerOverlayComponent<
  T extends BaseContentItem = ContentItem,
> {
  readonly isOpen = input.required<boolean>();
  readonly content = input.required<T[]>();
  readonly initialIndex = input<number>(0);

  /** Accessible label for the dialog. Defaults to "Video player". */
  readonly ariaLabel = input<string>('Video player');

  /**
   * Aspect ratio (width / height) for the player container on desktop.
   * Defaults to 9/16. On mobile (< 768px), the player uses the full viewport.
   */
  readonly aspectRatio = input<number | undefined>(undefined);

  readonly transitionDuration = input<number>(300);
  readonly swipeDistanceFactor = input<number>(0.12);
  readonly loop = input<boolean>(false);
  readonly enableNavKeys = input<boolean>(true);
  readonly enableWheel = input<boolean>(true);
  readonly wheelDebounceMs = input<number>(200);

  /**
   * Whether the built-in playback timeline bar renders over the active video.
   *
   * @default 'auto'
   */
  readonly timeline = input<TimelineMode>('auto');

  /**
   * Minimum video duration (seconds) for `timeline='auto'` to render the
   * built-in bar. Short looping clips below this threshold are suppressed.
   *
   * @default 30
   */
  readonly timelineMinDurationSeconds = input<number>(
    _kDefaultTimelineMinDurationSeconds,
  );

  readonly closed = output<void>();
  readonly slideChange = output<number>();
  readonly apiReady = output<ReelApi>();

  readonly slideTemplate = contentChild(RkPlayerSlideDirective<T>);
  readonly slideOverlayTemplate = contentChild(
    RkPlayerSlideOverlayDirective<T>,
  );
  readonly controlsTemplate = contentChild(RkPlayerControlsDirective<T>);
  readonly timelineTemplate = contentChild(RkPlayerTimelineDirective<T>);
  readonly navigationTemplate = contentChild(RkPlayerNavigationDirective);
  readonly nestedSlideTemplate = contentChild(RkPlayerNestedSlideDirective);
  readonly nestedNavTemplate = contentChild(RkPlayerNestedNavigationDirective);
  protected readonly loadingSlot = contentChild(RkPlayerLoadingDirective);
  protected readonly errorSlot = contentChild(RkPlayerErrorDirective);

  private readonly _activeIndex = linkedSignal(() =>
    this.isOpen() ? this.initialIndex() : 0,
  );
  readonly activeIndex = this._activeIndex.asReadonly();

  private readonly _innerActiveMediaType = signal<MediaType | null>(null);

  private _reelApi: ReelApi | null = null;
  private _innerApi: ReelApi | null = null;
  private _videoEl: HTMLVideoElement | null = null;
  private _videoPausedOnDrag = false;

  protected readonly ChevronUpIcon = ChevronUp;
  protected readonly ChevronDownIcon = ChevronDown;

  /**
   * Stable arrow-function references passed into template context objects.
   * Using bound methods (`.bind(this)`) in template expressions creates a new
   * function instance on every change-detection cycle, defeating OnPush.
   */
  readonly closeFn = (): void => this.close();
  readonly onPrevFn = (): void => this.onPrev();
  readonly onNextFn = (): void => this.onNext();

  /**
   * A stable, template-safe facade over `SoundStateService` that satisfies
   * the `PlayerSoundState` interface. Passed into the `rkPlayerControls`
   * template context so custom control templates can read and toggle mute
   * state without requiring a direct `SoundStateService` injection.
   *
   * Arrow functions are used so `this` is always bound correctly when the
   * template calls `soundState.toggle()`.
   */
  readonly soundStateFacade: PlayerSoundState = {
    muted: () => this._soundState.muted(),
    disabled: () => this._soundState.disabled(),
    toggle: () => this._soundState.toggle(),
  };

  /**
   * Template-safe facade over `TimelineStateService`. Arrow functions bind
   * `this` correctly when consumers read signals from the `rkPlayerControls`
   * template context.
   */
  readonly timelineStateFacade: PlayerTimelineState = {
    duration: () => this._timelineState.duration(),
    currentTime: () => this._timelineState.currentTime(),
    progress: () => this._timelineState.progress(),
    bufferedRanges: () => this._timelineState.bufferedRanges(),
    isScrubbing: () => this._timelineState.isScrubbing(),
    seek: (seconds) => this._timelineState.seek(seconds),
    bindInteractions: (target) =>
      this._timelineState.controller.bindInteractions(target),
  };

  protected readonly isSoundDisabled = computed(() => {
    const idx = this.activeIndex();
    return (
      (this.content()[idx]?.media.length ?? 0) > 1 &&
      this._innerActiveMediaType() === 'image'
    );
  });

  /**
   * Whether the active slide contains at least one video track. Derived as a
   * `computed()` so the template never triggers impure method calls on each
   * change-detection cycle.
   */
  protected readonly activeSlideHasVideo = computed(
    () =>
      this.content()[this.activeIndex()]?.media.some(
        (m) => m.type === 'video',
      ) ?? false,
  );

  /**
   * Decides whether the built-in timeline bar renders for the active slide.
   * Reacts to the `timeline` mode, the active slide's media shape, and the
   * controller's live duration signal.
   */
  protected readonly shouldRenderTimeline = computed(() => {
    const mode = this.timeline();
    if (mode === 'never') return false;
    const item = this.content()[this.activeIndex()];
    if (!item) return false;
    const anyVideo = item.media.some((m) => m.type === 'video');
    if (mode === 'always') return anyVideo;
    const isSingle = item.media.length === 1;
    const activeMediaIsVideo = isSingle
      ? item.media[0]?.type === 'video'
      : this._innerActiveMediaType() === 'video';
    if (!activeMediaIsVideo) return false;
    return this._timelineState.duration() >= this.timelineMinDurationSeconds();
  });

  private readonly _preloader: ContentPreloader = createContentPreloader({
    maxCacheSize: 1000,
  });
  private readonly _loadingCtrl: ContentLoadingController =
    createContentLoadingController(true, 0);

  private readonly _sizeSignal = signal<[number, number]>([0, 0]);
  readonly size = this._sizeSignal.asReadonly();

  private readonly _overlayEl =
    viewChild<ElementRef<HTMLDivElement>>('overlayEl');

  private readonly _bodyLock = inject(BodyLockService);
  private readonly _soundState = inject(SoundStateService);
  private readonly _timelineState = inject(TimelineStateService);
  private readonly _zone = inject(NgZone);
  private readonly _destroyRef = inject(DestroyRef);
  private readonly _document = inject(DOCUMENT);
  private readonly _injector = inject(Injector);

  protected readonly isLoading = toAngularSignal(
    this._loadingCtrl.isLoading,
    this._destroyRef,
  );

  protected readonly isError = toAngularSignal(
    this._loadingCtrl.isError,
    this._destroyRef,
  );

  private _preloaderDispose: (() => void) | null = null;
  private _restoreFocus: (() => void) | null = null;
  private _releaseFocusTrap: (() => void) | null = null;

  constructor() {
    this._sizeSignal.set(this._getSize());
    this._listenToEscape();
    this._listenToResize();

    this._destroyRef.onDestroy(() => {
      this._bodyLock.unlock();
      this._releaseFocusTrap?.();
      this._restoreFocus?.();
    });

    effect(() => {
      this._preloadNeighbors(this.activeIndex(), this.content());
    });

    effect(() => {
      if (this.isOpen()) {
        this._bodyLock.lock();
        this._setupInitialPreload();
        this._restoreFocus = captureFocusForReturn();
        // Defer focus + trap activation until after the next render cycle
        // so the overlay element created by @if(isOpen()) is in the DOM.
        // afterNextRender fires after Angular has flushed the view,
        // avoiding the race condition that Promise.resolve().then() has:
        // microtasks can fire before Angular's change detection flushes
        // the @if branch.
        afterNextRender(
          () => {
            const el = untracked(() => this._overlayEl())?.nativeElement;
            if (el) {
              el.focus();
              this._releaseFocusTrap = createFocusTrap(el);
            }
          },
          { injector: this._injector },
        );
      } else {
        this._bodyLock.unlock();
        if (this._preloaderDispose) {
          this._preloaderDispose();
          this._preloaderDispose = null;
        }
        this._releaseFocusTrap?.();
        this._releaseFocusTrap = null;
        this._restoreFocus?.();
        this._restoreFocus = null;
      }
    });
  }

  close(): void {
    this._soundState.reset();
    this.closed.emit();
  }

  onPrev(): void {
    this._reelApi?.prev();
  }

  onNext(): void {
    this._reelApi?.next();
  }

  onApiReady(api: ReelApi): void {
    this._reelApi = api;
    this.apiReady.emit(api);
  }

  onBeforeChange(): void {
    this._soundState.setDisabled(true);

    if (this._videoEl) {
      this._videoEl.pause();
      const key = this._videoEl.dataset['slideKey'];
      const frame = captureFrame(this._videoEl);
      if (key && frame) {
        sharedVideo.capturedFrames.set(key, frame);
      }
    }
  }

  onAfterChange(event: { index: number }): void {
    const index = event.index;
    this._loadingCtrl.setActiveIndex(index);

    const src = this.content()[index]?.media[0]?.src;
    if (src && this._preloader.isErrored(src)) {
      this._loadingCtrl.onError(index);
    } else if (src && this._preloader.isLoaded(src)) {
      this._loadingCtrl.onReady(index);
    }

    this._activeIndex.set(index);
    this._innerActiveMediaType.set(null);
    this._soundState.setDisabled(false);

    this.slideChange.emit(index);
  }

  getOnReady(index: number): () => void {
    return () => {
      this._loadingCtrl.onReady(index);
      const src = this.content()[index]?.media[0]?.src;
      if (src) this._preloader.markLoaded(src);
    };
  }

  getOnWaiting(index: number): () => void {
    return () => this._loadingCtrl.onWaiting(index);
  }

  getOnError(index: number): () => void {
    return () => {
      const src = this.content()[index]?.media[0]?.src;
      if (src) this._preloader.markErrored(src);
      this._loadingCtrl.onError(index);
    };
  }

  onVideoRef(ref: HTMLVideoElement | null): void {
    this._videoEl = ref;
  }

  onInnerMediaType(type: MediaType): void {
    this._innerActiveMediaType.set(type);
  }

  onInnerApiReady(api: ReelApi): void {
    this._innerApi = api;
  }

  onSlideDragStart(): void {
    this._innerApi?.unobserve();

    if (this._videoEl && !this._videoEl.paused) {
      this._videoEl.pause();
      this._videoPausedOnDrag = true;
    }
  }

  onSlideDragEnd(): void {
    this._innerApi?.observe();
    // A committed drag will be followed by onAfterChange, not onSlideDragCanceled.
    // Clear the flag here so a stale true cannot trigger a spurious play() call
    // if the event sequence is ever emitted out of expected order.
    this._videoPausedOnDrag = false;
  }

  onSlideDragCanceled(): void {
    if (this._videoPausedOnDrag && this._videoEl) {
      this._zone.runOutsideAngular(() => {
        this._videoEl!.play().catch(noop);
      });
    }
    this._videoPausedOnDrag = false;
  }

  /**
   * Attempts to cast a BaseContentItem to ContentItem for the default overlay.
   * Returns undefined if the item lacks the expected fields.
   */
  protected asContentItem(item: T): ContentItem | undefined {
    const record = item as Record<string, unknown>;
    if ('author' in record || 'description' in record || 'likes' in record) {
      return item as unknown as ContentItem;
    }
    return undefined;
  }

  private _getSize(): [number, number] {
    const win = this._document.defaultView;
    if (!win) return [0, 0];

    // Guard against degenerate aspect ratios (0, NaN, Infinity, negative).
    // Any such value would produce a zero-width or infinite-height container,
    // breaking layout entirely. Fall back to the default 9:16 ratio.
    const rawRatio = this.aspectRatio() ?? _kDefaultAspectRatio;
    const ratio =
      Number.isFinite(rawRatio) && rawRatio > 0
        ? rawRatio
        : _kDefaultAspectRatio;

    const windowWidth = win.innerWidth;
    const windowHeight = win.innerHeight;

    if (windowWidth < _kMobileBreakpointPx) {
      return [windowWidth, windowHeight];
    }

    let width = windowHeight * ratio;
    let height = windowHeight;

    if (width > windowWidth) {
      width = windowWidth;
      height = windowWidth / ratio;
    }

    return [width, height];
  }

  private _listenToEscape(): void {
    this._document.addEventListener('keydown', this._onKeyDown);
    this._destroyRef.onDestroy(() =>
      this._document.removeEventListener('keydown', this._onKeyDown),
    );
  }

  private readonly _onKeyDown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape' && this.isOpen()) {
      this.close();
    }
  };

  private _listenToResize(): void {
    const win = this._document.defaultView;
    if (!win) return;

    this._zone.runOutsideAngular(() => {
      win.addEventListener('resize', this._onResize);
      this._destroyRef.onDestroy(() =>
        win.removeEventListener('resize', this._onResize),
      );
    });
  }

  private readonly _onResize = (): void => {
    this._zone.run(() => {
      this._sizeSignal.set(this._getSize());
      this._reelApi?.adjust();
    });
  };

  private _setupInitialPreload(): void {
    const idx = this.initialIndex();
    this._loadingCtrl.setActiveIndex(idx);

    const src = this.content()[idx]?.media[0]?.src;
    if (src && this._preloader.isErrored(src)) {
      this._loadingCtrl.onError(idx);
    } else if (src && this._preloader.isLoaded(src)) {
      this._loadingCtrl.onReady(idx);
    } else if (src) {
      this._preloaderDispose = this._preloader.onLoaded(src, () =>
        this._loadingCtrl.onReady(idx),
      );
    }
  }

  private _preloadNeighbors(idx: number, items: readonly T[]): void {
    if (!this.isOpen() || items.length === 0) return;

    const range = 2;
    const start = clamp(idx - range, 0, items.length - 1);
    const end = clamp(idx + range, 0, items.length - 1);

    for (let i = start; i <= end; i++) {
      if (i === idx) continue;
      for (const m of items[i].media) {
        if (m.type === 'video') {
          if (m.poster) this._preloader.preload(m.poster, 'image');
        } else {
          this._preloader.preload(m.src, 'image');
        }
      }
    }
  }
}
