// packages/reelkit-angular/src/lib/context/reel-context.ts
import { InjectionToken, type Signal } from '@angular/core';

/**
 * Shape of the reactive context value shared by a `rk-reel` host
 * with its descendant `rk-reel-indicator` components.
 */
export interface ReelContextValue {
  index: Signal<number>;

  count: Signal<number>;

  /**
   * Programmatically navigate to a slide.
   * @param index   - Target slide index.
   * @param animate - When `true`, animate the transition.
   */
  goTo: (index: number, animate?: boolean) => Promise<void>;
}

export const RK_REEL_CONTEXT = new InjectionToken<ReelContextValue>(
  'RK_REEL_CONTEXT',
);

// packages/reelkit-react/src/lib/ReelContext.ts
import { createContext, useContext } from 'react';
import type { Signal } from '@reelkit/core';

/**
 * Values exposed by a parent {@link Reel} component to its children
 * via React context. Use {@link useReelContext} to access.
 */
export interface ReelContextValue {
  /** The active slide index signal. */
  index: Signal<number>;

  /** The total slide count signal. */
  count: Signal<number>;

  /** Navigate to a specific slide. */
  goTo: (index: number, animate?: boolean) => Promise<void>;
}

/** @internal */
export const ReelContext = createContext<ReelContextValue | null>(null);

/**
 * Returns the {@link ReelContextValue} from the nearest parent
 * {@link Reel}, or `null` if none exists.
 */
export const useReelContext = (): ReelContextValue | null =>
  useContext(ReelContext);
