// packages/reelkit-angular-reel-player/src/lib/video-slide/video-slide.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
  ViewEncapsulation,
  afterRenderEffect,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import { createSharedVideo, captureFrame } from '@reelkit/angular';
import { SoundStateService } from '../sound-state/sound-state.service';

/**
 * Shared video element instance — one per application, not per component.
 * Reused across all `RkVideoSlideComponent` instances so that iOS audio
 * context continuity is maintained when navigating between slides.
 */
const shared = createSharedVideo({
  className: 'rk-video-slide-element',
  disableRemotePlayback: true,
  disablePictureInPicture: true,
});

let activeToken: symbol | null = null;

/**
 * Renders a single video slide using a shared `<video>` element for iOS
 * sound continuity. Manages playback lifecycle (play/pause on active state),
 * persists playback position, and captures poster frames on deactivation.
 *
 * Must be rendered inside a component that provides `SoundStateService`.
 *
 * @example
 * ```html
 * <rk-video-slide
 *   [src]="item.src"
 *   [poster]="item.poster"
 *   [aspectRatio]="item.aspectRatio"
 *   [width]="size[0]"
 *   [height]="size[1]"
 *   [isActive]="isActive"
 *   [slideKey]="item.id"
 *   (videoRef)="onVideoRef($event)"
 * />
 * ```
 */
@Component({
  selector: 'rk-video-slide',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { style: 'display:block;width:100%;height:100%' },
  template: `
    <div
      #container
      class="rk-video-slide-container"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-hidden]="!isActive() || !isInnerActive() || null"
      [style.width.px]="width()"
      [style.height.px]="height()"
    >
      @if (posterSrc()) {
        <img
          [src]="posterSrc()"
          alt=""
          [class]="
            'rk-video-slide-poster' +
            (showPoster() || hasPlayError() ? ' rk-visible' : '')
          "
          [style.object-fit]="isVertical() ? 'cover' : 'contain'"
        />
      }
      @if (!hasPlayError()) {
        <div
          [class]="'rk-video-slide-loader' + (isLoading() ? ' rk-visible' : '')"
        ></div>
      }
    </div>
  `,
})
export class RkVideoSlideComponent {
  readonly src = input.required<string>();
  readonly poster = input<string | undefined>(undefined);
  /** Accessible label describing the video content. */
  readonly ariaLabel = input<string>('');
  readonly aspectRatio = input.required<number>();
  readonly width = input<number>(0);
  readonly height = input<number>(0);
  readonly isActive = input<boolean>(false);

  /**
   * Whether this is the active item within a nested horizontal slider.
   * Defaults to `true` for slides not inside a nested slider.
   */
  readonly isInnerActive = input<boolean>(true);

  readonly slideKey = input.required<string>();

  readonly videoRef = output<HTMLVideoElement | null>();

  protected readonly isLoading = signal(false);
  protected readonly showPoster = signal(true);
  protected readonly posterSrc = signal<string | undefined>(undefined);
  /** Set when the browser blocks autoplay or the video source cannot be played. */
  protected readonly hasPlayError = signal(false);
  protected readonly isVertical = computed(() => this.aspectRatio() < 1);

  private readonly _containerRef =
    viewChild.required<ElementRef<HTMLDivElement>>('container');

  private readonly _soundState = inject(SoundStateService);
  private readonly _zone = inject(NgZone);

  constructor() {
    this._registerPlaybackEffect();
    this._registerMuteEffect();
  }

  /**
   * Manages the full playback lifecycle for the active slide:
   * attaches the shared video element, starts playback, captures frames,
   * and cleans up on deactivation.
   */
  private _registerPlaybackEffect(): void {
    afterRenderEffect((onCleanup) => {
      const shouldPlay = this.isActive() && this.isInnerActive();
      if (!shouldPlay) return;

      const container = untracked(() => this._containerRef().nativeElement);
      const video = shared.getVideo();
      const key = untracked(() => this.slideKey());
      const src = untracked(() => this.src());
      const poster = untracked(() => this.poster());
      const muted = untracked(() => this._soundState.muted());
      const vertical = untracked(() => this.aspectRatio() < 1);

      this.isLoading.set(true);
      this.showPoster.set(true);
      this.hasPlayError.set(false);

      const captured = shared.capturedFrames.get(key);
      this.posterSrc.set(captured ?? poster);

      const handleCanPlay = (): void =>
        this._zone.run(() => this.isLoading.set(false));
      const handleWaiting = (): void =>
        this._zone.run(() => this.isLoading.set(true));
      const handlePlaying = (): void =>
        this._zone.run(() => {
          this.isLoading.set(false);
          this.showPoster.set(false);
        });

      const token = Symbol();
      activeToken = token;

      video.addEventListener('canplay', handleCanPlay);
      video.addEventListener('waiting', handleWaiting);
      video.addEventListener('playing', handlePlaying);

      video.pause();
      video.src = src;
      video.muted = muted;

      const savedPosition = shared.playbackPositions.get(key);
      video.currentTime = savedPosition ?? 0;
      video.style.objectFit = vertical ? 'cover' : 'contain';

      container.appendChild(video);
      this.videoRef.emit(video);

      video
        .play()
        .catch(() => this._zone.run(() => this.hasPlayError.set(true)));

      onCleanup(() => {
        video.removeEventListener('canplay', handleCanPlay);
        video.removeEventListener('waiting', handleWaiting);
        video.removeEventListener('playing', handlePlaying);

        shared.playbackPositions.set(key, video.currentTime);

        const frame = captureFrame(video);
        if (frame) {
          shared.capturedFrames.set(key, frame);
        }

        // Only pause and remove if no new slide has taken ownership
        if (activeToken === token) {
          video.pause();
          activeToken = null;
        }

        if (video.parentNode === container) {
          container.removeChild(video);
        }

        this.videoRef.emit(null);
        this.isLoading.set(false);
        this.hasPlayError.set(false);
      });
    });
  }

  /**
   * Syncs the shared video element's muted state with `SoundStateService`.
   * Only `muted` is a reactive dependency here. The active check is a guard,
   * not a trigger — wrapped in `untracked()` so toggling isActive/isInnerActive
   * does not re-run this effect.
   */
  private _registerMuteEffect(): void {
    effect(() => {
      const muted = this._soundState.muted();
      const isCurrentlyActive = untracked(
        () => this.isActive() && this.isInnerActive(),
      );
      if (!isCurrentlyActive) return;
      shared.getVideo().muted = muted;
    });
  }
}

// packages/reelkit-react-reel-player/src/lib/VideoSlide.tsx
import React, {
  type CSSProperties,
  useRef,
  useEffect,
  useLayoutEffect,
  useState,
} from 'react';
import {
  createSignal,
  createSharedVideo,
  captureFrame,
  noop,
  Observe,
} from '@reelkit/react';
import { useSoundState } from './useSoundState';
import './VideoSlide.css';

/**
 * Props for the {@link VideoSlide} component.
 */
export interface VideoSlideProps {
  /** URL of the video source. */
  src: string;

  /** Optional poster image shown while video loads. */
  poster?: string;

  /** Width / height ratio. Values < 1 use `cover`, >= 1 use `contain`. */
  aspectRatio: number;

  /** [width, height] in pixels. */
  size: [number, number];

  /** Whether this slide is the active (visible) slide in the parent reel. */
  isActive: boolean;

  /** Whether this slide is the active item in a nested horizontal slider. Defaults to `true`. */
  isInnerActive?: boolean;

  /** Unique key for persisting playback position and captured frames (e.g. "content-5" or "content-5:media-2"). */
  slideKey: string;

  /** Callback to report the shared video element ref to the parent for drag pause/resume. */
  onVideoRef?: (ref: HTMLVideoElement | null) => void;

  /** Additional CSS class for the root container. */
  className?: string;

  /** Additional inline styles merged onto the root container. */
  style?: CSSProperties;
}

const shared = createSharedVideo({
  className: 'rk-video-slide-element',
  disableRemotePlayback: true,
  disablePictureInPicture: true,
});

const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect;

/**
 * Renders a single video slide using a shared `<video>` element for iOS
 * sound continuity. Manages playback lifecycle (play/pause on
 * active state), persists playback position, and captures poster frames
 * on deactivation for seamless visual transitions.
 *
 * Shows a poster image and a wave loader while the video is buffering.
 *
 * Must be rendered inside a {@link SoundProvider}.
 *
 * @example
 * ```tsx
 * <VideoSlide
 *   src="/video.mp4"
 *   poster="/thumb.jpg"
 *   aspectRatio={9 / 16}
 *   size={[400, 700]}
 *   isActive={true}
 *   slideKey="slide-1"
 *   style={{ borderRadius: 12 }}
 * />
 * ```
 */
const VideoSlide: React.FC<VideoSlideProps> = ({
  src,
  poster,
  aspectRatio,
  size,
  isActive,
  isInnerActive = true,
  slideKey,
  onVideoRef,
  className,
  style,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const soundState = useSoundState();
  const shouldPlay = isActive && isInnerActive;
  const isVertical = aspectRatio < 1;
  const [isLoading, showPoster] = useState(
    () => [createSignal(false), createSignal(true)] as const,
  )[0];

  // Mount shared video element to this container when active
  useIsomorphicLayoutEffect(() => {
    if (!shouldPlay || !containerRef.current) return;

    const video = shared.getVideo();
    const container = containerRef.current;

    // Show loader and poster initially
    isLoading.value = true;
    showPoster.value = true;

    // Video event handlers for loading state
    const handleCanPlay = () => (isLoading.value = false);
    const handleWaiting = () => (isLoading.value = true);
    const handlePlaying = () => {
      isLoading.value = false;
      showPoster.value = false;
    };

    video.addEventListener('canplay', handleCanPlay);
    video.addEventListener('waiting', handleWaiting);
    video.addEventListener('playing', handlePlaying);

    // Update video properties
    video.src = src;
    video.muted = soundState.muted.value;

    // Restore saved playback position or start from beginning
    const savedPosition = shared.playbackPositions.get(slideKey);
    video.currentTime = savedPosition ?? 0;

    // Update object-fit based on aspect ratio
    video.style.objectFit = isVertical ? 'cover' : 'contain';

    // Append to this container
    container.appendChild(video);

    // Report ref to parent
    if (onVideoRef) {
      onVideoRef(video);
    }

    // Play
    // Autoplay may be prevented by the browser
    video.play().catch(noop);

    return () => {
      // Remove event listeners
      video.removeEventListener('canplay', handleCanPlay);
      video.removeEventListener('waiting', handleWaiting);
      video.removeEventListener('playing', handlePlaying);

      // Save current playback position before removing
      shared.playbackPositions.set(slideKey, video.currentTime);

      // Capture current frame to use as poster when returning
      const frame = captureFrame(video);
      if (frame) {
        shared.capturedFrames.set(slideKey, frame);
      }

      // Remove from this container when unmounting or becoming inactive
      if (video.parentNode === container) {
        container.removeChild(video);
      }
      if (onVideoRef) {
        onVideoRef(null);
      }

      isLoading.value = false;
    };
  }, [shouldPlay, src, isVertical, slideKey, onVideoRef]);

  // Sync muted state with sound context
  useEffect(() => {
    if (!shouldPlay) return;
    const video = shared.getVideo();
    if (video) video.muted = soundState.muted.value;
    return soundState.muted.observe(() => {
      if (video) video.muted = soundState.muted.value;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shouldPlay]);

  return (
    <div
      ref={containerRef}
      className={
        className
          ? `rk-video-slide-container ${className}`
          : 'rk-video-slide-container'
      }
      style={{
        width: size[0],
        height: size[1],
        ...style,
      }}
    >
      {/* Poster image with fade out transition */}
      {/* Use captured frame if available, otherwise fall back to original poster */}
      <Observe signals={[showPoster]}>
        {() => {
          const posterSrc = shared.capturedFrames.get(slideKey) ?? poster;
          if (!posterSrc) return null;
          return (
            <img
              src={posterSrc}
              alt=""
              className={`rk-video-slide-poster ${!shouldPlay || showPoster.value ? 'rk-visible' : ''}`}
              style={{
                objectFit: isVertical ? 'cover' : 'contain',
              }}
            />
          );
        }}
      </Observe>

      {/* Wave loader for buffering/loading state */}
      <Observe signals={[isLoading]}>
        {() => (
          <div
            className={`rk-video-slide-loader ${isLoading.value ? 'rk-visible' : ''}`}
          />
        )}
      </Observe>
    </div>
  );
};

export default VideoSlide;
