// apps/example-vue/src/pages/ImagePreviewVideoPage.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import {
  LightboxOverlay,
  lightboxFadeTransition,
  lightboxZoomTransition,
  slideTransition,
  useVideoSlideRenderer,
  type LightboxItem,
} from '@reelkit/vue-lightbox';
import type { TransitionTransformFn } from '@reelkit/vue';
import { cdnUrl } from '@reelkit/example-data';
import '@reelkit/vue-lightbox/styles.css';

const _kTransitions: { label: string; fn: TransitionTransformFn }[] = [
  { label: 'slide', fn: slideTransition },
  { label: 'fade', fn: lightboxFadeTransition },
  { label: 'zoom-in', fn: lightboxZoomTransition },
];

const sampleItems: LightboxItem[] = [
  {
    src: cdnUrl('samples/images/image-01.jpg'),
    title: 'Mountain River',
    description: 'A beautiful mountain river flowing through the forest.',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/videos/video-01.mp4'),
    type: 'video',
    poster: cdnUrl('samples/videos/video-poster-01.jpg'),
    title: 'For Bigger Blazes',
    description: 'Sample video demonstrating video support in the lightbox.',
  },
  {
    src: cdnUrl('samples/images/image-03.jpg'),
    title: 'Foggy Forest',
    description: 'Misty morning in the dense forest.',
    width: 1600,
    height: 900,
  },
  {
    src: cdnUrl('samples/videos/video-12.mp4'),
    type: 'video',
    poster: cdnUrl('samples/videos/video-poster-12.jpg'),
    title: 'With Sound',
    description: 'Video with audio — unmute via the sound toggle to hear it.',
  },
  {
    src: cdnUrl('samples/images/image-05.jpg'),
    title: 'Autumn Path',
    description:
      'A winding path through the autumn forest covered in golden leaves.',
    width: 1600,
    height: 1067,
  },
  {
    src: cdnUrl('samples/images/image-09.jpg'),
    title: 'Puppy Portrait',
    description: 'An adorable puppy looking at the camera with curious eyes.',
    width: 900,
    height: 1350,
  },
];

const open = ref(false);
const initialIndex = ref(0);
const transitionFn = ref<TransitionTransformFn>(slideTransition);

const { VideoSlideRenderer, VideoControlsRenderer, SoundProvider } =
  useVideoSlideRenderer(sampleItems);

const openAt = (index: number) => {
  initialIndex.value = index;
  open.value = true;
};

const onKeyActivate = (e: KeyboardEvent, index: number) => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault();
    openAt(index);
  }
};

watch(open, (isOpen, _, onCleanup) => {
  if (!isOpen) return;
  const html = document.documentElement;
  const prev = html.style.overscrollBehaviorY;
  html.style.overscrollBehaviorY = 'contain';
  onCleanup(() => {
    html.style.overscrollBehaviorY = prev;
  });
});
</script>

<template>
  <div class="image-gallery-page">
    <header class="gallery-header">
      <h1>Mixed Gallery (Images + Video)</h1>
      <p>
        Click on any item to open the lightbox. Video items use the opt-in
        <code>useVideoSlideRenderer</code> composable.
      </p>
      <div class="transition-selector">
        <span>Transition:</span>
        <button
          v-for="t in _kTransitions"
          :key="t.label"
          class="transition-btn"
          :class="{ active: transitionFn === t.fn }"
          @click="transitionFn = t.fn"
        >
          {{ t.label }}
        </button>
      </div>
    </header>

    <div class="gallery-grid">
      <div
        v-for="(item, index) in sampleItems"
        :key="index"
        class="gallery-item"
        role="button"
        tabindex="0"
        @click="openAt(index)"
        @keydown="onKeyActivate($event, index)"
      >
        <img
          :src="item.type === 'video' ? item.poster : item.src"
          :alt="item.title || `Item ${index + 1}`"
          loading="lazy"
        />
        <div class="gallery-item-overlay">
          <span v-if="item.type === 'video'" class="play-badge">
            <svg width="14" height="16" viewBox="0 0 14 16" fill="#000">
              <path d="M0 0l14 8-14 8z" />
            </svg>
          </span>
          <span v-if="item.title" class="gallery-item-title">{{
            item.title
          }}</span>
        </div>
      </div>
    </div>

    <SoundProvider>
      <LightboxOverlay
        v-model:is-open="open"
        :items="sampleItems"
        :initial-index="initialIndex"
        :transition-fn="transitionFn"
      >
        <template #slide="scope">
          <VideoSlideRenderer v-bind="scope" />
        </template>
        <template #controls="scope">
          <VideoControlsRenderer v-bind="scope" />
        </template>
      </LightboxOverlay>
    </SoundProvider>
  </div>
</template>

<style scoped>
.image-gallery-page {
  min-height: 100dvh;
  padding: 56px 24px 24px;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
}

.gallery-header {
  max-width: 1200px;
  margin: 0 auto 32px;
  text-align: center;
  color: #fff;
}

.gallery-header h1 {
  margin: 0 0 12px;
  font-size: 2.5rem;
  font-weight: 700;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.gallery-header p {
  margin: 0;
  font-size: 1rem;
  color: rgba(255, 255, 255, 0.7);
}

.gallery-header code {
  background: rgba(255, 255, 255, 0.08);
  padding: 2px 6px;
  border-radius: 4px;
  font-size: 0.9em;
}

.transition-selector {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin-top: 16px;
}

.transition-selector span {
  color: rgba(255, 255, 255, 0.7);
  font-size: 0.9rem;
}

.transition-btn {
  padding: 6px 14px;
  border: 1px solid rgba(255, 255, 255, 0.2);
  background: rgba(255, 255, 255, 0.05);
  color: rgba(255, 255, 255, 0.7);
  border-radius: 20px;
  font-size: 0.85rem;
  cursor: pointer;
  transition: all 0.2s ease;
  text-transform: capitalize;
}

.transition-btn:hover {
  background: rgba(255, 255, 255, 0.1);
  border-color: rgba(255, 255, 255, 0.3);
}

.transition-btn.active {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-color: transparent;
  color: #fff;
}

.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 16px;
  max-width: 1200px;
  margin: 0 auto;
}

.gallery-item {
  position: relative;
  border-radius: 12px;
  overflow: hidden;
  cursor: pointer;
  aspect-ratio: 4 / 3;
  background: rgba(255, 255, 255, 0.05);
  transition:
    transform 0.3s ease,
    box-shadow 0.3s ease;
}

.gallery-item:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
}

.gallery-item:focus {
  outline: 2px solid #667eea;
  outline-offset: 2px;
}

.gallery-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s ease;
}

.gallery-item:hover img {
  transform: scale(1.05);
}

.gallery-item-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 16px;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.8));
  opacity: 0;
  transition: opacity 0.3s ease;
  display: flex;
  align-items: center;
  gap: 8px;
}

.gallery-item:hover .gallery-item-overlay {
  opacity: 1;
}

.play-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.9);
  flex-shrink: 0;
}

.gallery-item-title {
  color: #fff;
  font-size: 14px;
  font-weight: 500;
}

@media (max-width: 600px) {
  .image-gallery-page {
    padding: 48px 12px 12px;
  }

  .gallery-header h1 {
    font-size: 1.75rem;
  }

  .gallery-grid {
    grid-template-columns: repeat(2, 1fr);
    gap: 8px;
  }

  .gallery-item {
    border-radius: 8px;
  }

  .gallery-item-overlay {
    opacity: 1;
    padding: 8px;
  }

  .gallery-item-title {
    font-size: 12px;
  }
}
</style>

// apps/example-react/src/app/pages/ImagePreviewVideoPage.tsx
import { useState, useCallback, useEffect } from 'react';
import {
  LightboxOverlay,
  lightboxFadeTransition,
  lightboxZoomTransition,
  slideTransition,
  useVideoSlideRenderer,
  type LightboxItem,
} from '@reelkit/react-lightbox';
import type { TransitionTransformFn } from '@reelkit/react';
import { cdnUrl } from '@reelkit/example-data';
import '@reelkit/react-lightbox/styles.css';
import './ImagePreviewPage.css';

const _kTransitions: { label: string; fn: TransitionTransformFn }[] = [
  { label: 'slide', fn: slideTransition },
  { label: 'fade', fn: lightboxFadeTransition },
  { label: 'zoom-in', fn: lightboxZoomTransition },
];

const sampleItems: LightboxItem[] = [
  {
    src: cdnUrl('samples/images/image-01.jpg'),
    title: 'Mountain River',
    description: 'A beautiful mountain river flowing through the forest.',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/videos/video-01.mp4'),
    type: 'video',
    poster: cdnUrl('samples/videos/video-poster-01.jpg'),
    title: 'For Bigger Blazes',
    description: 'Sample video demonstrating video support in the lightbox.',
  },
  {
    src: cdnUrl('samples/images/image-03.jpg'),
    title: 'Foggy Forest',
    description: 'Misty morning in the dense forest.',
    width: 1600,
    height: 900,
  },
  {
    src: cdnUrl('samples/videos/video-12.mp4'),
    type: 'video',
    poster: cdnUrl('samples/videos/video-poster-12.jpg'),
    title: 'With Sound',
    description: 'Video with audio — unmute via the sound toggle to hear it.',
  },
  {
    src: cdnUrl('samples/images/image-05.jpg'),
    title: 'Autumn Path',
    description:
      'A winding path through the autumn forest covered in golden leaves.',
    width: 1600,
    height: 1067,
  },
  {
    src: cdnUrl('samples/images/image-09.jpg'),
    title: 'Puppy Portrait',
    description: 'An adorable puppy looking at the camera with curious eyes.',
    width: 900,
    height: 1350,
  },
];

function ImagePreviewVideoPage() {
  const [previewIndex, setPreviewIndex] = useState<number | null>(null);
  const [transitionFn, setTransitionFn] = useState<TransitionTransformFn>(
    () => slideTransition,
  );

  const { renderSlide, renderControls, SoundProvider } =
    useVideoSlideRenderer(sampleItems);

  const handleImageClick = useCallback((index: number) => {
    setPreviewIndex(index);
  }, []);

  const handleClose = useCallback(() => {
    setPreviewIndex(null);
  }, []);

  useEffect(() => {
    if (previewIndex === null) return;
    const prev = document.documentElement.style.overscrollBehaviorY;
    document.documentElement.style.overscrollBehaviorY = 'contain';
    return () => {
      document.documentElement.style.overscrollBehaviorY = prev;
    };
  }, [previewIndex]);

  return (
    <div className="image-gallery-page">
      <div className="gallery-header">
        <h1>Mixed Gallery (Images + Video)</h1>
        <p>
          Click on any item to open the lightbox. Video items use the opt-in{' '}
          <code>useVideoSlideRenderer</code> hook.
        </p>
        <div className="transition-selector">
          <span>Transition:</span>
          {_kTransitions.map((t) => (
            <button
              key={t.label}
              className={`transition-btn ${transitionFn === t.fn ? 'active' : ''}`}
              onClick={() => setTransitionFn(() => t.fn)}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      <div className="gallery-grid">
        {sampleItems.map((item, index) => (
          <div
            key={index}
            className="gallery-item"
            onClick={() => handleImageClick(index)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                handleImageClick(index);
              }
            }}
          >
            <img
              src={item.type === 'video' ? item.poster : item.src}
              alt={item.title || `Item ${index + 1}`}
              loading="lazy"
            />
            <div className="gallery-item-overlay">
              {item.type === 'video' && (
                <span
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: 32,
                    height: 32,
                    borderRadius: '50%',
                    background: 'rgba(255,255,255,0.9)',
                    marginRight: 8,
                    verticalAlign: 'middle',
                  }}
                >
                  <svg width="14" height="16" viewBox="0 0 14 16" fill="#000">
                    <path d="M0 0l14 8-14 8z" />
                  </svg>
                </span>
              )}
              {item.title && (
                <span className="gallery-item-title">{item.title}</span>
              )}
            </div>
          </div>
        ))}
      </div>

      <SoundProvider>
        <LightboxOverlay
          isOpen={previewIndex !== null}
          images={sampleItems}
          initialIndex={previewIndex ?? 0}
          onClose={handleClose}
          transitionFn={transitionFn}
          renderSlide={renderSlide}
          renderControls={renderControls}
        />
      </SoundProvider>
    </div>
  );
}

export default ImagePreviewVideoPage;
