// apps/example-angular/src/app/pages/image-preview-url/image-preview-url-page.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  signal,
} from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import {
  RkLightboxUrlOverlayComponent,
  type LightboxItem,
} from '@reelkit/angular-lightbox';
import { createOverlayUrlState, urlIndexKey } from '@reelkit/angular';
import { cdnUrl } from '@reelkit/example-data';
import { createRouterUrlAdapter } from '@reelkit/angular/ng-router-url-adapter';

const _kParam = 'photo';

/** How many images this page pretends to have loaded so far. */
const _kPageSize = 3;

/** Stand-in for the round trip that fetches the next page. */
const _kFetchDelayMs = 900;

const sampleImages: LightboxItem[] = [
  { src: cdnUrl('samples/images/image-01.jpg'), title: 'Mountain River' },
  { src: cdnUrl('samples/images/image-02.jpg'), title: 'Snowy Peaks' },
  { src: cdnUrl('samples/images/image-03.jpg'), title: 'Foggy Forest' },
  { src: cdnUrl('samples/images/image-04.jpg'), title: 'Ocean Waves' },
  { src: cdnUrl('samples/images/image-05.jpg'), title: 'Autumn Path' },
];

/**
 * The lightbox with its open state in the URL: the address bar names the
 * visible slide, the link can be shared, and the back button closes.
 *
 * This application is routed, so the Router drives every read and write — the
 * default History adapter would leave the Router's own location stale.
 */
@Component({
  selector: 'app-image-preview-url-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RkLightboxUrlOverlayComponent, RouterLink],
  template: `
    <div class="image-gallery-page">
      <div class="gallery-header">
        <h1>URL Image Gallery</h1>
        <p>
          Every thumbnail is an ordinary link to
          <code>?photo=&lt;index&gt;</code> — open one in a new tab, copy its
          address, or press back to close. Paging through the gallery never
          piles up history entries.
        </p>
        <p>
          Back closes the gallery when you opened it from here — the link pushed
          an entry, so back pops to the grid. A shared link opened directly in a
          fresh tab has no history behind it, so back leaves the site; close
          with the ✕ button or Escape to stay on the grid.
        </p>
        <p>
          Only the first {{ pageSize }} images have loaded. The buttons below
          point past them, the way a shared link into a long feed does — the
          lightbox waits for the image to arrive instead of discarding the
          address.
        </p>
        <div class="transition-selector">
          <!-- A link, so the browser's own behaviour comes free: new tab, copy
               address, hover target, keyboard reach. -->
          <a
            class="transition-btn"
            [routerLink]="[]"
            [queryParams]="{ photo: total - 1 }"
          >
            Open image {{ total }} (link)
          </a>
          <!-- Navigating through the Router. No href, so the browser
               affordances are gone, but the URL still changes and back still
               closes. -->
          <button
            type="button"
            class="transition-btn"
            (click)="openViaRouter()"
          >
            Open image {{ total }} (router)
          </button>
          <!-- Straight through the controller. The adapter routes the write, so
               this lands in the same place — the difference is that the open
               started in code rather than from something the user could copy. -->
          <button
            type="button"
            class="transition-btn"
            (click)="photo.set(total - 1)"
          >
            Open image {{ total }} (controller.set)
          </button>
          @if (fetching()) {
            <span>Loading photo…</span>
          }
        </div>
      </div>

      <div class="gallery-grid">
        @for (image of loaded(); track image.src; let i = $index) {
          <a
            class="gallery-item"
            [routerLink]="[]"
            [queryParams]="{ photo: i }"
          >
            <img [src]="image.src" [alt]="image.title ?? ''" loading="lazy" />
            @if (image.title) {
              <div class="gallery-item-overlay">
                <span class="gallery-item-title">{{ image.title }}</span>
              </div>
            }
          </a>
        }
      </div>
    </div>

    <rk-lightbox-url-overlay [controller]="photo" [items]="loaded()" />
  `,
  // The gallery family shares one stylesheet — image-preview-video already
  // points here. A bespoke copy would drift the moment the family restyles.
  styleUrls: ['../image-preview/image-preview-page.css'],
})
export class ImagePreviewUrlPageComponent {
  private readonly _router = inject(Router);

  protected readonly pageSize = _kPageSize;
  protected readonly total = sampleImages.length;

  // Only part of the gallery has "arrived" — the rest stands in for pages this
  // feed has not fetched yet.
  protected readonly loaded = signal(sampleImages.slice(0, _kPageSize));
  protected readonly fetching = signal(false);

  protected openViaRouter(): void {
    void this._router.navigate([], {
      queryParams: { [_kParam]: this.total - 1 },
    });
  }

  // A plain index gallery, so the built-in `urlIndexKey` supplies the codec and
  // the bounded `locate`/`identify` — this windowed feed only adds a
  // `locateAsync` pager for links past the loaded window. No hand-rolled
  // locator. Built here (not inside the overlay) so `photo.set` stays on hand
  // for programmatic control.
  protected readonly photo = createOverlayUrlState({
    param: _kParam,
    adapter: createRouterUrlAdapter(),
    ...urlIndexKey(
      () => this.loaded().length,
      async (index) => {
        // Nothing left to fetch: this link names an image the feed lacks.
        if (index < 0 || index >= sampleImages.length) return null;

        this.fetching.set(true);
        await new Promise((done) => setTimeout(done, _kFetchDelayMs));
        this.loaded.set(sampleImages.slice(0, index + 1));
        this.fetching.set(false);

        return index; // urlIndexKey re-bounds it against the grown count
      },
    ),
  });
}

// apps/example-react/src/app/pages/ImagePreviewUrlPage.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { LightboxUrlOverlay, type LightboxItem } from '@reelkit/react-lightbox';
import {
  createSignal,
  Observe,
  Signal,
  useOverlayUrlState,
  urlIndexKey,
} from '@reelkit/react';
import { cdnUrl } from '@reelkit/example-data';
import { ImageOff } from 'lucide-react';
import { useReactRouterUrlAdapter } from '@reelkit/react/react-router-url-adapter';
import '@reelkit/react-lightbox/styles.css';
import './ImagePreviewPage.css';

const _kParam = 'photo';

/** How many images this page pretends to have loaded so far. */
const _kPageSize = 3;

/** Stand-in for the round trip that fetches the next page. */
const _kFetchDelayMs = 900;

const sampleImages: LightboxItem[] = [
  {
    src: cdnUrl('samples/images/image-01.jpg'),
    title: 'Mountain River',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/images/image-02.jpg'),
    title: 'Forest Path',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/images/image-03.jpg'),
    title: 'Lake at Dusk',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/images/image-04.jpg'),
    title: 'Coastal Cliffs',
    width: 1600,
    height: 1000,
  },
  {
    src: cdnUrl('samples/images/image-05.jpg'),
    title: 'Snow Ridge',
    width: 1600,
    height: 1000,
  },
];

const GalleryThumb: React.FC<{ src: string; alt: string }> = ({ src, alt }) => {
  const [error, setError] = useState(false);

  if (error) {
    return (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'rgba(255,255,255,0.3)',
          backgroundColor: '#1a1a1a',
        }}
      >
        <ImageOff size={28} strokeWidth={1.5} />
      </div>
    );
  }

  return (
    <img src={src} alt={alt} loading="lazy" onError={() => setError(true)} />
  );
};

/**
 * The lightbox with its open state in the URL: the address bar names the
 * visible slide, the link can be shared, and the back button closes.
 *
 * This application is routed, so the router drives every read and write — the
 * default History adapter would leave the router's own location stale.
 */
export function ImagePreviewUrlPage() {
  const adapter = useReactRouterUrlAdapter();
  const navigate = useNavigate();

  const [loaded, fetching] = useState(
    () =>
      // Only part of the gallery has "arrived" — the rest stands in for pages
      // this feed has not fetched yet.
      [
        createSignal(sampleImages.slice(0, _kPageSize)),
        createSignal(false),
      ] as [Signal<LightboxItem[]>, Signal<boolean>],
  )[0];

  // A plain index gallery, so the built-in `urlIndexKey` supplies the codec and
  // the bounded `locate`/`identify` — the only thing this windowed feed adds is
  // a `locateAsync` pager for links past the loaded window. No hand-rolled
  // locator. Keeping the controller here (not inside the overlay) leaves
  // `photo.set` on hand for programmatic control.
  const photo = useOverlayUrlState({
    param: _kParam,
    adapter,
    ...urlIndexKey(
      () => loaded.value.length,
      async (index) => {
        // Nothing left to fetch: this link names an image the feed lacks.
        if (index < 0 || index >= sampleImages.length) return null;

        fetching.value = true;
        await new Promise((done) => setTimeout(done, _kFetchDelayMs));
        loaded.value = sampleImages.slice(0, index + 1);
        fetching.value = false;

        return index; // urlIndexKey re-bounds it against the grown count
      },
    ),
  });

  return (
    <div className="image-gallery-page">
      <div className="gallery-header">
        <h1>URL Image Gallery</h1>
        <p>
          Every thumbnail is an ordinary link to{' '}
          <code>?photo=&lt;index&gt;</code>— open one in a new tab, copy its
          address, or press back to close. Paging through the gallery never
          piles up history entries.
        </p>
        <p>
          Back closes the gallery when you opened it from here — the link pushed
          an entry, so back pops to the gallery. A shared link opened directly
          in a fresh tab has no history behind it, so back leaves the site;
          close with the ✕ button or Escape to stay on the gallery.
        </p>
        <p>
          Only the first {_kPageSize} images have loaded. The buttons below all
          point past them, the way a shared link into a long feed does — the
          lightbox waits for the image to arrive instead of discarding the
          address.
        </p>
        <div className="transition-selector">
          {/* All three buttons open the same slide. They differ only in what
              the browser gets to know about it. */}

          {/* A link, so the browser's own behaviour comes free: new tab, copy
              address, hover target, keyboard reach. */}
          <Link
            to={`?${_kParam}=${sampleImages.length - 1}`}
            className="transition-btn"
          >
            Open image {sampleImages.length} (link)
          </Link>
          {/* Navigating through the router. No href, so the browser affordances
              are gone, but the URL still changes and back still closes. */}
          <button
            type="button"
            className="transition-btn"
            onClick={() => navigate(`?${_kParam}=${sampleImages.length - 1}`)}
          >
            Open image {sampleImages.length} (router)
          </button>
          {/* Straight through the controller. The adapter routes the write, so
              this ends up in the same place as the other two — the difference
              is that the open started in code rather than from something the
              user could copy or middle-click. */}
          <button
            type="button"
            className="transition-btn"
            onClick={() => photo.set(sampleImages.length - 1)}
          >
            Open image {sampleImages.length} (controller.set)
          </button>
          <Observe signals={[fetching]}>
            {() => (fetching.value ? <span>Loading photo…</span> : null)}
          </Observe>
        </div>
      </div>

      <Observe signals={[loaded]}>
        {() => (
          <div className="gallery-grid">
            {loaded.value.map((image, index) => (
              // The open state is a URL, so opening is a link. That buys the
              // browser's own behaviour for free: open in a new tab, copy the
              // address, see the target on hover, reach it by keyboard.
              <Link
                key={image.src}
                to={`?${_kParam}=${index}`}
                className="gallery-item"
              >
                <GalleryThumb
                  src={image.src}
                  alt={image.title || `Image ${index + 1}`}
                />
                <div className="gallery-item-overlay">
                  {image.title && (
                    <span className="gallery-item-title">{image.title}</span>
                  )}
                </div>
              </Link>
            ))}
          </div>
        )}
      </Observe>

      <Observe signals={[loaded]}>
        {() => <LightboxUrlOverlay controller={photo} images={loaded.value} />}
      </Observe>
    </div>
  );
}

export default ImagePreviewUrlPage;
