// apps/example-vue/src/pages/ReelPlayerPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  ReelPlayerOverlay,
  type ContentItem,
  type MediaItem,
} from '@reelkit/vue-reel-player';
import '@reelkit/vue-reel-player/styles.css';
import { Play } from 'lucide-vue-next';
import { cdnUrl, generateContent, getThumbnail } from '@reelkit/example-data';
import Thumbnail from '../components/Thumbnail.vue';

const _kContentCount = 50;

const isPlayerOpen = ref(false);
const selectedIndex = ref(0);

const content = computed<ContentItem[]>(() => {
  const items = generateContent(_kContentCount);
  items.splice(1, 0, {
    id: 'long-video-content',
    media: [
      {
        id: 'long-video',
        type: 'video',
        src: cdnUrl('samples/videos/video-06.mp4'),
        poster: cdnUrl('samples/videos/video-poster-06.jpg'),
        aspectRatio: 16 / 9,
      },
    ],
    author: {
      name: 'Timeline Demo',
      avatar: cdnUrl('samples/avatars/avatar-02.jpg'),
    },
    likes: 4200,
    description:
      'Long video: the playback timeline bar should render automatically.',
  });
  items.splice(3, 0, {
    id: 'broken-content',
    media: [
      {
        id: 'broken-img',
        type: 'image',
        src: 'https://broken.invalid/does-not-exist.jpg',
        aspectRatio: 9 / 16,
      },
    ],
    author: {
      name: 'Error Demo',
      avatar: cdnUrl('samples/avatars/avatar-01.jpg'),
    },
    likes: 0,
    description: 'This slide has a broken image to demonstrate error handling.',
  });
  return items;
});

const openPlayer = (index: number) => {
  selectedIndex.value = index;
  isPlayerOpen.value = true;
};

const closePlayer = () => {
  isPlayerOpen.value = false;
};
</script>

<template>
  <div class="page">
    <div class="container">
      <h1>Reel Player Demo</h1>
      <p class="subtitle">
        Click on any thumbnail to open the player. Swipe up/down or use arrow
        keys to navigate. Supports images, videos, and multi-media posts with
        horizontal sliders.
      </p>

      <div class="grid">
        <div
          v-for="(item, index) in content"
          :key="item.id"
          class="thumb"
          @click="openPlayer(index)"
        >
          <Thumbnail :src="getThumbnail(item)" />
          <div
            v-if="item.media.some((m: MediaItem) => m.type === 'video')"
            class="video-badge"
          >
            <Play :size="14" fill="#fff" color="#fff" />
          </div>
          <div v-if="item.media.length > 1" class="multi-badge">
            {{ item.media.length }}
          </div>
          <div class="author">
            <img :src="item.author.avatar" alt="" class="avatar" />
            <span class="author-name">{{ item.author.name }}</span>
          </div>
        </div>
      </div>
    </div>

    <ReelPlayerOverlay
      :is-open="isPlayerOpen"
      :content="content"
      :initial-index="selectedIndex"
      :timeline-min-duration-seconds="10"
      @close="closePlayer"
    />
  </div>
</template>

<style scoped>
.page {
  min-height: 100dvh;
  background-color: #111;
  padding: 56px 16px 16px;
  color: #fff;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
}

h1 {
  font-size: 1.5rem;
  margin-bottom: 24px;
  font-weight: 500;
}

.subtitle {
  color: rgba(255, 255, 255, 0.6);
  font-size: 0.9rem;
  margin-bottom: 32px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 8px;
}

.thumb {
  position: relative;
  aspect-ratio: 9 / 16;
  border-radius: 8px;
  overflow: hidden;
  cursor: pointer;
  background-color: #222;
  transition: transform 0.2s;
}

.thumb:hover {
  transform: scale(1.02);
}

.video-badge {
  position: absolute;
  top: 8px;
  right: 8px;
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background-color: rgba(0, 0, 0, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
}

.multi-badge {
  position: absolute;
  top: 8px;
  left: 8px;
  padding: 4px 8px;
  border-radius: 4px;
  background-color: rgba(0, 0, 0, 0.6);
  color: #fff;
  font-size: 0.7rem;
  font-weight: 500;
}

.author {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 32px 8px 8px;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.8));
  display: flex;
  align-items: center;
  gap: 6px;
}

.avatar {
  width: 20px;
  height: 20px;
  border-radius: 50%;
  object-fit: cover;
}

.author-name {
  color: #fff;
  font-size: 0.7rem;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// apps/example-react/src/app/pages/ReelPlayerPage.tsx
import React, { useState, useMemo } from 'react';
import { ImageOff, Play } from 'lucide-react';
import { ReelPlayerOverlay } from '@reelkit/react-reel-player';
import '@reelkit/react-reel-player/styles.css';
import {
  generateContent,
  getThumbnail,
} from '../components/reel-player/mockContent';
import { cdnUrl } from '@reelkit/example-data';

const CONTENT_COUNT = 50;

const Thumbnail: React.FC<{ src: string }> = ({ src }) => {
  const [error, setError] = useState(false);

  if (error) {
    return (
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'rgba(255,255,255,0.3)',
          gap: 4,
        }}
      >
        <ImageOff size={32} strokeWidth={1.5} />
        <span style={{ fontSize: 10 }}>Error</span>
      </div>
    );
  }

  return (
    <img
      src={src}
      alt=""
      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
      loading="lazy"
      onError={() => setError(true)}
    />
  );
};

function ReelPlayerPage() {
  const [isPlayerOpen, setIsPlayerOpen] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(0);

  const content = useMemo(() => {
    const items = generateContent(CONTENT_COUNT);
    // Insert a long video at index 1 so the built-in timeline bar is easy to find
    items.splice(1, 0, {
      id: 'long-video-content',
      media: [
        {
          id: 'long-video',
          type: 'video',
          src: cdnUrl('samples/videos/video-06.mp4'),
          poster: cdnUrl('samples/videos/video-poster-06.jpg'),
          aspectRatio: 16 / 9,
        },
      ],
      author: {
        name: 'Timeline Demo',
        avatar: cdnUrl('samples/avatars/avatar-02.jpg'),
      },
      likes: 4200,
      description:
        'Long video: the playback timeline bar should render automatically.',
    });
    // Insert a broken image slide at index 3 to demonstrate error handling
    items.splice(3, 0, {
      id: 'broken-content',
      media: [
        {
          id: 'broken-img',
          type: 'image',
          src: 'https://broken.invalid/does-not-exist.jpg',
          aspectRatio: 9 / 16,
        },
      ],
      author: {
        name: 'Error Demo',
        avatar: cdnUrl('samples/avatars/avatar-01.jpg'),
      },
      likes: 0,
      description:
        'This slide has a broken image to demonstrate error handling.',
    });
    return items;
  }, []);

  const openPlayer = (index: number) => {
    setSelectedIndex(index);
    setIsPlayerOpen(true);
  };

  const closePlayer = () => {
    setIsPlayerOpen(false);
  };

  return (
    <div
      style={{
        minHeight: '100dvh',
        backgroundColor: '#111',
        padding: '56px 16px 16px',
      }}
    >
      <div
        style={{
          maxWidth: 1200,
          margin: '0 auto',
        }}
      >
        <h1
          style={{
            color: '#fff',
            fontSize: '1.5rem',
            marginBottom: 24,
            fontWeight: 500,
          }}
        >
          Reel Player Demo
        </h1>
        <p
          style={{
            color: 'rgba(255,255,255,0.6)',
            fontSize: '0.9rem',
            marginBottom: 32,
          }}
        >
          Click on any thumbnail to open the player. Swipe up/down or use arrow
          keys to navigate. Supports images, videos, and multi-media posts with
          horizontal sliders.
        </p>

        {/* Thumbnail grid */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
            gap: 8,
          }}
        >
          {content.map((item, index) => {
            const hasVideo = item.media.some((m) => m.type === 'video');
            const isMulti = item.media.length > 1;

            return (
              <div
                key={item.id}
                onClick={() => openPlayer(index)}
                style={{
                  position: 'relative',
                  aspectRatio: '9 / 16',
                  borderRadius: 8,
                  overflow: 'hidden',
                  cursor: 'pointer',
                  backgroundColor: '#222',
                }}
              >
                <Thumbnail src={getThumbnail(item)} />

                {/* Video indicator */}
                {hasVideo && (
                  <div
                    style={{
                      position: 'absolute',
                      top: 8,
                      right: 8,
                      width: 28,
                      height: 28,
                      borderRadius: '50%',
                      backgroundColor: 'rgba(0,0,0,0.6)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    <Play size={14} fill="#fff" color="#fff" />
                  </div>
                )}

                {/* Multi-media indicator */}
                {isMulti && (
                  <div
                    style={{
                      position: 'absolute',
                      top: 8,
                      left: 8,
                      padding: '4px 8px',
                      borderRadius: 4,
                      backgroundColor: 'rgba(0,0,0,0.6)',
                      color: '#fff',
                      fontSize: '0.7rem',
                      fontWeight: 500,
                    }}
                  >
                    {item.media.length}
                  </div>
                )}

                {/* Hover overlay */}
                <div
                  style={{
                    position: 'absolute',
                    inset: 0,
                    backgroundColor: 'rgba(0,0,0,0)',
                    transition: 'background-color 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.3)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0)';
                  }}
                />

                {/* Author info */}
                <div
                  style={{
                    position: 'absolute',
                    bottom: 0,
                    left: 0,
                    right: 0,
                    padding: '32px 8px 8px',
                    background: 'linear-gradient(transparent, rgba(0,0,0,0.8))',
                  }}
                >
                  <div
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 6,
                    }}
                  >
                    <img
                      src={item.author.avatar}
                      alt=""
                      style={{
                        width: 20,
                        height: 20,
                        borderRadius: '50%',
                        objectFit: 'cover',
                      }}
                    />
                    <span
                      style={{
                        color: '#fff',
                        fontSize: '0.7rem',
                        fontWeight: 500,
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}
                    >
                      {item.author.name}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <ReelPlayerOverlay
        isOpen={isPlayerOpen}
        onClose={closePlayer}
        content={content}
        initialIndex={selectedIndex}
        timelineMinDurationSeconds={10}
      />
    </div>
  );
}

export default ReelPlayerPage;
