// apps/example-vue/src/pages/StoriesPlayerCustomPage.vue
<script setup lang="ts">
import { shallowRef } from 'vue';
import { StoriesOverlay, type StoriesGroup } from '@reelkit/vue-stories-player';
import { cdnUrl } from '@reelkit/example-data';
import '@reelkit/vue-stories-player/styles.css';
import HtmlProgressBar from './stories-player/HtmlProgressBar.vue';

type DemoId =
  | 'custom-header'
  | 'custom-footer'
  | 'custom-navigation'
  | 'custom-progress'
  | 'custom-loading-error'
  | 'theming'
  | 'custom-group-preview';

const _kDemos: { id: DemoId; title: string; description: string }[] = [
  {
    id: 'custom-header',
    title: 'Custom Header',
    description:
      'Uses the header slot to replace the default header with a minimal close button and custom author layout.',
  },
  {
    id: 'custom-footer',
    title: 'Custom Footer',
    description:
      'Uses the footer slot to add a reply input and action buttons below each story.',
  },
  {
    id: 'custom-navigation',
    title: 'Custom Navigation',
    description:
      'Uses the navigation slot to replace default chevron buttons with labeled pill buttons.',
  },
  {
    id: 'custom-progress',
    title: 'Custom Progress Bar',
    description:
      'Uses the progressBar slot to replace the default canvas bar with plain HTML segments.',
  },
  {
    id: 'custom-loading-error',
    title: 'Custom Loading / Error',
    description:
      'Uses the loading and error slots to replace the default spinner and error icon. Includes a broken image story.',
  },
  {
    id: 'theming',
    title: 'Themed via CSS Tokens',
    description:
      'Rebrands the stories overlay by overriding --rk-stories-* CSS custom properties in a stylesheet. No component code changes.',
  },
  {
    id: 'custom-group-preview',
    title: 'Custom Carousel Cards',
    description:
      'Uses the groupPreview slot to draw the desktop carousel cards beside the story: the preview frame, the author and a story count. Needs a window wider than 768px.',
  },
];

const _kAvatars = [
  cdnUrl('samples/avatars/avatar-13.jpg'),
  cdnUrl('samples/avatars/avatar-14.jpg'),
  cdnUrl('samples/avatars/avatar-15.jpg'),
];

const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 3600_000).toISOString();

const groups: StoriesGroup[] = [
  {
    author: { id: 'u1', name: 'Travel', avatar: _kAvatars[0], verified: true },
    stories: [
      {
        id: 'c1',
        mediaType: 'image',
        src: cdnUrl('samples/images/image-01.jpg'),
        createdAt: hoursAgo(1),
      },
      {
        id: 'c2',
        mediaType: 'image',
        src: cdnUrl('samples/images/image-02.jpg'),
        createdAt: hoursAgo(2),
      },
      {
        id: 'c3',
        mediaType: 'video',
        src: cdnUrl('samples/videos/video-01.mp4'),
        poster: cdnUrl('samples/videos/video-poster-01.jpg'),
        createdAt: hoursAgo(3),
      },
    ],
  },
  {
    author: { id: 'u2', name: 'Food', avatar: _kAvatars[1] },
    stories: [
      {
        id: 'c4',
        mediaType: 'image',
        src: cdnUrl('samples/images/image-03.jpg'),
        createdAt: hoursAgo(1),
      },
      {
        id: 'c5',
        mediaType: 'image',
        src: 'https://broken.invalid/does-not-exist.jpg',
        createdAt: hoursAgo(2),
      },
      {
        id: 'c6',
        mediaType: 'image',
        src: cdnUrl('samples/images/image-04.jpg'),
        createdAt: hoursAgo(3),
      },
    ],
  },
  {
    author: { id: 'u3', name: 'Music', avatar: _kAvatars[2], verified: true },
    stories: [
      {
        id: 'c7',
        mediaType: 'video',
        src: cdnUrl('samples/videos/video-02.mp4'),
        poster: cdnUrl('samples/videos/video-poster-02.jpg'),
        createdAt: hoursAgo(1),
      },
      {
        id: 'c8',
        mediaType: 'image',
        src: cdnUrl('samples/images/image-05.jpg'),
        createdAt: hoursAgo(2),
      },
    ],
  },
];

const activeDemo = shallowRef<DemoId | null>(null);
const close = () => {
  activeDemo.value = null;
};
</script>

<template>
  <div class="page">
    <div class="container">
      <h1>Custom Stories Player</h1>
      <p class="subtitle">
        Demonstrates scoped slot customization: headers, footers, navigation,
        progress bars, and loading/error states.
      </p>

      <div class="grid">
        <div v-for="demo in _kDemos" :key="demo.id" class="card">
          <h2>{{ demo.title }}</h2>
          <p>{{ demo.description }}</p>
          <button type="button" class="open" @click="activeDemo = demo.id">
            Open Demo
          </button>
        </div>
      </div>
    </div>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-header'"
      :groups="groups"
      @close="close"
    >
      <template
        #header="{
          author,
          onClose,
          isPaused,
          onTogglePause,
          isMuted,
          onToggleSound,
          isVideo,
        }"
      >
        <div class="custom-header">
          <div class="custom-header-author">
            <img :src="author.avatar" :alt="author.name" />
            <span>{{ author.name }}</span>
          </div>
          <div class="custom-header-actions">
            <button
              v-if="isVideo"
              type="button"
              class="pill"
              @click="onToggleSound"
            >
              {{ isMuted ? 'Unmute' : 'Mute' }}
            </button>
            <button type="button" class="pill" @click="onTogglePause">
              {{ isPaused ? 'Play' : 'Pause' }}
            </button>
            <button type="button" class="pill" @click="onClose">Close</button>
          </div>
        </div>
      </template>
    </StoriesOverlay>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-footer'"
      :groups="groups"
      @close="close"
    >
      <template #footer="{ author }">
        <div class="custom-footer">
          <input type="text" :placeholder="`Reply to ${author.name}...`" />
          <button type="button" class="pill">Send</button>
        </div>
      </template>
    </StoriesOverlay>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-navigation'"
      :groups="groups"
      @close="close"
    >
      <template
        #navigation="{ onPrevStory, onNextStory, onPrevGroup, onNextGroup }"
      >
        <div class="nav-column">
          <button type="button" class="pill group" @click="onPrevGroup">
            Prev Group
          </button>
          <button type="button" class="pill" @click="onPrevStory">Prev</button>
        </div>
        <div class="nav-gap" />
        <div class="nav-column">
          <button type="button" class="pill group" @click="onNextGroup">
            Next Group
          </button>
          <button type="button" class="pill" @click="onNextStory">Next</button>
        </div>
      </template>
    </StoriesOverlay>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-progress'"
      :groups="groups"
      @close="close"
    >
      <template #progressBar="{ totalStories, activeIndex, progress }">
        <HtmlProgressBar
          :total-stories="totalStories"
          :active-index="activeIndex"
          :progress="progress"
        />
      </template>
    </StoriesOverlay>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-loading-error'"
      :groups="groups"
      @close="close"
    >
      <template #loading="{ story }">
        <div class="custom-loading">Loading {{ story.mediaType }}...</div>
      </template>
      <template #error="{ story }">
        <div class="custom-error">
          <div class="custom-error-mark">!</div>
          <div>Failed to load {{ story.mediaType }}</div>
        </div>
      </template>
    </StoriesOverlay>

    <StoriesOverlay
      :is-open="activeDemo === 'custom-group-preview'"
      :groups="groups"
      desktop-layout="carousel"
      @close="close"
    >
      <template #groupPreview="{ group, story, onOpen }">
        <button
          type="button"
          class="preview-card"
          :aria-label="`Open stories by ${group.author.name}`"
          @click="onOpen"
        >
          <img
            v-if="story"
            class="preview-card-frame"
            :src="story.mediaType === 'video' ? story.poster : story.src"
            alt=""
          />
          <span class="preview-card-info">
            <span class="preview-card-count">
              {{ group.stories.length }}
              {{ group.stories.length === 1 ? 'story' : 'stories' }}
            </span>
            <span class="preview-card-author">
              <img :src="group.author.avatar" alt="" />
              {{ group.author.name }}
            </span>
          </span>
        </button>
      </template>
    </StoriesOverlay>

    <!-- Rethemed by the unscoped style at the bottom, which matches this
         overlay by its label. -->
    <StoriesOverlay
      :is-open="activeDemo === 'theming'"
      :groups="groups"
      aria-label="Themed stories"
      @close="close"
    />
  </div>
</template>

<style>
/* Unscoped: the overlay is teleported to the body, outside this page. */
.rk-stories-overlay[aria-label='Themed stories'] {
  --rk-stories-overlay-bg: #0f172a;
  --rk-stories-container-radius: 24px;
  --rk-stories-nav-bg: rgba(99, 102, 241, 0.35);
  --rk-stories-nav-bg-hover: rgba(168, 85, 247, 0.65);
  --rk-stories-top-shade-bg: linear-gradient(
    to bottom,
    rgba(99, 102, 241, 0.5) 0%,
    transparent 100%
  );
  --rk-stories-header-name-fg: #fef3c7;
  --rk-stories-ring-spin-duration: 2s;
}
</style>

<style scoped>
.page {
  min-height: 100dvh;
  background-color: #111;
  padding: 56px 16px 16px;
  color: #fff;
}

.container {
  max-width: 900px;
  margin: 0 auto;
}

h1 {
  font-size: 1.5rem;
  margin-bottom: 8px;
  font-weight: 500;
}

.subtitle {
  color: rgba(255, 255, 255, 0.6);
  font-size: 0.9rem;
  margin-bottom: 32px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 16px;
}

.card {
  background-color: #1a1a1a;
  border-radius: 12px;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.card h2 {
  font-size: 1.1rem;
  font-weight: 500;
}

.card p {
  color: rgba(255, 255, 255, 0.5);
  font-size: 0.8rem;
  line-height: 1.5;
  flex: 1;
}

.open {
  padding: 6px 14px;
  border-radius: 8px;
  border: none;
  font-size: 0.8rem;
  cursor: pointer;
  background-color: #fff;
  color: #000;
  font-weight: 500;
}

.pill {
  padding: 6px 14px;
  border-radius: 8px;
  border: none;
  font-size: 0.7rem;
  cursor: pointer;
  background: rgba(255, 255, 255, 0.15);
  color: #fff;
  backdrop-filter: blur(8px);
}

.pill.group {
  background: rgba(99, 102, 241, 0.3);
  color: #a78bfa;
}

.custom-header {
  position: absolute;
  top: 40px;
  left: 12px;
  right: 12px;
  z-index: 20;
  display: flex;
  align-items: center;
  justify-content: space-between;
  pointer-events: auto;
}

.custom-header-author {
  display: flex;
  align-items: center;
  gap: 8px;
  color: #fff;
  font-size: 13px;
  font-weight: 600;
}

.custom-header-author img {
  width: 28px;
  height: 28px;
  border-radius: 50%;
}

.custom-header-actions {
  display: flex;
  gap: 8px;
}

.custom-footer {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 16px 12px;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.7));
  display: flex;
  align-items: center;
  gap: 8px;
  z-index: 10;
  pointer-events: auto;
}

.custom-footer input {
  flex: 1;
  padding: 8px 12px;
  border-radius: 20px;
  border: 1px solid rgba(255, 255, 255, 0.3);
  background: rgba(255, 255, 255, 0.1);
  color: #fff;
  font-size: 13px;
  outline: none;
}

.nav-column {
  display: flex;
  flex-direction: column;
  gap: 8px;
  flex-shrink: 0;
}

.nav-gap {
  width: 16px;
}

.custom-loading {
  position: absolute;
  top: 22px;
  right: 72px;
  z-index: 20;
  color: #fff;
  font-size: 12px;
  background: rgba(99, 102, 241, 0.8);
  padding: 4px 12px;
  border-radius: 12px;
  pointer-events: none;
}

.custom-error {
  position: absolute;
  inset: 0;
  z-index: 5;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  background: linear-gradient(145deg, #2d1b1b 0%, #1a1a2e 100%);
  color: #ff6b6b;
  pointer-events: none;
  font-size: 14px;
}

.custom-error-mark {
  font-size: 48px;
}

.preview-card {
  position: relative;
  width: 100%;
  height: 100%;
  padding: 0;
  border: 2px solid rgba(167, 139, 250, 0.6);
  border-radius: 16px;
  overflow: hidden;
  cursor: pointer;
  background: #1e1b4b;
}

.preview-card-frame {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.preview-card-info {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  align-items: flex-start;
  gap: 6px;
  padding: 12px;
  background: linear-gradient(transparent 40%, rgba(30, 27, 75, 0.9));
}

.preview-card-count {
  padding: 2px 8px;
  border-radius: 10px;
  background: #6366f1;
  color: #fff;
  font-size: 11px;
}

.preview-card-author {
  display: flex;
  align-items: center;
  gap: 6px;
  color: #fff;
  font-size: 13px;
  font-weight: 600;
}

.preview-card-author img {
  width: 24px;
  height: 24px;
  border-radius: 50%;
}
</style>

// apps/example-react/src/app/pages/StoriesPlayerCustomPage.tsx
import { useState, useMemo } from 'react';
import {
  StoriesOverlay,
  type StoriesGroup,
} from '@reelkit/react-stories-player';
import { Observe, generate, type Signal } from '@reelkit/react';
import { cdnUrl } from '@reelkit/example-data';
import '@reelkit/react-stories-player/styles.css';

const AVATARS = [
  cdnUrl('samples/avatars/avatar-13.jpg'),
  cdnUrl('samples/avatars/avatar-14.jpg'),
  cdnUrl('samples/avatars/avatar-15.jpg'),
];

type DemoType =
  | 'custom-header'
  | 'custom-footer'
  | 'custom-navigation'
  | 'custom-progress'
  | 'custom-loading-error'
  | 'theming'
  | 'custom-group-preview'
  | null;

interface Demo {
  id: NonNullable<DemoType>;
  title: string;
  description: string;
}

const DEMOS: Demo[] = [
  {
    id: 'custom-header',
    title: 'Custom Header',
    description:
      'Uses renderHeader to replace the default header with a minimal close button and custom author layout.',
  },
  {
    id: 'custom-footer',
    title: 'Custom Footer',
    description:
      'Uses renderFooter to add a reply input and action buttons below each story.',
  },
  {
    id: 'custom-navigation',
    title: 'Custom Navigation',
    description:
      'Uses renderNavigation to replace default chevron buttons with labeled pill buttons.',
  },
  {
    id: 'custom-progress',
    title: 'Custom Progress Bar',
    description:
      'Uses renderProgressBar to replace the default canvas bar with a simple HTML progress element.',
  },
  {
    id: 'custom-loading-error',
    title: 'Custom Loading / Error',
    description:
      'Uses renderLoading and renderError to replace default spinner and error icon. Includes a broken image story.',
  },
  {
    id: 'theming',
    title: 'Themed via CSS Tokens',
    description:
      'Rebrands the stories overlay by overriding --rk-stories-* CSS custom properties in a stylesheet. No component code changes.',
  },
  {
    id: 'custom-group-preview',
    title: 'Custom Carousel Cards',
    description:
      'Uses renderGroupPreview to draw the desktop carousel cards beside the story: the preview frame, the author and a story count. Needs a window wider than 768px.',
  },
];

function generateGroups(): StoriesGroup[] {
  return [
    {
      author: {
        id: 'u1',
        name: 'Travel',
        avatar: AVATARS[0],
        verified: true,
      },
      stories: [
        {
          id: 'c1',
          mediaType: 'image',
          src: cdnUrl('samples/images/image-01.jpg'),
          createdAt: new Date(Date.now() - 3600_000).toISOString(),
        },
        {
          id: 'c2',
          mediaType: 'image',
          src: cdnUrl('samples/images/image-02.jpg'),
          createdAt: new Date(Date.now() - 7200_000).toISOString(),
        },
        {
          id: 'c3',
          mediaType: 'video',
          src: cdnUrl('samples/videos/video-01.mp4'),
          poster: cdnUrl('samples/videos/video-poster-01.jpg'),
          createdAt: new Date(Date.now() - 10800_000).toISOString(),
        },
      ],
    },
    {
      author: { id: 'u2', name: 'Food', avatar: AVATARS[1] },
      stories: [
        {
          id: 'c4',
          mediaType: 'image',
          src: cdnUrl('samples/images/image-03.jpg'),
          createdAt: new Date(Date.now() - 3600_000).toISOString(),
        },
        {
          id: 'c5',
          mediaType: 'image',
          src: 'https://broken.invalid/does-not-exist.jpg',
          createdAt: new Date(Date.now() - 7200_000).toISOString(),
        },
        {
          id: 'c6',
          mediaType: 'image',
          src: cdnUrl('samples/images/image-04.jpg'),
          createdAt: new Date(Date.now() - 10800_000).toISOString(),
        },
      ],
    },
    {
      author: { id: 'u3', name: 'Music', avatar: AVATARS[2], verified: true },
      stories: [
        {
          id: 'c7',
          mediaType: 'video',
          src: cdnUrl('samples/videos/video-02.mp4'),
          poster: cdnUrl('samples/videos/video-poster-02.jpg'),
          createdAt: new Date(Date.now() - 3600_000).toISOString(),
        },
        {
          id: 'c8',
          mediaType: 'image',
          src: cdnUrl('samples/images/image-05.jpg'),
          createdAt: new Date(Date.now() - 7200_000).toISOString(),
        },
      ],
    },
  ];
}

function HtmlProgressBar({
  totalStories,
  activeIndex,
  progress,
}: {
  totalStories: number;
  activeIndex: Signal<number>;
  progress: Signal<number>;
}) {
  return (
    <div
      style={{
        display: 'flex',
        gap: 4,
        padding: '8px 8px 0',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
      }}
    >
      <Observe signals={[activeIndex, progress]}>
        {() => (
          <>
            {generate(totalStories, (i) => {
              const ai = activeIndex.value;
              const p = progress.value;
              const fill = i < ai ? 100 : i === ai ? p * 100 : 0;
              return (
                <div
                  key={i}
                  style={{
                    flex: 1,
                    height: 3,
                    borderRadius: 2,
                    background: 'rgba(255,255,255,0.25)',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      width: `${fill}%`,
                      height: '100%',
                      background:
                        i < ai
                          ? '#6366f1'
                          : 'linear-gradient(90deg, #6366f1, #a78bfa)',
                      borderRadius: 2,
                      transition: i === ai ? 'none' : 'width 200ms',
                    }}
                  />
                </div>
              );
            })}
          </>
        )}
      </Observe>
    </div>
  );
}

const btnStyle: React.CSSProperties = {
  padding: '6px 14px',
  borderRadius: 8,
  border: 'none',
  fontSize: '0.8rem',
  cursor: 'pointer',
  transition: 'background 150ms',
};

function StoriesPlayerCustomPage() {
  const groups = useMemo(() => generateGroups(), []);
  const [activeDemo, setActiveDemo] = useState<DemoType>(null);

  return (
    <div
      style={{
        minHeight: '100dvh',
        backgroundColor: '#111',
        padding: '56px 16px 16px',
      }}
    >
      <div style={{ maxWidth: 900, margin: '0 auto' }}>
        <h1
          style={{
            color: '#fff',
            fontSize: '1.5rem',
            marginBottom: 8,
            fontWeight: 500,
          }}
        >
          Custom Stories Player
        </h1>
        <p
          style={{
            color: 'rgba(255,255,255,0.6)',
            fontSize: '0.9rem',
            marginBottom: 32,
          }}
        >
          Demonstrates render prop customization: headers, footers, navigation,
          progress bars, and loading/error states.
        </p>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: 16,
          }}
        >
          {DEMOS.map((demo) => (
            <div
              key={demo.id}
              style={{
                backgroundColor: '#1a1a1a',
                borderRadius: 12,
                padding: 20,
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <h2
                style={{ color: '#fff', fontSize: '1.1rem', fontWeight: 500 }}
              >
                {demo.title}
              </h2>
              <p
                style={{
                  color: 'rgba(255,255,255,0.5)',
                  fontSize: '0.8rem',
                  lineHeight: 1.5,
                  flex: 1,
                }}
              >
                {demo.description}
              </p>
              <button
                onClick={() => setActiveDemo(demo.id)}
                style={{
                  ...btnStyle,
                  backgroundColor: '#fff',
                  color: '#000',
                  fontWeight: 500,
                }}
              >
                Open Demo
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Custom Header */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-header'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        renderHeader={({
          author,
          onClose,
          isPaused,
          onTogglePause,
          isMuted,
          onToggleSound,
          isVideo,
        }) => (
          <div
            style={{
              position: 'absolute',
              top: 40,
              left: 12,
              right: 12,
              zIndex: 20,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              pointerEvents: 'auto',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <img
                src={author.avatar}
                alt={author.name}
                style={{ width: 28, height: 28, borderRadius: '50%' }}
              />
              <span style={{ color: '#fff', fontSize: 13, fontWeight: 600 }}>
                {author.name}
              </span>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              {isVideo && (
                <button
                  onClick={onToggleSound}
                  style={{
                    ...btnStyle,
                    background: 'rgba(255,255,255,0.15)',
                    color: '#fff',
                    fontSize: '0.7rem',
                  }}
                >
                  {isMuted ? 'Unmute' : 'Mute'}
                </button>
              )}
              <button
                onClick={onTogglePause}
                style={{
                  ...btnStyle,
                  background: 'rgba(255,255,255,0.15)',
                  color: '#fff',
                  fontSize: '0.7rem',
                }}
              >
                {isPaused ? 'Play' : 'Pause'}
              </button>
              <button
                onClick={onClose}
                style={{
                  ...btnStyle,
                  background: 'rgba(255,255,255,0.15)',
                  color: '#fff',
                  fontSize: '0.7rem',
                }}
              >
                Close
              </button>
            </div>
          </div>
        )}
      />

      {/* Custom Footer */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-footer'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        renderFooter={({ author }) => (
          <div
            style={{
              position: 'absolute',
              bottom: 0,
              left: 0,
              right: 0,
              padding: '16px 12px',
              background: 'linear-gradient(transparent, rgba(0,0,0,0.7))',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              zIndex: 10,
              pointerEvents: 'auto',
            }}
          >
            <input
              type="text"
              placeholder={`Reply to ${author.name}...`}
              style={{
                flex: 1,
                padding: '8px 12px',
                borderRadius: 20,
                border: '1px solid rgba(255,255,255,0.3)',
                background: 'rgba(255,255,255,0.1)',
                color: '#fff',
                fontSize: 13,
                outline: 'none',
              }}
            />
            <button
              style={{
                ...btnStyle,
                background: 'rgba(255,255,255,0.15)',
                color: '#fff',
              }}
            >
              Send
            </button>
          </div>
        )}
      />

      {/* Custom Navigation */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-navigation'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        renderNavigation={({
          onPrevStory,
          onNextStory,
          onPrevGroup,
          onNextGroup,
        }) => (
          <>
            <div
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
                flexShrink: 0,
              }}
            >
              <button
                onClick={onPrevGroup}
                style={{
                  ...btnStyle,
                  background: 'rgba(99,102,241,0.3)',
                  color: '#a78bfa',
                  backdropFilter: 'blur(8px)',
                }}
              >
                Prev Group
              </button>
              <button
                onClick={onPrevStory}
                style={{
                  ...btnStyle,
                  background: 'rgba(255,255,255,0.1)',
                  color: '#fff',
                  backdropFilter: 'blur(8px)',
                }}
              >
                Prev
              </button>
            </div>
            <div style={{ width: 16 }} />
            <div
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
                flexShrink: 0,
              }}
            >
              <button
                onClick={onNextGroup}
                style={{
                  ...btnStyle,
                  background: 'rgba(99,102,241,0.3)',
                  color: '#a78bfa',
                  backdropFilter: 'blur(8px)',
                }}
              >
                Next Group
              </button>
              <button
                onClick={onNextStory}
                style={{
                  ...btnStyle,
                  background: 'rgba(255,255,255,0.1)',
                  color: '#fff',
                  backdropFilter: 'blur(8px)',
                }}
              >
                Next
              </button>
            </div>
          </>
        )}
      />

      {/* Custom Progress Bar */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-progress'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        renderProgressBar={({ totalStories, activeIndex, progress }) => (
          <HtmlProgressBar
            totalStories={totalStories}
            activeIndex={activeIndex}
            progress={progress}
          />
        )}
      />

      {/* Custom Loading / Error */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-loading-error'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        renderLoading={({ story }) => (
          <div
            style={{
              position: 'absolute',
              top: 22,
              right: 72,
              zIndex: 20,
              color: '#fff',
              fontSize: 12,
              background: 'rgba(99,102,241,0.8)',
              padding: '4px 12px',
              borderRadius: 12,
              pointerEvents: 'none',
            }}
          >
            Loading {story.mediaType}...
          </div>
        )}
        renderError={({ story }) => (
          <div
            style={{
              position: 'absolute',
              inset: 0,
              zIndex: 5,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 12,
              background: 'linear-gradient(145deg, #2d1b1b 0%, #1a1a2e 100%)',
              color: '#ff6b6b',
              pointerEvents: 'none',
            }}
          >
            <div style={{ fontSize: 48 }}>!</div>
            <div style={{ fontSize: 14 }}>Failed to load {story.mediaType}</div>
          </div>
        )}
      />

      {/* Custom Carousel Cards */}
      <StoriesOverlay
        isOpen={activeDemo === 'custom-group-preview'}
        onClose={() => setActiveDemo(null)}
        groups={groups}
        desktopLayout="carousel"
        renderGroupPreview={({ group, story, onOpen }) => (
          <button
            type="button"
            aria-label={`Open stories by ${group.author.name}`}
            onClick={onOpen}
            style={{
              position: 'relative',
              width: '100%',
              height: '100%',
              padding: 0,
              border: '2px solid rgba(167,139,250,0.6)',
              borderRadius: 16,
              overflow: 'hidden',
              cursor: 'pointer',
              background: '#1e1b4b',
            }}
          >
            {story && (
              <img
                src={story.mediaType === 'video' ? story.poster : story.src}
                alt=""
                style={{
                  position: 'absolute',
                  inset: 0,
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                }}
              />
            )}
            <span
              style={{
                position: 'absolute',
                inset: 0,
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'flex-end',
                alignItems: 'flex-start',
                gap: 6,
                padding: 12,
                background:
                  'linear-gradient(transparent 40%, rgba(30,27,75,0.9))',
              }}
            >
              <span
                style={{
                  padding: '2px 8px',
                  borderRadius: 10,
                  background: '#6366f1',
                  color: '#fff',
                  fontSize: 11,
                }}
              >
                {group.stories.length}{' '}
                {group.stories.length === 1 ? 'story' : 'stories'}
              </span>
              <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                <img
                  src={group.author.avatar}
                  alt=""
                  style={{ width: 24, height: 24, borderRadius: '50%' }}
                />
                <span style={{ color: '#fff', fontSize: 13, fontWeight: 600 }}>
                  {group.author.name}
                </span>
              </span>
            </span>
          </button>
        )}
      />

      {/* Themed via CSS Tokens */}
      {activeDemo === 'theming' && (
        <>
          <style>{`
            .rk-stories-overlay {
              --rk-stories-overlay-bg: #0f172a;
              --rk-stories-container-radius: 24px;
              --rk-stories-nav-bg: rgba(99, 102, 241, 0.35);
              --rk-stories-nav-bg-hover: rgba(168, 85, 247, 0.65);
              --rk-stories-top-shade-bg: linear-gradient(
                to bottom,
                rgba(99, 102, 241, 0.5) 0%,
                transparent 100%
              );
              --rk-stories-header-name-fg: #fef3c7;
              --rk-stories-ring-spin-duration: 2s;
            }
          `}</style>
          <StoriesOverlay
            isOpen
            onClose={() => setActiveDemo(null)}
            groups={groups}
          />
        </>
      )}
    </div>
  );
}

export default StoriesPlayerCustomPage;
