// packages/reelkit-react-lightbox/src/lib/LightboxOverlay.tsx
/* eslint-disable react/jsx-no-useless-fragment */
import {
  type MutableRefObject,
  type ReactNode,
  type FC,
  useRef,
  useState,
  useEffect,
} from 'react';
import { createPortal } from 'react-dom';
import {
  createSignal,
  createContentLoadingController,
  createContentPreloader,
  createDisposableList,
  reaction,
  observeDomEvent,
  captureFocusForReturn,
  createFocusTrap,
  slideTransition,
  Reel,
  Observe,
  useBodyLock,
  SwipeToClose,
  type ReelApi,
  type ReelProps,
  type SwipeToCloseDirection,
  type TransitionTransformFn,
  type UrlStateController,
} from '@reelkit/react';
import { ChevronLeft, ChevronRight, ImageOff } from 'lucide-react';
import { useFullscreen } from '@reelkit/react';
import LightboxControls from './LightboxControls';
import type {
  ControlsRenderProps,
  SlideRenderProps,
  NavigationRenderProps,
  InfoRenderProps,
} from './types';
import './LightboxOverlay.css';

/**
 * Data for a single lightbox item (image or video).
 *
 * At minimum, provide `src`. Optional `title` and `description` are
 * rendered in the built-in info overlay (unless overridden via `renderInfo`).
 *
 * For video items, set `type: 'video'` and optionally provide a `poster`
 * thumbnail. Video rendering requires opting in via `useVideoSlideRenderer`.
 */
export interface LightboxItem {
  /** URL of the image or video. */
  src: string;

  /**
   * Item type. Defaults to `'image'` when omitted.
   * Video items require opting in via `useVideoSlideRenderer` and `renderSlide`.
   */
  type?: 'image' | 'video';

  /** Poster/thumbnail image for video items. Used for preloading and as placeholder. */
  poster?: string;

  /** Title displayed in the info overlay. */
  title?: string;

  /** Description displayed below the title in the info overlay. */
  description?: string;

  /** Intrinsic width of the image in pixels. Currently unused by the lightbox. */
  width?: number;

  /** Intrinsic height of the image in pixels. Currently unused by the lightbox. */
  height?: number;
}

/**
 * Subset of {@link ReelProps} forwarded to the underlying `Reel` component.
 *
 * Allows controlling transition duration, swipe sensitivity, looping,
 * keyboard navigation, and wheel behaviour without accessing `Reel` directly.
 */
export type ReelProxyProps = Pick<
  ReelProps,
  | 'transitionDuration'
  | 'swipeDistanceFactor'
  | 'loop'
  | 'enableNavKeys'
  | 'enableWheel'
  | 'wheelDebounceMs'
>;

/**
 * Props for the {@link LightboxOverlay} component.
 *
 * @example
 * ```tsx
 * // Basic usage
 * <LightboxOverlay
 *   isOpen={index !== null}
 *   images={images}
 *   initialIndex={index ?? 0}
 *   onClose={() => setIndex(null)}
 * />
 * ```
 *
 * @example
 * ```tsx
 * // With custom controls and info
 * <LightboxOverlay
 *   isOpen={isOpen}
 *   images={images}
 *   onClose={handleClose}
 *   renderControls={({ onClose, activeIndex, count }) => (
 *     <div>
 *       <Counter currentIndex={activeIndex} count={count} />
 *       <CloseButton onClick={onClose} />
 *     </div>
 *   )}
 *   renderInfo={({ item }) => <p>{item.title}</p>}
 * />
 * ```
 */
export interface LightboxOverlayBaseProps extends ReelProxyProps {
  /**
   * Accessible label for the dialog region. Announced by screen readers
   * when the lightbox opens.
   *
   * @default 'Image gallery'
   */
  ariaLabel?: string;

  /** Array of images to display as horizontal slides. */
  images: LightboxItem[];

  /**
   * Zero-based index of the initially visible image.
   * @default 0
   */
  initialIndex?: number;

  /**
   * Ref to access the Reel API
   */
  apiRef?: MutableRefObject<ReelApi | null>;

  /**
   * Slide transition function. Defaults to `slideTransition` from
   * `@reelkit/react`. Import additional built-ins from
   * `@reelkit/react-lightbox` (`lightboxFadeTransition`,
   * `lightboxZoomTransition`) or `@reelkit/react` (`flipTransition`).
   */
  transitionFn?: TransitionTransformFn;

  /**
   * Direction of the swipe-to-close gesture on mobile.
   *
   * @default 'up'
   */
  swipeToCloseDirection?: SwipeToCloseDirection;

  /**
   * Callback fired after slide change
   */
  onSlideChange?: (index: number) => void;

  /**
   * Custom controls. Replaces default close button, counter, and fullscreen toggle.
   */
  renderControls?: (props: ControlsRenderProps) => ReactNode;

  /**
   * Custom navigation arrows. Replaces default prev/next buttons.
   */
  renderNavigation?: (props: NavigationRenderProps) => ReactNode;

  /**
   * Custom info overlay. Replaces default title + description gradient.
   * Return `null` to hide the info overlay entirely.
   */
  renderInfo?: (props: InfoRenderProps) => ReactNode;

  /**
   * Custom slide rendering. Return null to fall back to default image slide.
   *
   * The optional `onReady` / `onWaiting` callbacks let the custom slide
   * report its loading state so the overlay can show/hide the spinner.
   */
  renderSlide?: (props: SlideRenderProps) => ReactNode | null;

  /** Custom loading indicator. Replaces default spinner. */
  renderLoading?: (props: {
    item: LightboxItem;
    activeIndex: number;
  }) => ReactNode;

  /** Custom error indicator. Replaces default error icon. */
  renderError?: (props: {
    item: LightboxItem;
    activeIndex: number;
  }) => ReactNode;
}

/**
 * Controlled mode: the surrounding component owns whether the lightbox is
 * open, and closes it from its own state.
 */
export interface LightboxControlledProps {
  /** When `true`, the lightbox is rendered and body scroll is locked. */
  isOpen: boolean;

  /** Callback to close the lightbox. Triggered by close button or Escape key. */
  onClose: () => void;
}

/**
 * URL-driven mode: the address bar owns whether the lightbox is open. A
 * {@link UrlStateController} — built in consumer code with `useOverlayUrlState`
 * — carries the open state, so the same controller can be read and driven from
 * elsewhere. The overlay opens itself when the controller's index names a slide
 * and closes when it clears.
 */
export interface LightboxUrlControlledProps {
  /**
   * URL-state controller from `useOverlayUrlState`. Its `index` drives whether
   * the overlay is open and which slide it shows; the overlay writes back
   * through it on slide change and close.
   */
  controller: UrlStateController;

  /** Called after the lightbox closes. The URL drives closing, not this. */
  onClose?: () => void;
}

/**
 * Props for the controlled {@link LightboxOverlay}. Open state is a boolean the
 * caller owns. For URL-driven open state, use {@link LightboxUrlOverlay}
 * instead — a separate component, so there is no mutually-exclusive prop to
 * police.
 */
export type LightboxOverlayProps = LightboxOverlayBaseProps &
  LightboxControlledProps;

/**
 * Props for {@link LightboxUrlOverlay}. Open state lives in the URL, carried by
 * a {@link UrlStateController} the consumer builds with `useOverlayUrlState`.
 */
export type LightboxUrlOverlayProps = LightboxOverlayBaseProps &
  LightboxUrlControlledProps;

/** Props the inner content actually consumes once the lightbox is open. */
type LightboxContentProps = LightboxOverlayBaseProps & { onClose: () => void };

/** Number of images to preload before and after the current index. */
const _kPreloadRange = 2;

const preloader = createContentPreloader({ maxCacheSize: 1000 });

/**
 * Inner content of the lightbox overlay. Manages slider, controls,
 * navigation, info overlay, fullscreen, resize, and image preloading.
 *
 * Rendered only while the lightbox is open — gated by {@link LightboxOverlay}
 * (`isOpen`) or {@link LightboxUrlOverlay} (a non-null `controller.index`).
 * @internal
 */
const LightboxContent: FC<LightboxContentProps> = (props) => {
  const {
    images,
    initialIndex = 0,
    onClose,
    transitionFn,
    apiRef,
    loop = false,
    enableNavKeys = true,
    enableWheel = true,
    wheelDebounceMs,
    transitionDuration,
    swipeDistanceFactor,
    swipeToCloseDirection = 'up',
  } = props;

  const propsRef = useRef(props);
  propsRef.current = props;

  const containerRef = useRef<HTMLDivElement>(null);
  const internalApiRef = useRef<ReelApi>(null);
  const sliderRef = apiRef ?? internalApiRef;

  const [
    {
      sizeSignal,
      loadingCtrl,
      indexSignal,
      isMobileSignal,
      handleAfterChange,
      handlePrev,
      handleNext,
      itemBuilder,
    },
  ] = useState(() => {
    const sizeSignal = createSignal<[number, number]>(
      typeof window !== 'undefined'
        ? [window.innerWidth, window.innerHeight]
        : [0, 0],
    );
    const loadingCtrl = createContentLoadingController(true, initialIndex);
    const indexSignal = createSignal(initialIndex);
    const isMobileSignal = createSignal(
      typeof window !== 'undefined'
        ? 'ontouchstart' in window || navigator.maxTouchPoints > 0
        : false,
    );

    const imageErrors = new Set<number>();
    const errorVersion = createSignal(0);

    return {
      sizeSignal,
      loadingCtrl,
      indexSignal,
      isMobileSignal,
      imageErrors,
      errorVersion,
      handleAfterChange: (index: number) => {
        loadingCtrl.setActiveIndex(index);
        const src = propsRef.current.images[index]?.src;
        if (src && preloader.isErrored(src)) {
          loadingCtrl.onError(index);
        } else if (src && preloader.isLoaded(src)) {
          loadingCtrl.onReady(index);
        }
        indexSignal.value = index;
        propsRef.current.onSlideChange?.(index);
      },
      handlePrev: () => {
        sliderRef.current?.prev();
      },
      handleNext: () => {
        sliderRef.current?.next();
      },
      itemBuilder: (
        index: number,
        _indexInRange: number,
        slideSize: [number, number],
      ) => {
        const { images: items, renderSlide } = propsRef.current;
        const image = items[index];
        const isActive = index === indexSignal.value;
        const onReady = () => loadingCtrl.onReady(index);
        const onWaiting = () => loadingCtrl.onWaiting(index);
        const onError = () => {
          preloader.markErrored(image.src);
          loadingCtrl.onError(index);
        };

        if (renderSlide) {
          const custom = renderSlide({
            item: image,
            index,
            size: slideSize,
            isActive,
            onReady,
            onWaiting,
            onError,
          });
          if (custom !== null) {
            return (
              <div
                className="rk-lightbox-slide"
                role="group"
                aria-roledescription="slide"
                aria-label={`Image ${index + 1} of ${items.length}`}
                style={{ width: slideSize[0], height: slideSize[1] }}
              >
                {custom}
              </div>
            );
          }
        }

        return (
          <div
            className="rk-lightbox-slide"
            role="group"
            aria-roledescription="slide"
            aria-label={`Image ${index + 1} of ${items.length}`}
            style={{ width: slideSize[0], height: slideSize[1] }}
          >
            <img
              src={image.src}
              alt={image.title || `Image ${index + 1}`}
              className="rk-lightbox-img"
              draggable={false}
              loading={isActive ? 'eager' : 'lazy'}
              ref={(node) => {
                // A cached image can finish decoding before React attaches the
                // handler below, so its load event never arrives and the slide
                // would sit under a spinner that has nothing left to wait for.
                // `naturalWidth` separates a decoded image from a broken one,
                // which reports complete just the same.
                if (node?.complete && node.naturalWidth > 0) {
                  preloader.markLoaded(image.src);
                  onReady();
                }
              }}
              onLoad={() => {
                preloader.markLoaded(image.src);
                onReady();
              }}
              onError={(e) => {
                (e.target as HTMLImageElement).style.display = 'none';
                onError();
              }}
            />
          </div>
        );
      },
    };
  });

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [isFullscreen, _, exitFullscreen, toggleFullscreen] = useFullscreen({
    ref: containerRef,
  });

  useBodyLock(true);

  useEffect(() => {
    const disposables = createDisposableList();

    disposables.push(captureFocusForReturn());
    const containerEl = containerRef.current;
    if (containerEl) {
      containerEl.focus({ preventScroll: true });
      disposables.push(createFocusTrap(containerEl));
    }

    disposables.push(
      observeDomEvent(window, 'resize', () => {
        sizeSignal.value = [window.innerWidth, window.innerHeight];
        isMobileSignal.value =
          'ontouchstart' in window || navigator.maxTouchPoints > 0;
      }),
      observeDomEvent(window, 'keydown', (e) => {
        if (e.key === 'Escape') {
          if (isFullscreen.value) {
            exitFullscreen();
          } else {
            propsRef.current.onClose();
          }
        }
      }),
      reaction(
        () => [indexSignal],
        () => {
          preloader.preloadRange(
            propsRef.current.images,
            indexSignal.value,
            _kPreloadRange,
          );
        },
      ),
    );

    preloader.preloadRange(
      propsRef.current.images,
      indexSignal.value,
      _kPreloadRange,
    );

    const initialIdx = indexSignal.value;
    const initialSrc = propsRef.current.images[initialIdx]?.src;
    if (initialSrc) {
      disposables.push(
        preloader.onLoaded(initialSrc, () => loadingCtrl.onReady(initialIdx)),
      );
    }

    return disposables.dispose;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return createPortal(
    <div
      ref={containerRef}
      className="rk-lightbox-overlay"
      role="dialog"
      aria-modal="true"
      aria-label={props.ariaLabel ?? 'Image gallery'}
      tabIndex={-1}
    >
      <Observe signals={[isFullscreen, indexSignal]}>
        {() => {
          const idx = indexSignal.value;
          const {
            renderControls: renderCtrl,
            onClose: close,
            images: items,
          } = propsRef.current;
          return (
            <>
              {renderCtrl ? (
                renderCtrl({
                  item: items[idx],
                  onClose: close,
                  activeIndex: idx,
                  count: items.length,
                  isFullscreen: isFullscreen.value,
                  onToggleFullscreen: toggleFullscreen,
                })
              ) : (
                <LightboxControls
                  onClose={close}
                  currentIndex={idx}
                  count={items.length}
                  isFullscreen={isFullscreen.value}
                  onToggleFullscreen={toggleFullscreen}
                />
              )}
            </>
          );
        }}
      </Observe>
      <Observe
        signals={[loadingCtrl.isLoading, loadingCtrl.isError, indexSignal]}
      >
        {() => {
          const idx = indexSignal.value;
          const { renderLoading, renderError, images } = propsRef.current;
          const currentItem = images[idx];

          if (loadingCtrl.isError.value) {
            return renderError ? (
              <>{renderError({ item: currentItem, activeIndex: idx })}</>
            ) : (
              <div
                className="rk-lightbox-img-error"
                role="img"
                aria-label="Content unavailable"
              >
                <ImageOff size={48} strokeWidth={1.5} aria-hidden="true" />
                <span className="rk-lightbox-img-error-text">
                  Content unavailable
                </span>
              </div>
            );
          }
          if (loadingCtrl.isLoading.value) {
            return renderLoading ? (
              <>{renderLoading({ item: currentItem, activeIndex: idx })}</>
            ) : (
              <div className="rk-lightbox-spinner" />
            );
          }
          return null;
        }}
      </Observe>
      <Observe signals={[sizeSignal, isMobileSignal]}>
        {() => (
          <SwipeToClose
            direction={swipeToCloseDirection}
            enabled={isMobileSignal.value}
            onClose={onClose}
          >
            <Reel
              count={images.length}
              size={sizeSignal.value}
              direction="horizontal"
              initialIndex={initialIndex}
              apiRef={sliderRef}
              afterChange={handleAfterChange}
              transition={transitionFn ?? slideTransition}
              transitionDuration={transitionDuration}
              swipeDistanceFactor={swipeDistanceFactor}
              loop={loop}
              enableNavKeys={enableNavKeys}
              enableWheel={enableWheel}
              wheelDebounceMs={wheelDebounceMs}
              itemBuilder={itemBuilder}
            />
          </SwipeToClose>
        )}
      </Observe>
      <Observe signals={[indexSignal, isMobileSignal]}>
        {() => {
          const idx = indexSignal.value;
          const mobile = isMobileSignal.value;
          const { renderNavigation, images: items } = propsRef.current;

          if (renderNavigation) {
            return (
              <>
                {renderNavigation({
                  item: items[idx],
                  onPrev: handlePrev,
                  onNext: handleNext,
                  activeIndex: idx,
                  count: items.length,
                })}
              </>
            );
          }
          if (mobile || items.length <= 1) return null;
          return (
            <>
              {idx > 0 && (
                <button
                  className="rk-lightbox-nav rk-lightbox-nav-prev"
                  onClick={handlePrev}
                  title="Previous"
                >
                  <ChevronLeft size={32} />
                </button>
              )}
              {idx < items.length - 1 && (
                <button
                  className="rk-lightbox-nav rk-lightbox-nav-next"
                  onClick={handleNext}
                  title="Next"
                >
                  <ChevronRight size={32} />
                </button>
              )}
            </>
          );
        }}
      </Observe>
      <Observe signals={[indexSignal]}>
        {() => {
          const idx = indexSignal.value;
          const { renderInfo, images: items } = propsRef.current;
          const currentImage = items[idx];

          if (renderInfo) {
            return <>{renderInfo({ item: currentImage, index: idx })}</>;
          }
          if (!currentImage?.title && !currentImage?.description) return null;
          return (
            <div className="rk-lightbox-info">
              {currentImage.title && (
                <h3 className="rk-lightbox-title">{currentImage.title}</h3>
              )}
              {currentImage.description && (
                <p className="rk-lightbox-description">
                  {currentImage.description}
                </p>
              )}
            </div>
          );
        }}
      </Observe>
      <Observe signals={[isMobileSignal]}>
        {() =>
          isMobileSignal.value ? (
            <div className="rk-lightbox-swipe-hint">Swipe up to close</div>
          ) : null
        }
      </Observe>
    </div>,
    document.body,
  );
};

/**
 * Full-screen image lightbox whose open state lives in the URL. Build the
 * controller with `useOverlayUrlState` and pass it as `controller`: the address
 * bar owns the gallery, so it opens when the controller's index names a slide,
 * closes when it clears — links are shareable and the back button closes when it
 * was opened from within the app. A shared link opened directly in a fresh tab
 * has no history behind it, so browser-back leaves the site; the close button or
 * Escape removes the parameter in place and stays.
 *
 * Prefer a link to the parameter (`<Link to="?photo=3">`) as the open action —
 * the href does it with no handler, and the open is then shareable, opens in a
 * new tab, and back-closes for free. `controller.set` to the parameter opens it
 * too; `set` is also the low-level write the overlay uses for slide changes and
 * to close.
 *
 * The controlled {@link LightboxOverlay} and this url-driven overlay are
 * separate components: each carries exactly one open-state driver, so there is
 * no mutually-exclusive prop to police.
 */
export const LightboxUrlOverlay = (
  props: LightboxUrlOverlayProps,
): ReactNode => {
  const { controller, onClose, ...base } = props;
  const latest = useRef({ base, onClose });
  latest.current = { base, onClose };

  return (
    <Observe signals={[controller.index]}>
      {() =>
        controller.index.value === null ? null : (
          <LightboxContent
            {...base}
            initialIndex={controller.index.value}
            onClose={() => {
              controller.set(null);
              latest.current.onClose?.();
            }}
            onSlideChange={(index) => {
              controller.set(index);
              latest.current.base.onSlideChange?.(index);
            }}
          />
        )
      }
    </Observe>
  );
};

/**
 * Full-screen image lightbox overlay with gesture, keyboard, and wheel
 * navigation. Controlled: the caller owns `isOpen`. For URL-driven open state,
 * use {@link LightboxUrlOverlay} instead.
 *
 * Renders into a portal on `document.body`. When `isOpen` is `false` the
 * component returns `null` — no DOM nodes are created.
 *
 * Customise controls, navigation, info overlay, and individual slides
 * via the `renderControls`, `renderNavigation`, `renderInfo`, and
 * `renderSlide` props. Reusable sub-components ({@link CloseButton},
 * {@link Counter}, {@link FullscreenButton}) are available for
 * composition inside `renderControls`.
 */
export const LightboxOverlay = (props: LightboxOverlayProps): ReactNode => {
  if (!props.isOpen) return null;

  return <LightboxContent {...props} />;
};

// packages/reelkit-angular-lightbox/src/lib/lightbox-overlay/lightbox-overlay.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  Injector,
  NgZone,
  ViewEncapsulation,
  afterNextRender,
  computed,
  contentChild,
  effect,
  inject,
  input,
  linkedSignal,
  output,
  signal,
  TemplateRef,
  untracked,
  viewChild,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  createContentLoadingController,
  createContentPreloader,
  slideTransition,
  fullscreenSignal,
  requestFullscreen,
  exitFullscreen,
  ReelComponent,
  RkReelItemDirective,
  SoundStateService,
  type ContentLoadingController,
  type ContentPreloader,
  type TransitionTransformFn,
  type ReelApi,
} from '@reelkit/angular';
import {
  LucideAngularModule,
  LucideIconProvider,
  LUCIDE_ICONS,
  ChevronLeft,
  ChevronRight,
} from 'lucide-angular';
import {
  BodyLockService,
  toAngularSignal,
  captureFocusForReturn,
  createFocusTrap,
  getFocusableElements,
  observeDomEvent,
} from '@reelkit/angular';
import {
  RkLightboxControlsDirective,
  RkLightboxNavigationDirective,
  RkLightboxInfoDirective,
  RkLightboxSlideDirective,
  RkLightboxLoadingDirective,
  RkLightboxErrorDirective,
  type LightboxLoadingContext,
  type LightboxErrorContext,
} from '../template-slots/lightbox-template-slots';
import {
  RkSwipeToCloseDirective,
  type SwipeToCloseDirection,
} from '@reelkit/angular';
import { RkCloseButtonComponent } from '../lightbox-controls/close-button.component';
import { RkCounterComponent } from '../lightbox-controls/counter.component';
import { RkFullscreenButtonComponent } from '../lightbox-controls/fullscreen-button.component';
import { RkSoundButtonComponent } from '../lightbox-controls/sound-button.component';
import type {
  LightboxItem,
  ReelProxyProps,
  LightboxControlsContext,
  LightboxNavContext,
  LightboxInfoContext,
  LightboxSlideContext,
} from '../types';

const _kPreloadRange = 2;
const _kDefaultTransitionDuration = 300;
const _kDefaultSwipeDistanceFactor = 0.12;
const _kDefaultWheelDebounceMs = 200;

const preloader: ContentPreloader = createContentPreloader({
  maxCacheSize: 1000,
});

const isTouchDevice = (): boolean =>
  typeof window !== 'undefined' &&
  ('ontouchstart' in window || navigator.maxTouchPoints > 0);

/**
 * Moves keyboard focus into `container`. Prefers the first naturally
 * focusable descendant; falls back to the container itself (which carries
 * `tabindex="-1"` in the template).
 */
const focusFirstFocusable = (container: HTMLElement): void => {
  const [first] = getFocusableElements(container);
  (first ?? container).focus();
};

/**
 * Full-screen image lightbox overlay with gesture, keyboard, and wheel navigation.
 *
 * Renders a portal-like fixed overlay using `position: fixed; z-index: 9999`.
 * When `isOpen` is `false`, the overlay is removed from the DOM via `@if`.
 *
 * Customise controls, navigation, info overlay, and individual slides via
 * template slots:
 * - `[rkLightboxControls]` — replace close/counter/fullscreen bar
 * - `[rkLightboxNavigation]` — replace prev/next arrows
 * - `[rkLightboxInfo]` — replace title/description gradient
 * - `[rkLightboxSlide]` — replace slide content (e.g. for video slides)
 *
 * @example
 * ```html
 * <rk-lightbox-overlay
 *   [isOpen]="index !== null"
 *   [items]="images"
 *   [initialIndex]="index ?? 0"
 *   (closed)="index = null"
 * />
 * ```
 */
@Component({
  selector: 'rk-lightbox-overlay',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { '(document:keydown)': 'onKeydown($event)' },
  providers: [
    {
      provide: LUCIDE_ICONS,
      useValue: new LucideIconProvider({ ChevronLeft, ChevronRight }),
      multi: true,
    },
  ],
  imports: [
    NgTemplateOutlet,
    LucideAngularModule,
    ReelComponent,
    RkReelItemDirective,
    RkSwipeToCloseDirective,
    RkCloseButtonComponent,
    RkCounterComponent,
    RkFullscreenButtonComponent,
    RkSoundButtonComponent,
  ],
  template: `
    @if (isOpen()) {
      <div
        #container
        class="rk-lightbox-overlay"
        role="dialog"
        aria-modal="true"
        [attr.aria-label]="ariaLabel()"
        tabindex="-1"
      >
        @if (items().length === 0) {
          <div class="rk-lightbox-empty" role="status" aria-live="polite">
            No items to display
          </div>
        }

        @if (items().length > 0 && showControls()) {
          <div class="rk-lightbox-top-shade"></div>
          @if (controlsTpl()) {
            <ng-container
              [ngTemplateOutlet]="controlsTpl()!"
              [ngTemplateOutletContext]="controlsContext()"
            />
          } @else {
            <div class="rk-lightbox-controls-left">
              <rk-counter
                [currentIndex]="currentIndex()"
                [count]="items().length"
              />
              <rk-fullscreen-button
                [isFullscreen]="isFullscreen()"
                (toggled)="handleToggleFullscreen()"
              />
              @if (
                isVideoSlide() && hasSharedSoundState && !soundState.disabled()
              ) {
                <rk-sound-button
                  [muted]="soundState.muted()"
                  (toggled)="soundState.toggle()"
                />
              }
            </div>
            <rk-close-button (clicked)="handleClose()" />
          }
        }

        @if (isError()) {
          @if (errorTpl()) {
            <ng-container
              [ngTemplateOutlet]="errorTpl()!"
              [ngTemplateOutletContext]="{
                $implicit: currentIndex(),
                item: currentItem(),
              }"
            />
          } @else {
            <div
              class="rk-lightbox-img-error"
              role="img"
              aria-label="Content unavailable"
            >
              <svg
                width="48"
                height="48"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                <circle cx="8.5" cy="8.5" r="1.5" />
                <polyline points="21 15 16 10 5 21" />
                <line x1="4" y1="4" x2="20" y2="20" />
              </svg>
              <span class="rk-lightbox-img-error-text"
                >Content unavailable</span
              >
            </div>
          }
        } @else if (isLoading()) {
          @if (loadingTpl()) {
            <ng-container
              [ngTemplateOutlet]="loadingTpl()!"
              [ngTemplateOutletContext]="{
                $implicit: currentIndex(),
                item: currentItem(),
              }"
            />
          } @else {
            <div class="rk-lightbox-spinner"></div>
          }
        }

        @if (items().length > 0) {
          <div
            [rkSwipeToClose]="isMobile()"
            [rkSwipeToCloseDirection]="swipeToCloseDirection()"
            (dismissed)="handleClose()"
          >
            <rk-reel
              [count]="items().length"
              [size]="size()"
              direction="horizontal"
              [initialIndex]="safeInitialIndex()"
              [loop]="loop() ?? false"
              [enableNavKeys]="enableNavKeys() ?? true"
              [enableWheel]="enableWheel() ?? true"
              [wheelDebounceMs]="wheelDebounceMs() ?? 200"
              [transitionDuration]="transitionDuration() ?? 300"
              [swipeDistanceFactor]="swipeDistanceFactor() ?? 0.12"
              [transition]="resolvedTransitionFn()"
              (apiReady)="onApiReady($event)"
              (afterChange)="onAfterChange($event)"
            >
              <ng-template rkReelItem let-idx let-itemSize="size">
                @let item = items()[idx];
                @if (item) {
                  <div
                    class="rk-lightbox-slide"
                    [style.width.px]="itemSize[0]"
                    [style.height.px]="itemSize[1]"
                    role="group"
                    aria-roledescription="slide"
                    [attr.aria-label]="slideAriaLabel(idx)"
                  >
                    @if (slideTpl()) {
                      <ng-container
                        [ngTemplateOutlet]="slideTpl()!"
                        [ngTemplateOutletContext]="slideContext(idx)"
                      />
                    } @else if (!imageErrorIndexes().has(idx)) {
                      <img
                        [src]="item.src"
                        [alt]="item.title || 'Image ' + (idx + 1)"
                        class="rk-lightbox-img"
                        [class.rk-loaded]="imageLoadedIndexes().has(idx)"
                        draggable="false"
                        loading="lazy"
                        (load)="onImageLoad(idx)"
                        (error)="onImageError(idx)"
                      />
                    }
                  </div>
                }
              </ng-template>
            </rk-reel>
          </div>

          @if (showNavigation()) {
            @if (navigationTpl()) {
              <ng-container
                [ngTemplateOutlet]="navigationTpl()!"
                [ngTemplateOutletContext]="navContext()"
              />
            } @else if (!isMobile() && items().length > 1) {
              @if (currentIndex() > 0) {
                <button
                  class="rk-lightbox-nav rk-lightbox-nav-prev"
                  (click)="handlePrev()"
                  title="Previous"
                  aria-label="Previous"
                  type="button"
                >
                  <lucide-angular [img]="ChevronLeftIcon" [size]="32" />
                </button>
              }
              @if (currentIndex() < items().length - 1) {
                <button
                  class="rk-lightbox-nav rk-lightbox-nav-next"
                  (click)="handleNext()"
                  title="Next"
                  aria-label="Next"
                  type="button"
                >
                  <lucide-angular [img]="ChevronRightIcon" [size]="32" />
                </button>
              }
            }
          }

          @if (showInfo()) {
            @if (infoTpl()) {
              <ng-container
                [ngTemplateOutlet]="infoTpl()!"
                [ngTemplateOutletContext]="infoContext()"
              />
            } @else if (currentItem().title || currentItem().description) {
              <div class="rk-lightbox-info">
                @if (currentItem().title) {
                  <h3 class="rk-lightbox-title">{{ currentItem().title }}</h3>
                }
                @if (currentItem().description) {
                  <p class="rk-lightbox-description">
                    {{ currentItem().description }}
                  </p>
                }
              </div>
            }
          }

          @if (isMobile()) {
            <div class="rk-lightbox-swipe-hint">Swipe up to close</div>
          }
        }
      </div>
    }
  `,
})
export class RkLightboxOverlayComponent {
  private readonly _bodyLock = inject(BodyLockService);
  private readonly _ngZone = inject(NgZone);
  private readonly _destroyRef = inject(DestroyRef);
  private readonly _injector = inject(Injector);

  protected readonly loadingCtrl: ContentLoadingController =
    createContentLoadingController(true, 0);

  protected readonly isLoading = toAngularSignal(
    this.loadingCtrl.isLoading,
    this._destroyRef,
  );

  protected readonly isError = toAngularSignal(
    this.loadingCtrl.isError,
    this._destroyRef,
  );

  protected readonly isFullscreen = toAngularSignal(
    fullscreenSignal,
    this._destroyRef,
  );

  /**
   * Sound state the consumer provided above this overlay, if any. A video
   * slide is rendered from the consumer's own `rkLightboxSlide` template, so
   * its injector is theirs, not this component's — an instance provided here
   * would be invisible to the slide, and the button would move nothing. One
   * provided above both is what lets the two meet.
   */
  private readonly _providedSoundState = inject(SoundStateService, {
    optional: true,
  });

  protected readonly soundState =
    this._providedSoundState ?? new SoundStateService();

  /** Whether a toggle can reach the video, and so whether to offer one. */
  protected readonly hasSharedSoundState = this._providedSoundState !== null;

  protected readonly controlsSlot = contentChild(RkLightboxControlsDirective);
  protected readonly navigationSlot = contentChild(
    RkLightboxNavigationDirective,
  );
  protected readonly infoSlot = contentChild(RkLightboxInfoDirective);
  protected readonly slideSlot = contentChild(RkLightboxSlideDirective);
  protected readonly loadingSlot = contentChild(RkLightboxLoadingDirective);
  protected readonly errorSlot = contentChild(RkLightboxErrorDirective);

  /**
   * Slot templates supplied as values rather than projected content.
   *
   * `<rk-lightbox-url-overlay>` wraps this component, so a consumer's
   * `<ng-template rkLightboxControls>` is its content, not ours — and a
   * `contentChild` query does not reach across a wrapper's `<ng-content>`.
   * The wrapper therefore runs the queries itself and hands each `TemplateRef`
   * down here.
   *
   * Unset for ordinary controlled usage, where the query below still answers.
   */
  readonly controlsTemplate = input<TemplateRef<LightboxControlsContext>>();
  readonly navigationTemplate = input<TemplateRef<LightboxNavContext>>();
  readonly infoTemplate = input<TemplateRef<LightboxInfoContext>>();
  readonly slideTemplate = input<TemplateRef<LightboxSlideContext>>();
  readonly loadingTemplate = input<TemplateRef<LightboxLoadingContext>>();
  readonly errorTemplate = input<TemplateRef<LightboxErrorContext>>();

  // Forwarded value wins; the projected query is the fallback.
  protected readonly controlsTpl = computed(
    () => this.controlsTemplate() ?? this.controlsSlot()?.templateRef,
  );
  protected readonly navigationTpl = computed(
    () => this.navigationTemplate() ?? this.navigationSlot()?.templateRef,
  );
  protected readonly infoTpl = computed(
    () => this.infoTemplate() ?? this.infoSlot()?.templateRef,
  );
  protected readonly slideTpl = computed(
    () => this.slideTemplate() ?? this.slideSlot()?.templateRef,
  );
  protected readonly loadingTpl = computed(
    () => this.loadingTemplate() ?? this.loadingSlot()?.templateRef,
  );
  protected readonly errorTpl = computed(
    () => this.errorTemplate() ?? this.errorSlot()?.templateRef,
  );

  private readonly _containerRef =
    viewChild<ElementRef<HTMLDivElement>>('container');

  /** When `true`, the lightbox is rendered and body scroll is locked. */
  readonly isOpen = input.required<boolean>();

  readonly items = input.required<LightboxItem[]>();

  /** Zero-based index of the initially visible item. @default 0 */
  readonly initialIndex = input<number>(0);

  /**
   * Slide transition function. Defaults to `slideTransition` from
   * `@reelkit/angular`. Import additional built-ins from
   * `@reelkit/angular-lightbox` (`lightboxFadeTransition`,
   * `lightboxZoomTransition`) or `@reelkit/angular` (`flipTransition`).
   */
  readonly transitionFn = input<TransitionTransformFn | undefined>(undefined);

  readonly showInfo = input<boolean>(true);

  readonly showControls = input<boolean>(true);

  readonly showNavigation = input<boolean>(true);

  /** Duration of slide transition animations in ms. @default 300 */
  readonly transitionDuration = input<ReelProxyProps['transitionDuration']>(
    _kDefaultTransitionDuration,
  );

  /** Minimum swipe distance fraction to trigger a slide change. @default 0.12 */
  readonly swipeDistanceFactor = input<ReelProxyProps['swipeDistanceFactor']>(
    _kDefaultSwipeDistanceFactor,
  );

  /** Whether the slider wraps from last slide back to first. @default false */
  readonly loop = input<ReelProxyProps['loop']>(false);

  /** Enable keyboard arrow key navigation. @default true */
  readonly enableNavKeys = input<ReelProxyProps['enableNavKeys']>(true);

  /** Enable mouse wheel navigation. @default true */
  readonly enableWheel = input<ReelProxyProps['enableWheel']>(true);

  /** Debounce duration for wheel events in ms. @default 200 */
  readonly wheelDebounceMs = input<ReelProxyProps['wheelDebounceMs']>(
    _kDefaultWheelDebounceMs,
  );

  /** Direction of the swipe-to-close gesture on mobile. @default 'up' */
  readonly swipeToCloseDirection = input<SwipeToCloseDirection>('up');

  /**
   * Accessible label for the dialog, announced by screen readers when the
   * overlay opens. Override when the gallery has a more specific name.
   * @default 'Image gallery'
   */
  readonly ariaLabel = input<string>('Image gallery');

  readonly closed = output<void>();

  readonly slideChange = output<number>();

  /**
   * `initialIndex` clamped to `[0, items.length - 1]`.
   * Guards against callers passing an out-of-bounds value (e.g. when the
   * items array shrinks between renders).
   */
  protected readonly safeInitialIndex = computed(() => {
    const idx = this.initialIndex();
    const len = this.items().length;
    if (len === 0) return 0;
    return Math.max(0, Math.min(idx, len - 1));
  });

  /**
   * Zero-based index of the currently visible slide.
   * Automatically resets to `safeInitialIndex` whenever the lightbox opens so
   * that re-opening always starts at the requested position.
   * Can still be updated imperatively by the slider's `onAfterChange` callback.
   */
  protected readonly currentIndex = linkedSignal(() =>
    this.isOpen() ? this.safeInitialIndex() : 0,
  );

  protected readonly size = signal<[number, number]>(
    typeof window !== 'undefined'
      ? [window.innerWidth, window.innerHeight]
      : [0, 0],
  );

  protected readonly isMobile = signal(isTouchDevice());

  protected readonly currentItem = computed(
    () => this.items()[this.currentIndex()],
  );

  /**
   * Set of slide indices whose images have completed loading.
   * Drives the shimmer-to-image crossfade in the template.
   * Cleared whenever the overlay closes so state is fresh on re-open.
   */
  protected readonly imageLoadedIndexes = signal<Set<number>>(new Set());

  /**
   * Set of slide indices whose images have failed to load.
   * Drives the broken-image fallback state in the template.
   * Cleared whenever the overlay closes so state is fresh on re-open.
   */
  protected readonly imageErrorIndexes = signal<Set<number>>(new Set());

  protected readonly isVideoSlide = computed(() => {
    const item = this.currentItem();
    return item?.type === 'video';
  });

  protected readonly resolvedTransitionFn = computed<TransitionTransformFn>(
    () => this.transitionFn() ?? slideTransition,
  );

  protected readonly ChevronLeftIcon = ChevronLeft;
  protected readonly ChevronRightIcon = ChevronRight;

  private _reelApi: ReelApi | null = null;
  private _preloaderDispose: (() => void) | null = null;
  private _restoreFocus: (() => void) | null = null;
  private _releaseFocusTrap: (() => void) | null = null;
  private _stopObservingResize: (() => void) | null = null;

  constructor() {
    if (typeof window !== 'undefined') {
      this._ngZone.runOutsideAngular(() => {
        this._stopObservingResize = observeDomEvent(
          window,
          'resize',
          this._handleResize,
        );
      });
    }
    this._destroyRef.onDestroy(() => {
      this._stopObservingResize?.();
      this._bodyLock.unlock();
    });

    effect(() => {
      if (this.isOpen()) {
        this.onOverlayOpened();
      } else {
        this.onOverlayClosed();
      }
    });

    effect(() => {
      this.preloadAdjacentSlides(this.currentIndex(), this.items());
    });
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (!this.isOpen()) return;

    if (event.key === 'Escape') {
      this.handleClose();
    }
  }

  /**
   * Closes the lightbox. If the browser is currently in fullscreen mode,
   * fullscreen is exited first so the page is never left in a fullscreen
   * state after the overlay is dismissed (whether via close button, swipe,
   * Escape key, or a custom controls slot).
   */
  protected handleClose(): void {
    if (fullscreenSignal.value) {
      exitFullscreen();
    }
    this.soundState.controller.muted.value = true;
    this.closed.emit();
  }

  protected onImageLoad(index: number): void {
    const src = this.items()[index]?.src;
    if (src) preloader.markLoaded(src);
    this.loadingCtrl.onReady(index);
    this.imageLoadedIndexes.update((prev) => {
      const next = new Set(prev);
      next.add(index);
      return next;
    });
  }

  protected onImageError(index: number): void {
    const src = this.items()[index]?.src;
    if (src) preloader.markErrored(src);
    this.loadingCtrl.onError(index);
    this.imageErrorIndexes.update((prev) => {
      const next = new Set(prev);
      next.add(index);
      return next;
    });
  }

  protected handlePrev(): void {
    this._reelApi?.prev();
  }

  protected handleNext(): void {
    this._reelApi?.next();
  }

  protected onApiReady(api: ReelApi): void {
    this._reelApi = api;
  }

  protected onAfterChange(event: { index: number }): void {
    const index = event.index;
    this.loadingCtrl.setActiveIndex(index);
    const src = this.items()[index]?.src;
    if (src && preloader.isErrored(src)) {
      this.loadingCtrl.onError(index);
    } else if (src && preloader.isLoaded(src)) {
      this.loadingCtrl.onReady(index);
    }
    this.currentIndex.set(index);
    this.slideChange.emit(index);
  }

  protected handleToggleFullscreen(): void {
    if (fullscreenSignal.value) {
      exitFullscreen();
    } else {
      const container = this._containerRef();
      if (container) {
        requestFullscreen(container.nativeElement);
      }
    }
  }

  /**
   * Template outlet context for the `rkLightboxControls` slot.
   * Recomputed only when `currentIndex`, `items`, or `isFullscreen` changes —
   * not on every change-detection cycle as a plain method would be.
   */
  protected readonly controlsContext = computed<LightboxControlsContext>(
    () => ({
      $implicit: undefined as void,
      item: this.currentItem(),
      activeIndex: this.currentIndex(),
      count: this.items().length,
      isFullscreen: this.isFullscreen(),
      onClose: () => this.handleClose(),
      onToggleFullscreen: () => this.handleToggleFullscreen(),
    }),
  );

  protected readonly navContext = computed<LightboxNavContext>(() => ({
    $implicit: undefined as void,
    item: this.currentItem(),
    activeIndex: this.currentIndex(),
    count: this.items().length,
    onPrev: () => this.handlePrev(),
    onNext: () => this.handleNext(),
  }));

  /**
   * Template outlet context for the `rkLightboxInfo` slot.
   * Recomputed only when the current item or index changes.
   */
  protected readonly infoContext = computed<LightboxInfoContext>(() => ({
    $implicit: this.currentItem() ?? ({} as LightboxItem),
    index: this.currentIndex(),
  }));

  /**
   * Slide context for the `rkLightboxSlide` slot. Takes an index parameter
   * so it cannot be a parameterless `computed()`. Reads pre-computed signals
   * (`size`, `currentIndex`) to keep per-call work minimal.
   */
  protected slideContext(index: number): LightboxSlideContext {
    return {
      $implicit: this.items()[index] as LightboxItem,
      index,
      size: this.size(),
      isActive: index === this.currentIndex(),
      onReady: () => {
        this.loadingCtrl.onReady(index);
        const src = this.items()[index]?.src;
        if (src) preloader.markLoaded(src);
      },
      onWaiting: () => this.loadingCtrl.onWaiting(index),
      onError: () => {
        const src = this.items()[index]?.src;
        if (src) preloader.markErrored(src);
        this.loadingCtrl.onError(index);
      },
    };
  }

  /**
   * Returns the accessible label for a slide: uses the item's title if
   * present, otherwise falls back to "Image X of Y".
   */
  protected slideAriaLabel(index: number): string {
    const item = this.items()[index];
    const position = `${index + 1} of ${this.items().length}`;
    return item?.title ? `${item.title}, ${position}` : `Image ${position}`;
  }

  private readonly _handleResize = (): void => {
    this._ngZone.run(() => {
      this.size.set([window.innerWidth, window.innerHeight]);
      this.isMobile.set(isTouchDevice());
      this._reelApi?.adjust();
    });
  };

  private onOverlayOpened(): void {
    this._bodyLock.lock();
    this._restoreFocus = captureFocusForReturn();

    const initialIdx = this.safeInitialIndex();
    this.loadingCtrl.setActiveIndex(initialIdx);

    const initialSrc = this.items()[initialIdx]?.src;
    if (initialSrc && preloader.isErrored(initialSrc)) {
      this.loadingCtrl.onError(initialIdx);
    } else if (initialSrc && preloader.isLoaded(initialSrc)) {
      this.loadingCtrl.onReady(initialIdx);
    } else if (initialSrc) {
      this._preloaderDispose = preloader.onLoaded(initialSrc, () =>
        this.loadingCtrl.onReady(initialIdx),
      );
    }

    afterNextRender(
      () => {
        const container = untracked(() => this._containerRef())?.nativeElement;
        if (container) {
          focusFirstFocusable(container);
          this._releaseFocusTrap = createFocusTrap(container);
        }
      },
      { injector: this._injector },
    );
  }

  private onOverlayClosed(): void {
    this._bodyLock.unlock();
    this._reelApi = null;
    this.imageLoadedIndexes.set(new Set());
    this.imageErrorIndexes.set(new Set());
    this.soundState.controller.muted.value = true;
    if (this._preloaderDispose) {
      this._preloaderDispose();
      this._preloaderDispose = null;
    }
    if (fullscreenSignal.value) {
      exitFullscreen();
    }
    this._releaseFocusTrap?.();
    this._releaseFocusTrap = null;
    this._restoreFocus?.();
    this._restoreFocus = null;
  }

  private preloadAdjacentSlides(
    idx: number,
    items: readonly LightboxItem[],
  ): void {
    if (!this.isOpen()) return;
    preloader.preloadRange(items, idx, _kPreloadRange);
  }
}
