// apps/example-react/src/app/pages/FullPageSlider.tsx
import React from 'react';
import { Reel, ReelIndicator, useBodyLock, type ReelApi } from '@reelkit/react';

const TOTAL_SLIDES = 10000;
const SIZE_MODE_KEY = 'reelkit-fullpage-size-mode';

// Generate color from index using HSL for nice variety
const getSlideColor = (index: number): string => {
  const hue = (index * 37) % 360; // Golden angle for good distribution
  return `hsl(${hue}, 70%, 65%)`;
};

// Generate slide content from index
const getSlideContent = (index: number) => ({
  title: `Slide ${index + 1}`,
  description:
    index === 0
      ? 'Swipe up or down to navigate'
      : `Item #${index + 1} of ${TOTAL_SLIDES.toLocaleString()}`,
});

type SizeMode = 'explicit' | 'auto';
type IndicatorMode = 'auto' | 'controlled';

const INDICATOR_MODE_KEY = 'reelkit-fullpage-indicator-mode';

function FullPageSlider() {
  const [activeIndex, setActiveIndex] = React.useState(0);
  const sliderRef = React.useRef<ReelApi>(null);
  const [sizeMode, setSizeMode] = React.useState<SizeMode>(
    () => (localStorage.getItem(SIZE_MODE_KEY) as SizeMode) || 'explicit',
  );
  const [indicatorMode, setIndicatorMode] = React.useState<IndicatorMode>(
    () => (localStorage.getItem(INDICATOR_MODE_KEY) as IndicatorMode) || 'auto',
  );
  const [size, setSize] = React.useState<[number, number]>([
    window.innerWidth,
    window.innerHeight,
  ]);
  const [goToValue, setGoToValue] = React.useState('');

  // Lock body scroll to prevent browser chrome movement on mobile
  useBodyLock(true);

  const toggleSizeMode = () => {
    const next = sizeMode === 'explicit' ? 'auto' : 'explicit';
    localStorage.setItem(SIZE_MODE_KEY, next);
    setSizeMode(next);
  };

  const toggleIndicatorMode = () => {
    const next = indicatorMode === 'auto' ? 'controlled' : 'auto';
    localStorage.setItem(INDICATOR_MODE_KEY, next);
    setIndicatorMode(next);
  };

  React.useEffect(() => {
    if (sizeMode !== 'explicit') return;

    const handleResize = () => {
      setSize([window.innerWidth, window.innerHeight]);
      sliderRef.current?.adjust();
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [sizeMode]);

  return (
    <div style={{ width: '100%', height: '100dvh', overflow: 'hidden' }}>
      <Reel
        count={TOTAL_SLIDES}
        {...(sizeMode === 'explicit' ? { size } : {})}
        direction="vertical"
        loop={false}
        useNavKeys={true}
        enableWheel={true}
        apiRef={sliderRef}
        afterChange={(index) => setActiveIndex(index)}
        style={
          sizeMode === 'auto' ? { width: '100%', height: '100%' } : undefined
        }
        itemBuilder={(index, _indexInRange, itemSize) => {
          const slide = getSlideContent(index);
          return (
            <div
              style={{
                width: itemSize[0],
                height: itemSize[1],
                backgroundColor: getSlideColor(index),
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                color: '#000',
              }}
            >
              <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>
                {slide.title}
              </h1>
              <p style={{ fontSize: '1.5rem', opacity: 0.7 }}>
                {slide.description}
              </p>
            </div>
          );
        }}
      >
        {/* Current position indicator */}
        <div
          style={{
            position: 'absolute',
            top: 48,
            left: '50%',
            transform: 'translateX(-50%)',
            padding: '6px 14px',
            backgroundColor: 'rgba(0,0,0,0.5)',
            color: '#fff',
            borderRadius: 20,
            fontSize: '0.8rem',
            zIndex: 10,
            backdropFilter: 'blur(8px)',
            WebkitBackdropFilter: 'blur(8px)',
          }}
        >
          {(activeIndex + 1).toLocaleString()} / {TOTAL_SLIDES.toLocaleString()}
        </div>

        {/* Size mode toggle */}
        <button
          onClick={toggleSizeMode}
          style={{
            position: 'absolute',
            top: 48,
            right: 40,
            padding: '6px 12px',
            backgroundColor: 'rgba(0,0,0,0.5)',
            color: '#fff',
            border: 'none',
            borderRadius: 20,
            fontSize: '0.75rem',
            cursor: 'pointer',
            zIndex: 10,
            backdropFilter: 'blur(8px)',
            WebkitBackdropFilter: 'blur(8px)',
          }}
        >
          size: {sizeMode === 'explicit' ? `[${size[0]}, ${size[1]}]` : 'auto'}
        </button>

        {/* Indicator mode toggle */}
        <button
          onClick={toggleIndicatorMode}
          data-testid="indicator-mode-toggle"
          style={{
            position: 'absolute',
            top: 48,
            right: 40,
            marginTop: 36,
            padding: '6px 12px',
            backgroundColor: 'rgba(0,0,0,0.5)',
            color: '#fff',
            border: 'none',
            borderRadius: 20,
            fontSize: '0.75rem',
            cursor: 'pointer',
            zIndex: 10,
            backdropFilter: 'blur(8px)',
            WebkitBackdropFilter: 'blur(8px)',
          }}
        >
          indicator: {indicatorMode}
        </button>

        {/* Bottom controls */}
        <div
          style={{
            position: 'absolute',
            bottom: 24,
            left: '50%',
            transform: 'translateX(-50%)',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 10,
            zIndex: 10,
          }}
        >
          {/* Go to index control */}
          <div style={{ display: 'flex', gap: 8 }}>
            <input
              type="number"
              min={1}
              max={TOTAL_SLIDES}
              value={goToValue}
              onChange={(e) => setGoToValue(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  const index = parseInt(goToValue, 10) - 1;
                  if (index >= 0 && index < TOTAL_SLIDES) {
                    sliderRef.current?.goTo(index, true);
                  }
                  (e.target as HTMLInputElement).blur();
                }
              }}
              onBlur={() => {
                window.scrollTo(0, 0);
                sliderRef.current?.adjust();
              }}
              placeholder="Slide #"
              style={{
                padding: '10px 14px',
                fontSize: '0.9rem',
                backgroundColor: 'rgba(0,0,0,0.5)',
                color: '#fff',
                border: 'none',
                borderRadius: 8,
                width: 90,
                outline: 'none',
                backdropFilter: 'blur(8px)',
                WebkitBackdropFilter: 'blur(8px)',
              }}
            />
            <button
              onClick={() => {
                const index = parseInt(goToValue, 10) - 1;
                if (index >= 0 && index < TOTAL_SLIDES) {
                  sliderRef.current?.goTo(index, true);
                }
              }}
              style={{
                padding: '10px 20px',
                fontSize: '0.9rem',
                backgroundColor: 'rgba(0,0,0,0.6)',
                color: '#fff',
                border: 'none',
                borderRadius: 8,
                cursor: 'pointer',
                backdropFilter: 'blur(8px)',
                WebkitBackdropFilter: 'blur(8px)',
              }}
            >
              Go
            </button>
          </div>

          {/* Navigation buttons */}
          <div style={{ display: 'flex', gap: 10 }}>
            <button
              onClick={() => sliderRef.current?.prev()}
              style={{
                padding: '10px 20px',
                fontSize: '0.9rem',
                backgroundColor: 'rgba(0,0,0,0.5)',
                color: '#fff',
                border: 'none',
                borderRadius: 8,
                cursor: 'pointer',
                backdropFilter: 'blur(8px)',
                WebkitBackdropFilter: 'blur(8px)',
              }}
            >
              ↑ Previous
            </button>
            <button
              onClick={() => sliderRef.current?.next()}
              style={{
                padding: '10px 20px',
                fontSize: '0.9rem',
                backgroundColor: 'rgba(0,0,0,0.5)',
                color: '#fff',
                border: 'none',
                borderRadius: 8,
                cursor: 'pointer',
                backdropFilter: 'blur(8px)',
                WebkitBackdropFilter: 'blur(8px)',
              }}
            >
              Next ↓
            </button>
          </div>
        </div>

        {/* Indicator */}
        <div
          style={{
            position: 'absolute',
            right: 12,
            top: '50%',
            transform: 'translateY(-50%)',
            zIndex: 10,
          }}
        >
          <ReelIndicator
            direction="vertical"
            visible={4}
            radius={4}
            gap={6}
            onDotClick={(index) => sliderRef.current?.goTo(index, true)}
            {...(indicatorMode === 'controlled'
              ? { count: TOTAL_SLIDES, active: activeIndex }
              : {})}
          />
        </div>
      </Reel>
    </div>
  );
}

export default FullPageSlider;

// apps/example-angular/src/app/pages/full-page-slider/full-page-slider.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  signal,
  computed,
  OnInit,
  OnDestroy,
  inject,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  ReelComponent,
  ReelIndicatorComponent,
  RkReelItemDirective,
  BodyLockService,
  type ReelApi,
} from '@reelkit/angular';

const TOTAL_SLIDES = 10000;
const SIZE_MODE_KEY = 'reelkit-fullpage-size-mode';
const INDICATOR_MODE_KEY = 'reelkit-fullpage-indicator-mode';

type SizeMode = 'explicit' | 'auto';
type IndicatorMode = 'auto' | 'controlled';

const getSlideColor = (index: number): string => {
  const hue = (index * 37) % 360;
  return `hsl(${hue}, 70%, 65%)`;
};

const getSlideContent = (
  index: number,
): { title: string; description: string } => ({
  title: `Slide ${index + 1}`,
  description:
    index === 0
      ? 'Swipe up or down to navigate'
      : `Item #${index + 1} of ${TOTAL_SLIDES.toLocaleString()}`,
});

@Component({
  selector: 'app-full-page-slider',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReelComponent,
    ReelIndicatorComponent,
    RkReelItemDirective,
    FormsModule,
  ],
  template: `
    <div style="width: 100%; height: 100dvh; overflow: hidden;">
      <rk-reel
        [count]="totalSlides"
        [size]="sizeMode() === 'explicit' ? explicitSize() : undefined"
        direction="vertical"
        [loop]="false"
        [useNavKeys]="true"
        [enableWheel]="true"
        (apiReady)="onApiReady($event)"
        (afterChange)="onAfterChange($event)"
        [style.width]="sizeMode() === 'auto' ? '100%' : null"
        [style.height]="sizeMode() === 'auto' ? '100%' : null"
      >
        <ng-template rkReelItem let-index let-size="size">
          <div
            [style.width.px]="size[0]"
            [style.height.px]="size[1]"
            [style.background-color]="getSlideColor(index)"
            style="display: flex; flex-direction: column; justify-content: center; align-items: center; color: #000;"
          >
            <h1 style="font-size: 3rem; margin-bottom: 1rem;">
              {{ getSlideContent(index).title }}
            </h1>
            <p style="font-size: 1.5rem; opacity: 0.7;">
              {{ getSlideContent(index).description }}
            </p>
          </div>
        </ng-template>

        <div
          style="
            position: absolute;
            top: 48px;
            left: 50%;
            transform: translateX(-50%);
            padding: 6px 14px;
            background-color: rgba(0,0,0,0.5);
            color: #fff;
            border-radius: 20px;
            font-size: 0.8rem;
            z-index: 10;
            backdrop-filter: blur(8px);
            -webkit-backdrop-filter: blur(8px);
          "
        >
          {{ (activeIndex() + 1).toLocaleString() }} /
          {{ totalSlides.toLocaleString() }}
        </div>

        <button
          (click)="toggleSizeMode()"
          style="
            position: absolute;
            top: 48px;
            right: 40px;
            padding: 6px 12px;
            background-color: rgba(0,0,0,0.5);
            color: #fff;
            border: none;
            border-radius: 20px;
            font-size: 0.75rem;
            cursor: pointer;
            z-index: 10;
            backdrop-filter: blur(8px);
            -webkit-backdrop-filter: blur(8px);
          "
        >
          size:
          {{
            sizeMode() === 'explicit'
              ? '[' + explicitSize()[0] + ', ' + explicitSize()[1] + ']'
              : 'auto'
          }}
        </button>

        <button
          (click)="toggleIndicatorMode()"
          data-testid="indicator-mode-toggle"
          style="
            position: absolute;
            top: 84px;
            right: 40px;
            padding: 6px 12px;
            background-color: rgba(0,0,0,0.5);
            color: #fff;
            border: none;
            border-radius: 20px;
            font-size: 0.75rem;
            cursor: pointer;
            z-index: 10;
            backdrop-filter: blur(8px);
            -webkit-backdrop-filter: blur(8px);
          "
        >
          indicator: {{ indicatorMode() }}
        </button>

        <div
          style="
            position: absolute;
            bottom: 24px;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 10px;
            z-index: 10;
          "
        >
          <div style="display: flex; gap: 8px;">
            <input
              type="number"
              [min]="1"
              [max]="totalSlides"
              [(ngModel)]="goToValue"
              (keydown.enter)="goToSlide(); $event.target.blur()"
              (blur)="onInputBlur()"
              placeholder="Slide #"
              style="
                padding: 10px 14px;
                font-size: 0.9rem;
                background-color: rgba(0,0,0,0.5);
                color: #fff;
                border: none;
                border-radius: 8px;
                width: 90px;
                outline: none;
                backdrop-filter: blur(8px);
                -webkit-backdrop-filter: blur(8px);
              "
            />
            <button
              (click)="goToSlide()"
              style="
                padding: 10px 20px;
                font-size: 0.9rem;
                background-color: rgba(0,0,0,0.6);
                color: #fff;
                border: none;
                border-radius: 8px;
                cursor: pointer;
                backdrop-filter: blur(8px);
                -webkit-backdrop-filter: blur(8px);
              "
            >
              Go
            </button>
          </div>

          <div style="display: flex; gap: 10px;">
            <button
              (click)="reelApi?.prev()"
              style="
                padding: 10px 20px;
                font-size: 0.9rem;
                background-color: rgba(0,0,0,0.5);
                color: #fff;
                border: none;
                border-radius: 8px;
                cursor: pointer;
                backdrop-filter: blur(8px);
                -webkit-backdrop-filter: blur(8px);
              "
            >
              ↑ Previous
            </button>
            <button
              (click)="reelApi?.next()"
              style="
                padding: 10px 20px;
                font-size: 0.9rem;
                background-color: rgba(0,0,0,0.5);
                color: #fff;
                border: none;
                border-radius: 8px;
                cursor: pointer;
                backdrop-filter: blur(8px);
                -webkit-backdrop-filter: blur(8px);
              "
            >
              Next ↓
            </button>
          </div>
        </div>

        <div
          style="
            position: absolute;
            right: 12px;
            top: 50%;
            transform: translateY(-50%);
            z-index: 10;
          "
        >
          <rk-reel-indicator
            direction="vertical"
            [visible]="4"
            [radius]="4"
            [gap]="6"
            [count]="indicatorMode() === 'controlled' ? totalSlides : undefined"
            [active]="
              indicatorMode() === 'controlled' ? activeIndex() : undefined
            "
            (dotClick)="reelApi?.goTo($event, true)"
          />
        </div>
      </rk-reel>
    </div>
  `,
})
export class FullPageSliderComponent implements OnInit, OnDestroy {
  private readonly bodyLock = inject(BodyLockService);

  protected readonly totalSlides = TOTAL_SLIDES;
  protected readonly activeIndex = signal(0);
  protected readonly sizeMode = signal<SizeMode>(
    (localStorage.getItem(SIZE_MODE_KEY) as SizeMode) ?? 'explicit',
  );
  protected readonly indicatorMode = signal<IndicatorMode>(
    (localStorage.getItem(INDICATOR_MODE_KEY) as IndicatorMode) ?? 'auto',
  );
  protected readonly explicitSize = signal<[number, number]>([
    window.innerWidth,
    window.innerHeight,
  ]);
  protected goToValue = '';
  protected reelApi: ReelApi | null = null;

  protected readonly getSlideColor = getSlideColor;
  protected readonly getSlideContent = getSlideContent;

  private readonly handleResize = (): void => {
    if (this.sizeMode() !== 'explicit') return;
    this.explicitSize.set([window.innerWidth, window.innerHeight]);
    this.reelApi?.adjust();
  };

  ngOnInit(): void {
    this.bodyLock.lock();
    window.addEventListener('resize', this.handleResize);
  }

  ngOnDestroy(): void {
    this.bodyLock.unlock();
    window.removeEventListener('resize', this.handleResize);
  }

  protected onApiReady(api: ReelApi): void {
    this.reelApi = api;
  }

  protected onAfterChange(event: { index: number }): void {
    this.activeIndex.set(event.index);
  }

  protected toggleSizeMode(): void {
    const next = this.sizeMode() === 'explicit' ? 'auto' : 'explicit';
    localStorage.setItem(SIZE_MODE_KEY, next);
    this.sizeMode.set(next);
  }

  protected toggleIndicatorMode(): void {
    const next = this.indicatorMode() === 'auto' ? 'controlled' : 'auto';
    localStorage.setItem(INDICATOR_MODE_KEY, next);
    this.indicatorMode.set(next);
  }

  protected goToSlide(): void {
    const index = parseInt(this.goToValue, 10) - 1;
    if (index >= 0 && index < TOTAL_SLIDES) {
      this.reelApi?.goTo(index, true);
    }
  }

  protected onInputBlur(): void {
    window.scrollTo(0, 0);
    this.reelApi?.adjust();
  }
}
