// packages/reelkit-angular-stories-player/src/lib/stories-ring/stories-ring.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  input,
  output,
} from '@angular/core';
import {
  getRingPresentation,
  kStoriesRingSize,
  type AuthorInfo,
} from '@reelkit/stories-core';

/**
 * Circular avatar with a gradient ring.
 *
 * The ring has two states: a group with anything left to watch gets the
 * rotating gradient, a fully watched one gets a flat muted ring. Progress
 * within a group is not drawn here — the progress bar inside the player
 * carries that.
 */
@Component({
  selector: 'rk-stories-ring',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      [class]="presentation().className"
      [style]="presentation().style"
      (click)="clicked.emit()"
      (keydown.enter)="clicked.emit()"
      (keydown.space)="$event.preventDefault(); clicked.emit()"
      role="button"
      tabindex="0"
      [attr.aria-label]="ariaLabel()"
    >
      <img
        class="rk-stories-ring-avatar"
        [src]="author().avatar"
        [alt]="author().name"
        [width]="presentation().avatarSize"
        [height]="presentation().avatarSize"
      />
    </div>
  `,
})
export class RkStoriesRingComponent {
  /** Only the avatar and the name are drawn; nothing keys on the id here. */
  readonly author = input.required<AuthorInfo>();

  /** A group of 0 draws no ring at all, just the avatar. */
  readonly totalStories = input.required<number>();

  /** Short of `totalStories` keeps the gradient; reaching it mutes the ring. */
  readonly viewedCount = input.required<number>();

  /**
   * Outer ring diameter in pixels.
   *
   * @default 68
   */
  readonly size = input(kStoriesRingSize);

  /**
   * Gradient colours for a group with stories left to watch.
   *
   * @default the built-in gradient
   */
  readonly gradientColors = input<string[] | undefined>(undefined);

  /**
   * Colour for a fully watched group.
   *
   * @default 'rgba(255,255,255,0.25)'
   */
  readonly viewedColor = input<string | undefined>(undefined);

  /** The ring is a button and nothing more — opening the player is yours. */
  readonly clicked = output<void>();

  protected readonly ariaLabel = computed(
    () => `${this.author().name}'s stories`,
  );

  protected readonly presentation = computed(() =>
    getRingPresentation({
      totalStories: this.totalStories(),
      viewedCount: this.viewedCount(),
      size: this.size(),
      gradientColors: this.gradientColors(),
      viewedColor: this.viewedColor(),
    }),
  );
}

// packages/reelkit-react-stories-player/src/lib/StoriesRing.tsx
import type { CSSProperties, FC } from 'react';
import {
  getRingPresentation,
  kStoriesRingSize,
  type AuthorInfo,
} from '@reelkit/stories-core';
import './StoriesRing.css';

/** Props for the {@link StoriesRing} component. */
export interface StoriesRingProps {
  /** Only the avatar and the name are drawn; nothing keys on the id here. */
  author: AuthorInfo;

  /** A group of 0 draws no ring at all, just the avatar. */
  totalStories: number;

  /** Short of `totalStories` keeps the gradient; reaching it mutes the ring. */
  viewedCount: number;

  /**
   * Outer ring diameter in pixels.
   * @default 68
   */
  size?: number;

  /**
   * Gradient colors for a group with stories left to watch.
   * @default Instagram gradient
   */
  gradientColors?: string[];

  /**
   * Color for a fully watched group.
   * @default 'rgba(255,255,255,0.25)'
   */
  viewedColor?: string;

  /** The ring is a button and nothing more — opening the player is yours. */
  onClick?: () => void;
}

/**
 * Circular avatar with a gradient ring. The ring has two states: a group with
 * anything left to watch gets the rotating Instagram gradient, a fully watched
 * one gets a flat muted ring. Progress within a group is not shown here — the
 * progress bar inside the player carries that.
 */
export const StoriesRing: FC<StoriesRingProps> = ({
  author,
  totalStories,
  viewedCount,
  size = kStoriesRingSize,
  onClick,
  gradientColors,
  viewedColor,
}) => {
  const { avatarSize, className, style } = getRingPresentation({
    totalStories,
    viewedCount,
    size,
    gradientColors,
    viewedColor,
  });

  return (
    <div
      className={className}
      style={style as CSSProperties}
      onClick={onClick}
      onKeyDown={(event) => {
        // A native button opens on Enter and Space; this one has to be told.
        if (event.key !== 'Enter' && event.key !== ' ') return;
        event.preventDefault();
        onClick?.();
      }}
      role="button"
      tabIndex={0}
      aria-label={`${author.name}'s stories`}
    >
      <img
        className="rk-stories-ring-avatar"
        src={author.avatar}
        alt={author.name}
        width={avatarSize}
        height={avatarSize}
      />
    </div>
  );
};
