// apps/example-react/src/app/pages/ImagePreviewVideoPage.tsx
import { useState, useCallback } from 'react';
import {
  LightboxOverlay,
  useVideoSlideRenderer,
  type LightboxItem,
  type TransitionType,
} from '@reelkit/react-lightbox';
import '@reelkit/react-lightbox/styles.css';
import './ImagePreviewPage.css';

const transitions: TransitionType[] = ['slide', 'fade', 'zoom-in'];

const sampleItems: LightboxItem[] = [
  {
    src: 'https://picsum.photos/id/1015/1600/1000',
    title: 'Mountain River',
    description: 'A beautiful mountain river flowing through the forest.',
    width: 1600,
    height: 1000,
  },
  {
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'video',
    poster:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg',
    title: 'For Bigger Blazes',
    description: 'Sample video demonstrating video support in the lightbox.',
  },
  {
    src: 'https://picsum.photos/id/1018/1600/900',
    title: 'Foggy Forest',
    description: 'Misty morning in the dense forest.',
    width: 1600,
    height: 900,
  },
  {
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    type: 'video',
    poster:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
    title: 'For Bigger Escapes',
    description: 'Another sample video showcasing the opt-in video feature.',
  },
  {
    src: 'https://picsum.photos/id/1020/1600/1067',
    title: 'Autumn Path',
    description:
      'A winding path through the autumn forest covered in golden leaves.',
    width: 1600,
    height: 1067,
  },
  {
    src: 'https://picsum.photos/id/1025/900/1350',
    title: 'Puppy Portrait',
    description: 'An adorable puppy looking at the camera with curious eyes.',
    width: 900,
    height: 1350,
  },
];

function ImagePreviewVideoPage() {
  const [previewIndex, setPreviewIndex] = useState<number | null>(null);
  const [transition, setTransition] = useState<TransitionType>('slide');

  const { renderSlide, renderControls } = useVideoSlideRenderer(
    sampleItems,
    previewIndex !== null,
  );

  const handleImageClick = useCallback((index: number) => {
    setPreviewIndex(index);
  }, []);

  const handleClose = useCallback(() => {
    setPreviewIndex(null);
  }, []);

  return (
    <div className="image-gallery-page">
      <div className="gallery-header">
        <h1>Mixed Gallery (Images + Video)</h1>
        <p>
          Click on any item to open the lightbox. Video items use the opt-in{' '}
          <code>useVideoSlideRenderer</code> hook.
        </p>
        <div className="transition-selector">
          <span>Transition:</span>
          {transitions.map((t) => (
            <button
              key={t}
              className={`transition-btn ${transition === t ? 'active' : ''}`}
              onClick={() => setTransition(t)}
            >
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="gallery-grid">
        {sampleItems.map((item, index) => (
          <div
            key={index}
            className="gallery-item"
            onClick={() => handleImageClick(index)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                handleImageClick(index);
              }
            }}
          >
            <img
              src={
                item.type === 'video'
                  ? item.poster
                  : item.src.replace(/\/\d+\/\d+$/, '/400/300')
              }
              alt={item.title || `Item ${index + 1}`}
              loading="lazy"
            />
            <div className="gallery-item-overlay">
              {item.type === 'video' && (
                <span
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: 32,
                    height: 32,
                    borderRadius: '50%',
                    background: 'rgba(255,255,255,0.9)',
                    marginRight: 8,
                    verticalAlign: 'middle',
                  }}
                >
                  <svg width="14" height="16" viewBox="0 0 14 16" fill="#000">
                    <path d="M0 0l14 8-14 8z" />
                  </svg>
                </span>
              )}
              {item.title && (
                <span className="gallery-item-title">{item.title}</span>
              )}
            </div>
          </div>
        ))}
      </div>

      <LightboxOverlay
        isOpen={previewIndex !== null}
        images={sampleItems}
        initialIndex={previewIndex ?? 0}
        onClose={handleClose}
        transition={transition}
        renderSlide={renderSlide}
        renderControls={renderControls}
      />
    </div>
  );
}

export default ImagePreviewVideoPage;

// apps/example-angular/src/app/pages/image-preview-video/image-preview-video-page.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  OnDestroy,
  signal,
} from '@angular/core';
import {
  RkLightboxOverlayComponent,
  RkLightboxControlsDirective,
  RkLightboxSlideDirective,
  RkLightboxVideoSlideComponent,
  RkCloseButtonComponent,
  RkCounterComponent,
  RkFullscreenButtonComponent,
  RkSoundButtonComponent,
  setLightboxVideoMuted,
  type LightboxItem,
  type TransitionType,
} from '@reelkit/angular-lightbox';

const transitions: TransitionType[] = ['slide', 'fade', 'zoom-in'];

const sampleItems: LightboxItem[] = [
  {
    src: 'https://picsum.photos/id/1015/1600/1000',
    title: 'Mountain River',
    description: 'A beautiful mountain river flowing through the forest.',
    width: 1600,
    height: 1000,
  },
  {
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'video',
    poster:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg',
    title: 'For Bigger Blazes',
    description: 'Sample video demonstrating video support in the lightbox.',
  },
  {
    src: 'https://picsum.photos/id/1018/1600/900',
    title: 'Foggy Forest',
    description: 'Misty morning in the dense forest.',
    width: 1600,
    height: 900,
  },
  {
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    type: 'video',
    poster:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg',
    title: 'For Bigger Escapes',
    description: 'Another sample video showcasing the opt-in video feature.',
  },
  {
    src: 'https://picsum.photos/id/1020/1600/1067',
    title: 'Autumn Path',
    description:
      'A winding path through the autumn forest covered in golden leaves.',
    width: 1600,
    height: 1067,
  },
  {
    src: 'https://picsum.photos/id/1025/900/1350',
    title: 'Puppy Portrait',
    description: 'An adorable puppy looking at the camera with curious eyes.',
    width: 900,
    height: 1350,
  },
];

@Component({
  selector: 'app-image-preview-video-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    RkLightboxOverlayComponent,
    RkLightboxControlsDirective,
    RkLightboxSlideDirective,
    RkLightboxVideoSlideComponent,
    RkCloseButtonComponent,
    RkCounterComponent,
    RkFullscreenButtonComponent,
    RkSoundButtonComponent,
  ],
  styleUrls: ['../image-preview/image-preview-page.css'],
  template: `
    <div class="image-gallery-page">
      <div class="gallery-header">
        <h1>Mixed Gallery (Images + Video)</h1>
        <p>
          Click on any item to open the lightbox. Video items use the opt-in
          <code>RkLightboxVideoSlideComponent</code>.
        </p>
        <div class="transition-selector">
          <span>Transition:</span>
          @for (t of transitions; track t) {
            <button
              [class]="'transition-btn' + (transition() === t ? ' active' : '')"
              (click)="transition.set(t)"
            >
              {{ t }}
            </button>
          }
        </div>
      </div>

      <div class="gallery-grid">
        @for (item of items; track item.src; let index = $index) {
          <div
            class="gallery-item"
            (click)="previewIndex.set(index)"
            role="button"
            [attr.tabindex]="0"
            (keydown.enter)="previewIndex.set(index)"
            (keydown.space)="$event.preventDefault(); previewIndex.set(index)"
          >
            <img
              [src]="thumbnailSrc(item)"
              [alt]="item.title ?? 'Item ' + (index + 1)"
              loading="lazy"
            />
            <div class="gallery-item-overlay">
              @if (item.type === 'video') {
                <span
                  style="
                    display: inline-flex;
                    align-items: center;
                    justify-content: center;
                    width: 32px;
                    height: 32px;
                    border-radius: 50%;
                    background: rgba(255,255,255,0.9);
                    margin-right: 8px;
                    vertical-align: middle;
                  "
                >
                  <svg width="14" height="16" viewBox="0 0 14 16" fill="#000">
                    <path d="M0 0l14 8-14 8z" />
                  </svg>
                </span>
              }
              @if (item.title) {
                <span class="gallery-item-title">{{ item.title }}</span>
              }
            </div>
          </div>
        }
      </div>

      <rk-lightbox-overlay
        [isOpen]="previewIndex() !== null"
        [items]="items"
        [initialIndex]="previewIndex() ?? 0"
        [transition]="transition()"
        (closed)="onClose()"
      >
        <ng-template
          rkLightboxControls
          let-ctx="onClose"
          let-currentIndex="currentIndex"
          let-count="count"
          let-isFullscreen="isFullscreen"
          let-onToggleFullscreen="onToggleFullscreen"
          let-onClose="onClose"
        >
          <div class="rk-lightbox-controls-left">
            <rk-counter [currentIndex]="currentIndex" [count]="count" />
            <rk-fullscreen-button
              [isFullscreen]="isFullscreen"
              (toggled)="onToggleFullscreen()"
            />
            <rk-sound-button [muted]="isMuted()" (toggled)="toggleMute()" />
          </div>
          <rk-close-button (clicked)="onClose()" />
        </ng-template>

        <ng-template
          rkLightboxSlide
          let-item
          let-size="size"
          let-isActive="isActive"
        >
          @if (item.type === 'video') {
            <rk-lightbox-video-slide
              [src]="item.src"
              [poster]="item.poster"
              [isActive]="isActive"
              [size]="size"
              [slideKey]="item.src"
            />
          } @else {
            <img
              [src]="item.src"
              [alt]="item.title ?? ''"
              class="rk-lightbox-img rk-loaded"
            />
          }
        </ng-template>
      </rk-lightbox-overlay>
    </div>
  `,
})
export class ImagePreviewVideoPageComponent implements OnDestroy {
  protected readonly items: LightboxItem[] = sampleItems;
  protected readonly transitions: TransitionType[] = transitions;
  protected readonly previewIndex = signal<number | null>(null);
  protected readonly transition = signal<TransitionType>('slide');
  protected readonly isMuted = signal(true);

  protected onClose(): void {
    this.previewIndex.set(null);
    // Reset to muted when lightbox closes so next open can autoplay.
    this.isMuted.set(true);
    setLightboxVideoMuted(true);
  }

  protected toggleMute(): void {
    const next = !this.isMuted();
    this.isMuted.set(next);
    setLightboxVideoMuted(next);
  }

  ngOnDestroy(): void {
    setLightboxVideoMuted(true);
  }

  protected thumbnailSrc(item: LightboxItem): string {
    if (item.type === 'video') {
      return item.poster ?? '';
    }
    return item.src.replace(/\/\d+\/\d+$/, '/400/300');
  }
}
