// apps/example-vue/src/pages/StoriesPlayerUrlPage.vue
<script setup lang="ts">
import { computed, shallowRef } from 'vue';
import type {
  ChromePlacement,
  DesktopLayout,
} from '@reelkit/vue-stories-player';
import { persistedRef } from '../composables/persistedRef';
import Segmented from '../components/Segmented.vue';
import StoriesSwitches from '../components/StoriesSwitches.vue';
import StoriesUrlDemo from './stories-player-url/StoriesUrlDemo.vue';
import {
  generateUrlGroups,
  kUrlPageSize,
  type Addressing,
  type InnerKey,
} from './stories-player-url/urlFeed';

// The whole feed, generated once, and the part of it that has "arrived". Both
// outlive a switch, so paging in a group survives a change of URL key shape.
const allGroups = generateUrlGroups();
const loaded = shallowRef(allGroups.slice(0, kUrlPageSize));

const addressing = persistedRef<Addressing>(
  'reelkit-stories-player-url-addressing',
  'index',
);
const innerKey = persistedRef<InnerKey>(
  'reelkit-stories-player-url-inner-key',
  'index',
);
const hash = persistedRef('reelkit-stories-player-url-hash', false);
const rememberSeen = persistedRef(
  'reelkit-stories-player-url-remember-seen',
  true,
);
const desktopLayout = persistedRef<DesktopLayout>(
  'reelkit-stories-player-url-desktop-layout',
  'single',
);
const chromePlacement = persistedRef<ChromePlacement>(
  'reelkit-stories-player-url-chrome-placement',
  'overlay',
);

const hashable = computed(
  () => addressing.value === 'stableId' || innerKey.value === 'stableId',
);

// Remount when the key shape changes: `useOverlayUrlState` builds its controller
// once, so a fresh key needs a fresh instance. The stale parameter self-heals
// out of the URL.
const demoKey = computed(
  () => `${addressing.value}.${innerKey.value}.${hash.value ? 'hash' : 'raw'}`,
);
</script>

<template>
  <div class="page">
    <div class="container">
      <h1>URL Stories Player</h1>
      <p class="subtitle">
        The open group and story live in one
        <code>?story=&lt;group&gt;.&lt;story&gt;</code> parameter. Tapping a
        ring opens that user; swiping only replaces the entry, so one back step
        always closes. The switches rebuild the group half of the URL key. Only
        the first {{ kUrlPageSize }} groups have loaded — a link past them pages
        the rest in first.
      </p>

      <div class="switchers">
        <Segmented
          legend="Group addressing"
          :options="[
            {
              label: 'Index — 2.…',
              active: addressing === 'index',
              onClick: () => (addressing = 'index'),
            },
            {
              label: 'Stable id — user-2.…',
              active: addressing === 'stableId',
              onClick: () => (addressing = 'stableId'),
            },
          ]"
        />
        <Segmented
          legend="Story addressing"
          :options="[
            {
              label: 'Index — .0',
              active: innerKey === 'index',
              onClick: () => (innerKey = 'index'),
            },
            {
              label: 'Stable id — .story-2-0',
              active: innerKey === 'stableId',
              onClick: () => (innerKey = 'stableId'),
            },
          ]"
        />
        <Segmented
          legend="Hash (stable id)"
          :options="[
            {
              label: 'Raw',
              active: hashable && !hash,
              disabled: !hashable,
              onClick: () => (hash = false),
            },
            {
              label: 'base64url',
              active: hashable && hash,
              disabled: !hashable,
              onClick: () => (hash = true),
            },
          ]"
        />
        <StoriesSwitches
          v-model:remember-seen="rememberSeen"
          v-model:desktop-layout="desktopLayout"
          v-model:chrome-placement="chromePlacement"
        />
      </div>

      <StoriesUrlDemo
        :key="demoKey"
        v-model:loaded="loaded"
        :all-groups="allGroups"
        :addressing="addressing"
        :inner-key="innerKey"
        :hash="hash"
        :remember-seen="rememberSeen"
        :desktop-layout="desktopLayout"
        :chrome-placement="chromePlacement"
      />
    </div>
  </div>
</template>

<style scoped>
.page {
  min-height: 100dvh;
  background-color: #111;
  padding: 56px 16px 16px;
  color: #fff;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
}

h1 {
  font-size: 1.5rem;
  margin-bottom: 16px;
  font-weight: 500;
}

.subtitle {
  color: rgba(255, 255, 255, 0.6);
  font-size: 0.9rem;
  margin-bottom: 20px;
}

.switchers {
  display: flex;
  gap: 20px;
  flex-wrap: wrap;
  margin-bottom: 24px;
}
</style>

// apps/example-angular/src/app/pages/stories-player-url/stories-player-url-page.component.ts
import { ChangeDetectionStrategy, Component, computed } from '@angular/core';
import type {
  ChromePlacement,
  DesktopLayout,
  StoriesGroup,
  StoryItem,
} from '@reelkit/angular-stories-player';
import { cdnUrl } from '@reelkit/example-data';
import { persistedSignal } from '../../util/persisted-signal';
import {
  StoriesUrlDemoComponent,
  type Addressing,
  type InnerKey,
} from './stories-url-demo.component';

/** How many groups the demo pretends to have loaded so far. */
const _kPageSize = 3;

const _kNames = [
  'Alice',
  'Bob',
  'Charlie',
  'Diana',
  'Eve',
  'Frank',
  'Grace',
  'Heidi',
];

/** The full feed, generated once so a switch never regenerates it. */
const feed: StoriesGroup<StoryItem>[] = _kNames.map((name, i) => ({
  author: {
    id: `user-${i}`,
    name,
    avatar: cdnUrl(
      `samples/avatars/avatar-${String(6 + i).padStart(2, '0')}.jpg`,
    ),
    verified: i % 3 === 0,
  },
  stories: Array.from({ length: 2 + (i % 3) }, (_, j) => ({
    id: `story-${i}-${j}`,
    mediaType: 'image' as const,
    src: cdnUrl(
      `samples/images/stories/story-${String(((i * 10 + j) % 100) + 1).padStart(3, '0')}.jpg`,
    ),
    createdAt: new Date(Date.now() - (i * 3 + j) * 3600_000).toISOString(),
  })),
}));

/**
 * The stories player with its open state in the URL, switchable across every
 * key shape so one page shows them all: each axis by index or by stable id,
 * with or without base64url hashing. The switches rebuild the URL key, so the
 * address bar changes shape while the player stays the same.
 */
@Component({
  selector: 'app-stories-player-url-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StoriesUrlDemoComponent],
  template: `
    <div
      style="min-height: 100dvh; background-color: #111; padding: 56px 16px 16px;"
    >
      <div style="max-width: 1200px; margin: 0 auto;">
        <h1
          style="color: #fff; font-size: 1.5rem; margin-bottom: 16px; font-weight: 500;"
        >
          URL Stories Player
        </h1>
        <p
          style="color: rgba(255,255,255,0.6); font-size: 0.9rem; margin-bottom: 20px;"
        >
          The open group and story live in one
          <code>?story=&lt;group&gt;.&lt;story&gt;</code> parameter. Tapping a
          ring opens that user; swiping only replaces the entry, so one back
          step always closes. The switches rebuild the group half of the URL
          key. Only the first {{ pageSize }} groups have loaded — a link past
          them pages the rest in first.
        </p>

        <div
          style="display: flex; gap: 20px; flex-wrap: wrap; margin-bottom: 24px;"
        >
          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Group addressing
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [style]="segStyle(addressing() === 'index')"
                (click)="addressing.set('index')"
              >
                Index — 2.…
              </button>
              <button
                type="button"
                [style]="segStyle(addressing() === 'stableId')"
                (click)="addressing.set('stableId')"
              >
                Stable id — user-2.…
              </button>
            </div>
          </fieldset>

          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Story addressing
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [style]="segStyle(innerKey() === 'index')"
                (click)="innerKey.set('index')"
              >
                Index — .0
              </button>
              <button
                type="button"
                [style]="segStyle(innerKey() === 'stableId')"
                (click)="innerKey.set('stableId')"
              >
                Stable id — .story-2-0
              </button>
            </div>
          </fieldset>

          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Hash (stable id)
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [disabled]="!hashable()"
                [style]="segStyle(hashable() && !hash(), !hashable())"
                (click)="hash.set(false)"
              >
                Raw
              </button>
              <button
                type="button"
                [disabled]="!hashable()"
                [style]="segStyle(hashable() && hash(), !hashable())"
                (click)="hash.set(true)"
              >
                base64url
              </button>
            </div>
          </fieldset>

          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Remember seen
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [style]="segStyle(rememberSeen())"
                (click)="rememberSeen.set(true)"
              >
                On
              </button>
              <button
                type="button"
                [style]="segStyle(!rememberSeen())"
                (click)="rememberSeen.set(false)"
              >
                Off
              </button>
            </div>
          </fieldset>

          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Desktop layout
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [style]="segStyle(desktopLayout() === 'single')"
                (click)="desktopLayout.set('single')"
              >
                Single
              </button>
              <button
                type="button"
                [style]="segStyle(desktopLayout() === 'carousel')"
                (click)="desktopLayout.set('carousel')"
              >
                Carousel
              </button>
            </div>
          </fieldset>

          <fieldset style="border: 0; padding: 0; margin: 0;">
            <legend
              style="color: rgba(255,255,255,0.5); font-size: 0.72rem; margin-bottom: 6px;"
            >
              Progress &amp; header
            </legend>
            <div style="display: flex; gap: 6px;">
              <button
                type="button"
                [style]="segStyle(chromePlacement() === 'overlay')"
                (click)="chromePlacement.set('overlay')"
              >
                Overlay
              </button>
              <button
                type="button"
                [style]="segStyle(chromePlacement() === 'group')"
                (click)="chromePlacement.set('group')"
              >
                Group
              </button>
            </div>
          </fieldset>
        </div>

        <!-- Remount when the key shape changes: createOverlayUrlState builds
             its controller once, so a fresh key needs a fresh instance.
             Tracking the key string makes @for tear the demo down and rebuild
             it, and the stale parameter then self-heals. -->
        @for (shape of [demoKey()]; track shape) {
          <app-stories-url-demo
            [feed]="feed"
            [pageSize]="pageSize"
            [addressing]="addressing()"
            [innerKey]="innerKey()"
            [hash]="hash()"
            [rememberSeen]="rememberSeen()"
            [desktopLayout]="desktopLayout()"
            [chromePlacement]="chromePlacement()"
          />
        }
      </div>
    </div>
  `,
})
export class StoriesPlayerUrlPageComponent {
  protected readonly feed = feed;
  protected readonly pageSize = _kPageSize;

  protected readonly addressing = persistedSignal<Addressing>(
    'reelkit-stories-player-url-addressing',
    'index',
  );
  protected readonly innerKey = persistedSignal<InnerKey>(
    'reelkit-stories-player-url-inner-key',
    'index',
  );
  protected readonly hash = persistedSignal(
    'reelkit-stories-player-url-hash',
    false,
  );
  protected readonly rememberSeen = persistedSignal(
    'reelkit-stories-player-url-remember-seen',
    true,
  );
  protected readonly desktopLayout = persistedSignal<DesktopLayout>(
    'reelkit-stories-player-url-desktop-layout',
    'single',
  );
  protected readonly chromePlacement = persistedSignal<ChromePlacement>(
    'reelkit-stories-player-url-chrome-placement',
    'overlay',
  );

  /** Hashing only means anything once an axis is addressed by id. */
  protected readonly hashable = computed(
    () => this.addressing() === 'stableId' || this.innerKey() === 'stableId',
  );

  protected readonly demoKey = computed(
    () =>
      `${this.addressing()}.${this.innerKey()}.${this.hash() ? 'hash' : 'raw'}`,
  );

  protected segStyle(active: boolean, disabled = false): string {
    const background = active
      ? 'rgba(99,102,241,0.55)'
      : 'rgba(255,255,255,0.06)';
    const color = disabled ? 'rgba(255,255,255,0.3)' : '#fff';
    const cursor = disabled ? 'not-allowed' : 'pointer';
    return `padding: 6px 12px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.2); background: ${background}; color: ${color}; font-size: 0.8rem; cursor: ${cursor};`;
  }
}
