// packages/reelkit-react-reel-player/src/lib/NestedSlider.tsx
import React, { type ReactNode, useState, useRef, useEffect } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import {
  Reel,
  ReelIndicator,
  Observe,
  createSignal,
  type ReelApi,
} from '@reelkit/react';
import type {
  BaseContentItem,
  MediaItem,
  NavigationRenderProps,
  NestedSlideRenderProps,
} from './types';
import ImageSlide from './ImageSlide';
import VideoSlide from './VideoSlide';
import './NestedSlider.css';

/** @internal */
interface NestedSliderProps {
  media: MediaItem[];
  contentItem: BaseContentItem;
  isParentActive: boolean;
  size: [number, number];
  contentId: string;
  innerSliderRef: React.MutableRefObject<ReelApi | null>;
  enableWheel?: boolean;

  /** Inner media index to open at. Applies only on first mount. @default 0 */
  initialIndex?: number;
  onVideoRef?: (ref: HTMLVideoElement | null) => void;
  onActiveMediaTypeChange?: (type: 'image' | 'video') => void;

  /** Fired after the active inner media index changes. */
  onIndexChange?: (index: number) => void;
  onReady?: () => void;
  onWaiting?: () => void;
  onError?: () => void;
  renderNavigation?: (props: NavigationRenderProps) => ReactNode;
  renderNestedSlide?: (props: NestedSlideRenderProps) => ReactNode;
}

/**
 * Horizontal nested slider for multi-media content items (e.g. an Instagram
 * carousel post with both images and videos).
 *
 * Renders a horizontal `Reel` inside a vertical slide, with indicator dots
 * and left/right navigation arrows. Syncs its active ref with the parent
 * player for coordinated drag/unobserve behavior.
 *
 * @internal Used by {@link MediaSlide} when a content item has multiple media assets.
 */
const NestedSlider: React.FC<NestedSliderProps> = (props) => {
  const { media, isParentActive, size, innerSliderRef, enableWheel } = props;

  const propsRef = useRef(props);
  propsRef.current = props;
  const localSliderRef = useRef<ReelApi>(null);
  const videoRef = useRef<HTMLVideoElement | null>(null);

  const [
    {
      indexSignal,
      seed,
      handleBeforeChange,
      handleAfterChange,
      handlePrev,
      handleNext,
      itemBuilder,
    },
  ] = useState(() => {
    // Clamp the seed: a URL may name an inner index past this post's media.
    const seed =
      props.initialIndex !== undefined &&
      props.initialIndex >= 0 &&
      props.initialIndex < props.media.length
        ? props.initialIndex
        : 0;
    const indexSignal = createSignal(seed);

    const handleVideoRef = (ref: HTMLVideoElement | null) => {
      videoRef.current = ref;
      propsRef.current.onVideoRef?.(ref);
    };

    return {
      indexSignal,
      seed,
      handleBeforeChange: () => {
        if (videoRef.current && !videoRef.current.paused) {
          videoRef.current.pause();
        }
      },
      handleAfterChange: (index: number) => {
        indexSignal.value = index;
        const {
          media: items,
          onActiveMediaTypeChange,
          onReady,
          onIndexChange,
        } = propsRef.current;
        onActiveMediaTypeChange?.(items[index].type);
        onIndexChange?.(index);
        if (items[index].type === 'image') {
          onReady?.();
        }
      },
      handlePrev: () => {
        localSliderRef.current?.prev();
      },
      handleNext: () => {
        localSliderRef.current?.next();
      },
      itemBuilder: (
        index: number,
        _indexInRange: number,
        itemSize: [number, number],
      ) => {
        const {
          media: items,
          isParentActive: parentActive,
          contentId: cId,
          onReady,
          onWaiting,
          onError,
          renderNestedSlide,
        } = propsRef.current;
        const item = items[index];
        const isInnerActive = index === indexSignal.value;
        const slideKey = `${cId}:${item.id}`;
        const videoRefProp = isInnerActive ? handleVideoRef : undefined;

        const defaultContent =
          item.type === 'video' ? (
            <VideoSlide
              src={item.src}
              poster={item.poster}
              aspectRatio={item.aspectRatio}
              size={itemSize}
              isActive={parentActive}
              isInnerActive={isInnerActive}
              slideKey={slideKey}
              onVideoRef={videoRefProp}
              onReady={isInnerActive ? onReady : undefined}
              onWaiting={isInnerActive ? onWaiting : undefined}
              onError={isInnerActive ? onError : undefined}
            />
          ) : (
            <ImageSlide
              src={item.src}
              size={itemSize}
              imageProps={
                isInnerActive ? { onLoad: onReady, onError } : undefined
              }
            />
          );

        if (renderNestedSlide) {
          return renderNestedSlide({
            item: propsRef.current.contentItem,
            media: item,
            index,
            size: itemSize,
            isActive: parentActive,
            isInnerActive,
            slideKey,
            onVideoRef: videoRefProp,
            onReady: isInnerActive ? onReady : undefined,
            onWaiting: isInnerActive ? onWaiting : undefined,
            onError: isInnerActive ? onError : undefined,
            defaultContent,
          });
        }

        return defaultContent;
      },
    };
  });

  useEffect(() => {
    innerSliderRef.current = localSliderRef.current;
    return () => {
      innerSliderRef.current = null;
    };
  }, [innerSliderRef]);

  useEffect(() => {
    if (isParentActive) {
      // On activation, report the live inner index so a URL following the
      // player names the media actually on screen — 0 on a fresh mount, the
      // retained index while this post stayed in the virtualization window.
      propsRef.current.onActiveMediaTypeChange?.(media[indexSignal.value].type);
      propsRef.current.onIndexChange?.(indexSignal.value);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isParentActive]);

  return (
    <div
      style={{
        width: size[0],
        height: size[1],
        position: 'relative',
        backgroundColor: '#000',
      }}
    >
      <Reel
        count={media.length}
        size={size}
        direction="horizontal"
        loop={false}
        enableNavKeys={true}
        enableWheel={enableWheel}
        initialIndex={seed}
        apiRef={localSliderRef}
        beforeChange={handleBeforeChange}
        afterChange={handleAfterChange}
        className={isParentActive ? 'rk-reel-nested-active' : undefined}
        itemBuilder={itemBuilder}
      />

      <Observe signals={[indexSignal]}>
        {() => {
          const idx = indexSignal.value;
          const { media: items, renderNavigation: renderNav } =
            propsRef.current;

          return (
            <>
              {items.length > 1 && (
                <div className="rk-reel-nested-indicator">
                  <ReelIndicator
                    count={items.length}
                    active={idx}
                    direction="horizontal"
                    visible={5}
                    radius={3}
                    gap={4}
                    activeColor="#fff"
                    inactiveColor="rgba(255,255,255,0.4)"
                    onDotClick={(i) => localSliderRef.current?.goTo(i, true)}
                  />
                </div>
              )}

              {items.length > 1 &&
                (renderNav ? (
                  renderNav({
                    item: propsRef.current.contentItem as BaseContentItem,
                    media: items[idx],
                    onPrev: handlePrev,
                    onNext: handleNext,
                    activeIndex: idx,
                    count: items.length,
                  })
                ) : (
                  <>
                    {idx > 0 && (
                      <button
                        className="rk-reel-nested-nav rk-reel-nested-nav-prev"
                        onClick={handlePrev}
                        aria-label="Previous"
                      >
                        <ChevronLeft size={24} />
                      </button>
                    )}
                    {idx < items.length - 1 && (
                      <button
                        className="rk-reel-nested-nav rk-reel-nested-nav-next"
                        onClick={handleNext}
                        aria-label="Next"
                      >
                        <ChevronRight size={24} />
                      </button>
                    )}
                  </>
                ))}
            </>
          );
        }}
      </Observe>
    </div>
  );
};

export default NestedSlider;

// packages/reelkit-angular-reel-player/src/lib/nested-slider/nested-slider.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  TemplateRef,
  ViewEncapsulation,
  computed,
  effect,
  input,
  linkedSignal,
  output,
  untracked,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  LucideAngularModule,
  LucideIconProvider,
  LUCIDE_ICONS,
  ChevronLeft,
  ChevronRight,
} from 'lucide-angular';
import {
  ReelComponent,
  ReelIndicatorComponent,
  RkReelItemDirective,
  type ReelApi,
} from '@reelkit/angular';
import { RkVideoSlideComponent } from '../video-slide/video-slide.component';
import { RkImageSlideComponent } from '../image-slide/image-slide.component';
import type {
  MediaItem,
  MediaType,
  PlayerNestedNavigationContext,
  PlayerNestedSlideContext,
} from '../types';

/**
 * Horizontal nested slider for multi-media content items (e.g. an Instagram
 * carousel post with both images and videos).
 *
 * Renders a horizontal `rk-reel` inside a vertical slide, with indicator dots
 * and left/right navigation arrows. Syncs its active ref with the parent
 * player for coordinated drag/unobserve behavior.
 *
 * @internal Used by `RkMediaSlideComponent` when a content item has multiple media assets.
 */
@Component({
  selector: 'rk-nested-slider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { style: 'display:block;width:100%;height:100%' },
  imports: [
    NgTemplateOutlet,
    LucideAngularModule,
    ReelComponent,
    ReelIndicatorComponent,
    RkReelItemDirective,
    RkVideoSlideComponent,
    RkImageSlideComponent,
  ],
  providers: [
    {
      provide: LUCIDE_ICONS,
      useValue: new LucideIconProvider({ ChevronLeft, ChevronRight }),
      multi: true,
    },
  ],
  template: `
    <div
      class="rk-reel-nested-slider-inner"
      role="region"
      aria-label="Media carousel"
      [style.width.px]="width()"
      [style.height.px]="height()"
    >
      <rk-reel
        [count]="media().length"
        [size]="size()"
        direction="horizontal"
        [loop]="false"
        [enableNavKeys]="true"
        [enableWheel]="enableWheel()"
        [initialIndex]="seedIndex()"
        [class.rk-reel-nested-active]="isActive()"
        (apiReady)="onInnerApiReady($event)"
        (beforeChange)="onBeforeChange()"
        (afterChange)="onAfterChange($event)"
      >
        <ng-template rkReelItem let-index let-size="size">
          @let item = mediaAt(index);
          @let isInnerActive = innerActiveIndex() === index;
          @let key = slideKey() + ':' + item.id;

          @if (nestedSlideTemplate()) {
            <ng-container
              [ngTemplateOutlet]="nestedSlideTemplate()!"
              [ngTemplateOutletContext]="{
                $implicit: item,
                index: index,
                size: size,
                isActive: isActive(),
                isInnerActive: isInnerActive,
                slideKey: key,
              }"
            />
          } @else {
            @if (item.type === 'video') {
              <rk-video-slide
                [src]="item.src"
                [poster]="item.poster"
                [aspectRatio]="item.aspectRatio"
                [width]="size[0]"
                [height]="size[1]"
                [isActive]="isActive()"
                [isInnerActive]="isInnerActive"
                [slideKey]="key"
                [onReady]="isInnerActive ? onReady() : undefined"
                [onWaiting]="isInnerActive ? onWaiting() : undefined"
                [onError]="isInnerActive ? onError() : undefined"
                (videoRef)="
                  isInnerActive || !$event ? onVideoRef($event) : null
                "
              />
            } @else {
              <rk-image-slide
                [src]="item.src"
                [width]="size[0]"
                [height]="size[1]"
                [onReady]="isInnerActive ? onReady() : undefined"
                [onError]="isInnerActive ? onError() : undefined"
              />
            }
          }
        </ng-template>
      </rk-reel>

      @if (media().length > 1) {
        <div class="rk-reel-nested-indicator">
          <rk-reel-indicator
            [count]="media().length"
            [active]="innerActiveIndex()"
            direction="horizontal"
            [visible]="5"
            [radius]="3"
            [gap]="4"
            activeColor="#fff"
            inactiveColor="rgba(255,255,255,0.4)"
            (dotClick)="onDotClick($event)"
          />
        </div>
      }

      @if (media().length > 1) {
        @if (nestedNavTemplate()) {
          <ng-container
            [ngTemplateOutlet]="nestedNavTemplate()!"
            [ngTemplateOutletContext]="{
              $implicit: onPrevFn,
              media: media()[innerActiveIndex()],
              onPrev: onPrevFn,
              onNext: onNextFn,
              activeIndex: innerActiveIndex(),
              count: media().length,
            }"
          />
        } @else {
          @if (innerActiveIndex() > 0) {
            <button
              class="rk-reel-nested-nav rk-reel-nested-nav-prev"
              (click)="onPrev()"
              aria-label="Previous media"
            >
              <lucide-angular [img]="ChevronLeftIcon" [size]="24" />
            </button>
          }
          @if (innerActiveIndex() < media().length - 1) {
            <button
              class="rk-reel-nested-nav rk-reel-nested-nav-next"
              (click)="onNext()"
              aria-label="Next media"
            >
              <lucide-angular [img]="ChevronRightIcon" [size]="24" />
            </button>
          }
        }
      }
    </div>
  `,
})
export class RkNestedSliderComponent {
  readonly media = input.required<MediaItem[]>();
  readonly isActive = input<boolean>(false);
  readonly width = input<number>(0);
  readonly height = input<number>(0);
  readonly slideKey = input.required<string>();
  readonly enableWheel = input<boolean>(false);
  /**
   * Inner media index to open at. Applies only on first mount, so a two-axis
   * URL can deep-link into a specific image of a multi-media post; later
   * navigation is the user's own.
   */
  readonly initialIndex = input<number | undefined>(undefined);
  readonly onReady = input<(() => void) | undefined>(undefined);
  readonly onWaiting = input<(() => void) | undefined>(undefined);
  readonly onError = input<(() => void) | undefined>(undefined);
  readonly nestedSlideTemplate =
    input<TemplateRef<PlayerNestedSlideContext> | null>(null);
  readonly nestedNavTemplate =
    input<TemplateRef<PlayerNestedNavigationContext> | null>(null);

  readonly innerActiveIndexChange = output<number>();
  readonly videoRef = output<HTMLVideoElement | null>();
  readonly innerMediaType = output<MediaType>();
  readonly innerApiReady = output<ReelApi>();

  /**
   * The clamped first-mount seed: a URL may name an inner index past this
   * post's media, so an out-of-range seed falls back to `0`. Feeds the inner
   * reel's initial position.
   */
  readonly seedIndex = computed(() => {
    const seed = this.initialIndex();
    const length = this.media().length;
    return seed !== undefined && seed >= 0 && seed < length ? seed : 0;
  });

  // Applies the seed on the first mount only; a later media swap resets to 0.
  private _seeded = false;

  /**
   * Tracks the active inner slide index. Opens at the clamped seed on first
   * mount, then resets to `0` when the `media` input changes (e.g. the parent
   * swaps to a different content item), preventing a stale index from pointing
   * beyond the bounds of the new array.
   */
  readonly innerActiveIndex = linkedSignal(() => {
    void this.media();
    if (!this._seeded) {
      this._seeded = true;
      return untracked(this.seedIndex);
    }
    return 0;
  });

  protected readonly ChevronLeftIcon = ChevronLeft;
  protected readonly ChevronRightIcon = ChevronRight;

  /**
   * Stable arrow-function references for template context objects.
   * Avoids creating new function instances on every change-detection cycle.
   */
  readonly onPrevFn = (): void => this.onPrev();
  readonly onNextFn = (): void => this.onNext();

  readonly size = computed<[number, number]>(() => [
    this.width(),
    this.height(),
  ]);

  private _innerApi: ReelApi | null = null;
  private _videoEl: HTMLVideoElement | null = null;

  constructor() {
    effect(() => {
      if (this.isActive()) {
        const idx = this.innerActiveIndex();
        const items = this.media();
        if (items[idx]) {
          this.innerMediaType.emit(items[idx].type);
        }
      }
    });

    // On activation, report the retained inner index so a URL following the
    // player names the media actually on screen — the seed on a fresh mount,
    // the retained index while this post stayed in the window. Depends on
    // isActive only; the index is read untracked so it fires on activation, not
    // on every inner navigation (that path reports through onAfterChange).
    effect(() => {
      if (this.isActive()) {
        this.innerActiveIndexChange.emit(untracked(this.innerActiveIndex));
      }
    });
  }

  mediaAt(index: number): MediaItem {
    // Guard against transient out-of-bounds access during media array changes.
    // The linkedSignal resets innerActiveIndex to 0 on media change, but the
    // virtual reel may still request the old index in the same render cycle.
    return this.media()[index] ?? this.media()[0];
  }

  onInnerApiReady(api: ReelApi): void {
    this._innerApi = api;
    this.innerApiReady.emit(api);
  }

  onAfterChange(event: { index: number }): void {
    this.innerActiveIndex.set(event.index);
    this.innerActiveIndexChange.emit(event.index);
    const items = this.media();
    const item = items[event.index];
    if (item) {
      this.innerMediaType.emit(item.type);
      if (item.type === 'image') {
        this.onReady()?.();
      }
    }
  }

  onBeforeChange(): void {
    if (this._videoEl && !this._videoEl.paused) {
      this._videoEl.pause();
    }
  }

  onVideoRef(ref: HTMLVideoElement | null): void {
    this._videoEl = ref;
    this.videoRef.emit(ref);
  }

  onDotClick(index: number): void {
    this._innerApi?.goTo(index, true);
  }

  onPrev(): void {
    this._innerApi?.prev();
  }

  onNext(): void {
    this._innerApi?.next();
  }

  unobserve(): void {
    this._innerApi?.unobserve();
  }

  observe(): void {
    this._innerApi?.observe();
  }
}
