// packages/reelkit-angular-reel-player/src/index.ts
/**
 * @module @reelkit/angular-reel-player
 *
 * Full-screen, Instagram/TikTok-style vertical reel player overlay for Angular.
 *
 * The main entry point is {@link RkReelPlayerOverlayComponent}: a generic,
 * customizable standalone component that renders a virtualized vertical slider
 * with media playback, gesture/keyboard/wheel navigation, and optional sound
 * controls.
 *
 * Customization is achieved via `@ContentChild` template slots:
 * - `rkPlayerSlideOverlay`: custom per-slide overlays
 * - `rkPlayerSlide`: fully custom slide content
 * - `rkPlayerControls`: custom player controls
 * - `rkPlayerNavigation`: custom navigation arrows
 * - `rkPlayerNestedSlide`: custom nested horizontal slide content
 * - `rkPlayerNestedNavigation`: custom arrows for the inner horizontal slider
 *
 * For custom data types, extend {@link BaseContentItem}:
 * ```ts
 * interface MyItem extends BaseContentItem {
 *   title: string;
 * }
 * ```
 *
 * @example
 * ```ts
 * import { Component, signal } from '@angular/core';
 * import {
 *   RkReelPlayerOverlayComponent,
 *   type ContentItem,
 * } from '@reelkit/angular-reel-player';
 * import '@reelkit/angular-reel-player/styles.css';
 *
 * @Component({
 *   imports: [RkReelPlayerOverlayComponent],
 *   template: `
 *     <button (click)="isOpen.set(true)">Open Player</button>
 *     <rk-reel-player-overlay
 *       [isOpen]="isOpen()"
 *       [content]="items"
 *       (closed)="isOpen.set(false)"
 *     />
 *   `,
 * })
 * export class AppComponent {
 *   isOpen = signal(false);
 *   items: ContentItem[] = [...];
 * }
 * ```
 *
 * Open state comes in two shapes. {@link RkReelPlayerOverlayComponent} is
 * controlled — the surrounding component owns `isOpen`.
 * {@link RkReelPlayerUrlOverlayComponent} puts it in the address bar instead,
 * so the playing slide has a link that can be shared, bookmarked, and closed
 * with the back button. Every template slot above works the same in either.
 *
 * @example URL-driven — opening is a link, back closes
 * ```ts
 * import { Component } from '@angular/core';
 * import { RouterLink } from '@angular/router';
 * import {
 *   RkReelPlayerUrlOverlayComponent,
 *   type ContentItem,
 * } from '@reelkit/angular-reel-player';
 * import { createOverlayUrlState, urlIndexKey } from '@reelkit/angular';
 * import { createRouterUrlAdapter } from '@reelkit/angular/ng-router-url-adapter';
 * import '@reelkit/angular-reel-player/styles.css';
 *
 * @Component({
 *   imports: [RkReelPlayerUrlOverlayComponent, RouterLink],
 *   template: `
 *     @for (post of content; track post.id; let i = $index) {
 *       <a [routerLink]="[]" [queryParams]="{ reel: i }">{{ post.id }}</a>
 *     }
 *     <rk-reel-player-url-overlay [controller]="reel" [content]="content" />
 *   `,
 * })
 * export class FeedComponent {
 *   content: ContentItem[] = [...];
 *   protected readonly reel = createOverlayUrlState({
 *     param: 'reel',
 *     adapter: createRouterUrlAdapter(),
 *     ...urlIndexKey(() => this.content.length),
 *   });
 * }
 * ```
 */

export { RkReelPlayerOverlayComponent } from './lib/reel-player-overlay/reel-player-overlay.component';
export { RkReelPlayerUrlOverlayComponent } from './lib/reel-player-overlay/reel-player-url-overlay.component';

export type {
  UrlAdapter,
  UrlCodec,
  UrlLocator,
  TwoAxisPosition,
} from '@reelkit/angular';
export { urlIndexTwoAxisKey } from '@reelkit/angular';

export type {
  MediaType,
  MediaItem,
  BaseContentItem,
  ContentItem,
  PlayerSlideContext,
  PlayerSlideOverlayContext,
  PlayerControlsContext,
  PlayerSoundState,
  PlayerTimelineState,
  PlayerTimelineContext,
  PlayerBufferedRange,
  PlayerNavigationContext,
  PlayerNestedSlideContext,
  PlayerNestedNavigationContext,
  TimelineMode,
} from './lib/types';

export {
  RkPlayerSlideDirective,
  RkPlayerSlideOverlayDirective,
  RkPlayerControlsDirective,
  RkPlayerTimelineDirective,
  RkPlayerNavigationDirective,
  RkPlayerNestedSlideDirective,
  RkPlayerNestedNavigationDirective,
  RkPlayerLoadingDirective,
  RkPlayerErrorDirective,
  PLAYER_TEMPLATE_SLOT_DIRECTIVES,
  type PlayerLoadingContext,
  type PlayerErrorContext,
} from './lib/template-slots/player-template-slots';

export { RkCloseButtonComponent } from './lib/player-controls/close-button.component';
export { RkSoundButtonComponent } from './lib/player-controls/sound-button.component';

export { RkImageSlideComponent } from './lib/image-slide/image-slide.component';
export { RkVideoSlideComponent } from './lib/video-slide/video-slide.component';
export { RkSlideOverlayComponent } from './lib/slide-overlay/slide-overlay.component';
export { RkMediaSlideComponent } from './lib/media-slide/media-slide.component';
export { RkNestedSliderComponent } from './lib/nested-slider/nested-slider.component';

export { SoundStateService } from './lib/sound-state/sound-state.service';
export { TimelineStateService } from './lib/timeline-state/timeline-state.service';
export { RkTimelineBarComponent } from './lib/timeline-bar/timeline-bar.component';

// packages/reelkit-react-reel-player/src/index.ts
/**
 * @module @reelkit/react-reel-player
 *
 * Full-screen, Instagram/TikTok-style vertical reel player overlay for React.
 *
 * The main entry point is {@link ReelPlayerOverlay}: a generic, customizable
 * component that renders a virtualized vertical slider with media playback,
 * gesture/keyboard/wheel navigation, and optional sound controls.
 *
 * Customization is achieved via render props:
 * - `renderSlideOverlay`: custom per-slide overlays
 * - `renderSlide`: fully custom slide content
 * - `renderControls`: custom player controls (compose with {@link CloseButton}, {@link SoundButton})
 * - `renderNavigation`: custom navigation arrows
 * - `renderNestedNavigation`: custom arrows for the inner horizontal slider (multi-media posts)
 *
 * For custom data types, extend {@link BaseContentItem} and pass as a
 * type parameter: `<ReelPlayerOverlay<MyItem> />`.
 *
 * Open state comes in two shapes. {@link ReelPlayerOverlay} is controlled — the
 * surrounding component owns `isOpen`. {@link ReelPlayerUrlOverlay} puts it in
 * the address bar instead, so the playing slide has a link that can be shared,
 * bookmarked, and closed with the back button. Every render prop above works
 * the same in either.
 *
 * @example Controlled — the component owns `isOpen`
 * ```tsx
 * import { useState } from 'react';
 * import { ReelPlayerOverlay, type ContentItem } from '@reelkit/react-reel-player';
 * import '@reelkit/react-reel-player/styles.css';
 *
 * const content: ContentItem[] = [
 *   {
 *     id: '1',
 *     media: [{ id: 'v1', type: 'video', src: '/video.mp4', aspectRatio: 9 / 16 }],
 *     author: { name: 'John', avatar: '/avatar.jpg' },
 *     likes: 1234,
 *     description: 'Amazing video!',
 *   },
 * ];
 *
 * function App() {
 *   const [isOpen, setIsOpen] = useState(false);
 *   return (
 *     <>
 *       <button onClick={() => setIsOpen(true)}>Open Player</button>
 *       <ReelPlayerOverlay
 *         isOpen={isOpen}
 *         onClose={() => setIsOpen(false)}
 *         content={content}
 *       />
 *     </>
 *   );
 * }
 * ```
 *
 * @example URL-driven — opening is a link, back closes
 * ```tsx
 * import { useOverlayUrlState, urlIndexKey } from '@reelkit/react';
 * import { ReelPlayerUrlOverlay } from '@reelkit/react-reel-player';
 * import { Link } from 'react-router-dom';
 *
 * function Feed() {
 *   const reel = useOverlayUrlState({
 *     param: 'reel',
 *     ...urlIndexKey(() => content.length),
 *   });
 *
 *   return (
 *     <>
 *       {content.map((item, i) => (
 *         <Link key={item.id} to={`?reel=${i}`}>
 *           <img src={getThumbnail(item)} />
 *         </Link>
 *       ))}
 *
 *       <ReelPlayerUrlOverlay controller={reel} content={content} />
 *     </>
 *   );
 * }
 * ```
 */

export {
  ReelPlayerOverlay,
  ReelPlayerUrlOverlay,
} from './lib/ReelPlayerOverlay';
export type {
  ReelPlayerOverlayBaseProps,
  ReelPlayerControlledProps,
  ReelPlayerUrlControlledProps,
  ReelPlayerOverlayProps,
  ReelPlayerUrlOverlayProps,
  ReelProxyProps,
} from './lib/ReelPlayerOverlay';

export type {
  UrlAdapter,
  UrlCodec,
  UrlLocator,
  TwoAxisPosition,
} from '@reelkit/react';
export { urlIndexTwoAxisKey } from '@reelkit/react';

export type {
  MediaType,
  MediaItem,
  BaseContentItem,
  ContentItem,
  ControlsRenderProps,
  NavigationRenderProps,
  SlideRenderProps,
  NestedSlideRenderProps,
  TimelineMode,
  TimelineRenderProps,
} from './lib/types';

export { CloseButton, SoundButton } from './lib/PlayerControls';
export type { CloseButtonProps, SoundButtonProps } from './lib/PlayerControls';

export { default as ImageSlide } from './lib/ImageSlide';
export type { ImageSlideProps } from './lib/ImageSlide';

export { default as VideoSlide } from './lib/VideoSlide';
export type { VideoSlideProps } from './lib/VideoSlide';

export { default as SlideOverlay } from './lib/SlideOverlay';
export type { SlideOverlayProps } from './lib/SlideOverlay';

export {
  TimelineProvider,
  useTimelineState,
  useTimelineStateOptional,
} from './lib/TimelineState';
export {
  default as TimelineBar,
  type TimelineBarProps,
} from './lib/TimelineBar';
