// packages/reelkit-react/src/lib/components/ReelIndicator.tsx
import * as React from 'react';
import { clamp } from '@reelkit/core';

export type ReelIndicatorDirection = 'horizontal' | 'vertical';

export interface ReelIndicatorProps {
  /** Total number of items */
  count: number;
  /** Current active index */
  active: number;
  /** Direction of the indicator */
  direction?: ReelIndicatorDirection;
  /** Dot radius in pixels */
  radius?: number;
  /** Number of normal-sized visible dots */
  visible?: number;
  /** Gap between dots */
  gap?: number;
  /** Active dot color */
  activeColor?: string;
  /** Inactive dot color */
  inactiveColor?: string;
  /** Scale for edge dots (0-1) */
  edgeScale?: number;
  className?: string;
  style?: React.CSSProperties;
  onDotClick?: (index: number) => void;
}

/**
 * Instagram-style indicator with scrolling dots.
 * - Shows `visible` normal-sized dots
 * - Adds 1 small dot at start if there are more items before
 * - Adds 1 small dot at end if there are more items after
 * - Slides when navigating to edge dots with smooth animation
 */
const Element: React.FC<ReelIndicatorProps> = (props) => {
  const {
    count,
    active,
    direction = 'vertical',
    visible = 5,
    radius = 3,
    gap = 4,
    activeColor = '#fff',
    inactiveColor = 'rgba(255, 255, 255, 0.5)',
    edgeScale = 0.5,
    className,
    style,
    onDotClick,
  } = props;

  const isVertical = direction === 'vertical';
  const dotSize = radius * 2;
  const itemSize = dotSize + gap;

  // Window start index - the first normal-sized dot
  const [windowStart, setWindowStart] = React.useState(() => {
    if (count <= visible) return 0;
    // Initially position so active is visible
    return clamp(active - Math.floor(visible / 2), 0, count - visible);
  });

  // Update window when active changes
  React.useEffect(() => {
    if (count <= visible) {
      setWindowStart(0);
      return;
    }

    setWindowStart((prev) => {
      // If active is before the window (on the small leading dot)
      if (active < prev) {
        // Slide window left to make active the first normal dot
        return Math.max(0, active);
      }
      // If active is after the window (on the small trailing dot)
      if (active >= prev + visible) {
        // Slide window right to make active the last normal dot
        return Math.min(count - visible, active - visible + 1);
      }
      return prev;
    });
  }, [active, count, visible]);

  const windowEnd = Math.min(windowStart + visible, count);
  const hasLeadingSmall = windowStart > 0;
  const hasTrailingSmall = windowEnd < count;

  // Calculate container size - fixed size with space for both edge dots
  const normalDotsCount = Math.min(visible, count);
  let containerSize = normalDotsCount * itemSize;
  if (count > visible) {
    // Always reserve space for both edge dots to prevent size jumping
    containerSize += itemSize * 2;
  }

  // Build the dots array with absolute positioning for smooth sliding
  const dots = React.useMemo(() => {
    const result: React.ReactNode[] = [];

    // Render from (windowStart - 1) to (windowEnd + 1) to ensure smooth transitions
    const renderStart = Math.max(0, windowStart - 1);
    const renderEnd = Math.min(count, windowEnd + 1);

    for (let i = renderStart; i < renderEnd; i++) {
      const isActive = i === active;

      // Determine dot scale based on position relative to window
      let scale = 1;
      if (i < windowStart) {
        scale = edgeScale;
      } else if (i >= windowEnd) {
        scale = edgeScale;
      }

      // Calculate slot index for this dot
      let slotIndex: number;
      if (i < windowStart) {
        // Leading edge dot - always slot 0
        slotIndex = 0;
      } else if (i >= windowEnd) {
        // Trailing edge dot - last slot
        slotIndex = visible + 1;
      } else {
        // Visible dot - slots 1 to visible
        slotIndex = (i - windowStart) + 1;
      }

      // If no leading small, shift all visible and trailing left by 1
      if (!hasLeadingSmall && slotIndex > 0) {
        slotIndex -= 1;
      }

      const position = slotIndex * itemSize;

      result.push(
        <span
          key={i}
          data-reel-indicator={i}
          style={{
            position: 'absolute',
            [isVertical ? 'top' : 'left']: position,
            [isVertical ? 'left' : 'top']: 0,
            width: itemSize,
            height: itemSize,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            transition: 'top 0.2s ease, left 0.2s ease',
          }}
          onClick={onDotClick ? () => onDotClick(i) : undefined}
          data-testid={`indicator-dot-${i}`}
        >
          <span
            style={{
              width: dotSize,
              height: dotSize,
              borderRadius: '50%',
              backgroundColor: isActive ? activeColor : inactiveColor,
              transition: 'transform 0.2s ease, background-color 0.2s ease',
              transform: `scale(${scale})`,
              cursor: onDotClick ? 'pointer' : 'default',
            }}
          />
        </span>
      );
    }

    return result;
  }, [
    windowStart,
    windowEnd,
    hasLeadingSmall,
    visible,
    count,
    active,
    dotSize,
    itemSize,
    edgeScale,
    activeColor,
    inactiveColor,
    isVertical,
    onDotClick,
  ]);

  return (
    <div
      className={className}
      style={{
        position: 'relative',
        overflow: 'hidden',
        [isVertical ? 'height' : 'width']: containerSize,
        [isVertical ? 'width' : 'height']: itemSize,
        ...style,
      }}
    >
      {dots}
    </div>
  );
};

export const ReelIndicator = React.memo(Element);

export default ReelIndicator;

// packages/reelkit-wc/src/lib/ReelIndicator.ts
import { clamp, type SliderDirection } from '@reelkit/core';

/**
 * Web Component for Instagram-style indicator with scrolling dots.
 *
 * @example
 * ```html
 * <reel-indicator
 *   count="100"
 *   active-index="0"
 *   direction="vertical"
 *   visible="5"
 * ></reel-indicator>
 * ```
 *
 * @fires reel-indicator-click - Fired when a dot is clicked, detail: { index: number }
 */
export class ReelIndicator extends HTMLElement {
  static get observedAttributes() {
    return [
      'count',
      'active-index',
      'direction',
      'visible',
      'radius',
      'gap',
      'edge-scale',
      'active-color',
      'inactive-color',
    ];
  }

  private windowStart = 0;
  private initialized = false;
  private boundClickHandler: ((e: Event) => void) | null = null;

  constructor() {
    super();
  }

  connectedCallback() {
    if (!this.initialized) {
      this.initialize();
    }
  }

  disconnectedCallback() {
    this.cleanup();
  }

  attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
    if (oldValue === newValue) return;

    if (this.initialized) {
      if (name === 'active-index') {
        this.updateWindowStart();
      }
      this.render();
    }
  }

  private initialize() {
    this.updateWindowStart();
    this.setupContainer();
    this.setupClickHandler();
    this.render();
    this.initialized = true;
  }

  private cleanup() {
    if (this.boundClickHandler) {
      this.removeEventListener('click', this.boundClickHandler);
      this.boundClickHandler = null;
    }
    this.innerHTML = '';
    this.initialized = false;
  }

  private setupContainer() {
    const isVertical = this.direction === 'vertical';
    const dotSize = this.radius * 2;
    const itemSize = dotSize + this.gap;

    const normalDotsCount = Math.min(this.visible, this.count);
    let containerSize = normalDotsCount * itemSize;
    if (this.count > this.visible) {
      containerSize += itemSize * 2;
    }

    this.style.display = 'block';
    this.style.position = 'relative';
    this.style.overflow = 'hidden';

    if (isVertical) {
      this.style.height = `${containerSize}px`;
      this.style.width = `${itemSize}px`;
    } else {
      this.style.width = `${containerSize}px`;
      this.style.height = `${itemSize}px`;
    }
  }

  private setupClickHandler() {
    this.boundClickHandler = (e: Event) => {
      let target = e.target as HTMLElement;

      let indexAttr = target.getAttribute('data-reel-indicator');
      if (indexAttr === null && target.parentElement) {
        indexAttr = target.parentElement.getAttribute('data-reel-indicator');
      }

      if (indexAttr !== null) {
        const index = parseInt(indexAttr, 10);
        this.dispatchEvent(
          new CustomEvent('reel-indicator-click', {
            detail: { index },
            bubbles: true,
          })
        );
      }
    };

    this.addEventListener('click', this.boundClickHandler);
  }

  private updateWindowStart() {
    if (this.count <= this.visible) {
      this.windowStart = 0;
      return;
    }

    const activeIndex = this.activeIndex;

    if (activeIndex < this.windowStart) {
      this.windowStart = Math.max(0, activeIndex);
      return;
    }

    if (activeIndex >= this.windowStart + this.visible) {
      this.windowStart = Math.min(
        this.count - this.visible,
        activeIndex - this.visible + 1
      );
    }
  }

  private render() {
    const isVertical = this.direction === 'vertical';
    const dotSize = this.radius * 2;
    const itemSize = dotSize + this.gap;
    const activeIndex = this.activeIndex;

    const windowEnd = Math.min(this.windowStart + this.visible, this.count);
    const hasLeadingSmall = this.windowStart > 0;

    const renderStart = Math.max(0, this.windowStart - 1);
    const renderEnd = Math.min(this.count, windowEnd + 1);

    this.innerHTML = '';

    for (let i = renderStart; i < renderEnd; i++) {
      const isActive = i === activeIndex;

      let scale = 1;
      if (i < this.windowStart) {
        scale = this.edgeScale;
      } else if (i >= windowEnd) {
        scale = this.edgeScale;
      }

      let slotIndex: number;
      if (i < this.windowStart) {
        slotIndex = 0;
      } else if (i >= windowEnd) {
        slotIndex = this.visible + 1;
      } else {
        slotIndex = i - this.windowStart + 1;
      }

      if (!hasLeadingSmall && slotIndex > 0) {
        slotIndex -= 1;
      }

      const position = slotIndex * itemSize;

      const wrapper = document.createElement('span');
      wrapper.setAttribute('data-reel-indicator', String(i));
      wrapper.style.position = 'absolute';
      wrapper.style.display = 'flex';
      wrapper.style.justifyContent = 'center';
      wrapper.style.alignItems = 'center';
      wrapper.style.width = `${itemSize}px`;
      wrapper.style.height = `${itemSize}px`;
      wrapper.style.transition = 'top 0.2s ease, left 0.2s ease';
      wrapper.style.cursor = 'pointer';

      if (isVertical) {
        wrapper.style.top = `${position}px`;
        wrapper.style.left = '0';
      } else {
        wrapper.style.left = `${position}px`;
        wrapper.style.top = '0';
      }

      const dot = document.createElement('span');
      dot.style.width = `${dotSize}px`;
      dot.style.height = `${dotSize}px`;
      dot.style.borderRadius = '50%';
      dot.style.transition = 'transform 0.2s ease, background-color 0.2s ease';
      dot.style.flexShrink = '0';
      dot.style.backgroundColor = isActive ? this.activeColor : this.inactiveColor;
      dot.style.transform = `scale(${scale})`;

      wrapper.appendChild(dot);
      this.appendChild(wrapper);
    }
  }

  // Attribute getters/setters

  get count(): number {
    return parseInt(this.getAttribute('count') || '0', 10);
  }

  set count(value: number) {
    this.setAttribute('count', String(value));
  }

  get activeIndex(): number {
    return parseInt(this.getAttribute('active-index') || '0', 10);
  }

  set activeIndex(value: number) {
    this.setAttribute('active-index', String(value));
  }

  get direction(): SliderDirection {
    return (this.getAttribute('direction') as SliderDirection) || 'vertical';
  }

  set direction(value: SliderDirection) {
    this.setAttribute('direction', value);
  }

  get visible(): number {
    return parseInt(this.getAttribute('visible') || '5', 10);
  }

  set visible(value: number) {
    this.setAttribute('visible', String(value));
  }

  get radius(): number {
    return parseInt(this.getAttribute('radius') || '3', 10);
  }

  set radius(value: number) {
    this.setAttribute('radius', String(value));
  }

  get gap(): number {
    return parseInt(this.getAttribute('gap') || '4', 10);
  }

  set gap(value: number) {
    this.setAttribute('gap', String(value));
  }

  get edgeScale(): number {
    return parseFloat(this.getAttribute('edge-scale') || '0.5');
  }

  set edgeScale(value: number) {
    this.setAttribute('edge-scale', String(value));
  }

  get activeColor(): string {
    return this.getAttribute('active-color') || '#fff';
  }

  set activeColor(value: string) {
    this.setAttribute('active-color', value);
  }

  get inactiveColor(): string {
    return this.getAttribute('inactive-color') || 'rgba(255, 255, 255, 0.5)';
  }

  set inactiveColor(value: string) {
    this.setAttribute('inactive-color', value);
  }

  // Public API

  /** Set the active dot index */
  setActive(index: number): void {
    if (index < 0 || index >= this.count) return;
    this.activeIndex = index;
  }
}

// Register the custom element
if (typeof customElements !== 'undefined' && !customElements.get('reel-indicator')) {
  customElements.define('reel-indicator', ReelIndicator);
}
