// packages/reelkit-react-stories-player/src/index.ts
/**
 * @module @reelkit/react-stories-player
 *
 * Instagram-style stories player overlay for React. Full-screen vertical
 * content viewer with two-axis navigation: tap left/right to advance within
 * a user's stories, swipe left/right with a 3D flip transition to switch
 * between users.
 *
 * The main component is {@link StoriesOverlay}. Entry-point components
 * {@link StoriesRing} and {@link StoriesRingList} render the circular
 * avatar rings that open the overlay.
 *
 * Open state comes in two shapes. {@link StoriesOverlay} is controlled — the
 * surrounding component owns `isOpen`. {@link StoriesUrlOverlay} puts it in the
 * address bar instead: the open group and story ride one `?story=<group>.<story>`
 * parameter, so the playing story has a link that can be shared, bookmarked, and
 * closed with the back button. Inner navigation is carried too — swiping between
 * a user's stories updates the URL — and one back step always closes.
 *
 * @example Controlled — the component owns `isOpen`
 * ```tsx
 * import { StoriesOverlay } from '@reelkit/react-stories-player';
 * import '@reelkit/react-stories-player/styles.css';
 *
 * function Feed({ groups }) {
 *   const [open, setOpen] = useState(false);
 *   return (
 *     <>
 *       <button onClick={() => setOpen(true)}>Open stories</button>
 *       <StoriesOverlay isOpen={open} groups={groups} onClose={() => setOpen(false)} />
 *     </>
 *   );
 * }
 * ```
 *
 * @example URL-driven — opening is a link, back closes
 * ```tsx
 * import {
 *   StoriesUrlOverlay,
 *   StoriesRingList,
 *   useOverlayUrlState,
 *   urlIndexTwoAxisKey,
 * } from '@reelkit/react-stories-player';
 * import { Link } from 'react-router-dom';
 * import '@reelkit/react-stories-player/styles.css';
 *
 * function Feed({ groups }) {
 *   // Outer axis is the group, inner is the story within it.
 *   const stories = useOverlayUrlState({
 *     param: 'story',
 *     ...urlIndexTwoAxisKey({
 *       outerCount: () => groups.length,
 *       innerCounts: () => groups.map((g) => g.stories.length),
 *     }),
 *   });
 *
 *   return (
 *     <>
 *       {groups.map((g, i) => (
 *         <Link key={g.author.id} to={`?story=${i}.0`}>{g.author.name}</Link>
 *       ))}
 *       <StoriesUrlOverlay controller={stories} groups={groups} />
 *     </>
 *   );
 * }
 * ```
 */

export {
  StoriesOverlay,
  StoriesUrlOverlay,
  type StoriesOverlayProps,
  type StoriesUrlOverlayProps,
} from './lib/StoriesOverlay';
export { StoriesRing } from './lib/StoriesRing';
export { StoriesRingList } from './lib/StoriesRingList';
export { CanvasProgressBar } from './lib/CanvasProgressBar';
export { StoryHeader } from './lib/StoryHeader';
export { HeartAnimation } from './lib/HeartAnimation';
export { ImageStorySlide } from './lib/ImageStorySlide';
export { VideoStorySlide } from './lib/VideoStorySlide';
export { SoundProvider, useSoundState } from '@reelkit/react';

export {
  createStoriesViewedStateController,
  type StoriesViewedStateController,
  type StoriesViewedStateControllerConfig,
} from '@reelkit/stories-core';

export {
  useOverlayUrlState,
  createViewedStateController,
  twoAxisViewedTracking,
  createLocalStorageAdapter,
  createSessionStorageAdapter,
  createMemoryStorageAdapter,
  urlIndexTwoAxisKey,
  urlStableIdTwoAxisKey,
  base64UrlCodec,
  type UrlAdapter,
  type UrlCodec,
  type UrlLocator,
  type UrlKey,
  type UrlStateController,
  type TwoAxisPosition,
  type TwoAxisIdentity,
  type UrlIndexTwoAxisKeyOptions,
  type ViewedStateController,
  type ViewedStateOptions,
  type StorageAdapter,
} from '@reelkit/react';

export type {
  StoryItem,
  AuthorInfo,
  StoriesGroup,
  MediaType,
  HeaderRenderProps,
  FooterRenderProps,
  SlideRenderProps,
  NavigationRenderProps,
  ProgressBarRenderProps,
  LoadingRenderProps,
  ErrorRenderProps,
  DesktopLayout,
  ChromePlacement,
  GroupPreviewRenderProps,
  StoriesApi,
} from './lib/types';

// packages/reelkit-angular-stories-player/src/index.ts
/**
 * @module @reelkit/angular-stories-player
 *
 * Instagram-style stories overlay for Angular: tap to move through a group,
 * swipe or a cube transition to move between groups, and an auto-advance
 * timer driving a canvas progress bar.
 *
 * The package is the third binding on `@reelkit/stories-core`, alongside
 * `@reelkit/react-stories-player` and `@reelkit/vue-stories-player`. All
 * three share the same engine, so a behavioural difference between them is a
 * bug rather than a matter of framework taste.
 *
 * Open state comes in two shapes. {@link RkStoriesOverlayComponent} is
 * controlled — the surrounding component owns `isOpen`.
 * {@link RkStoriesUrlOverlayComponent} puts the open group and story in the
 * address bar instead, so the playing story has a link that can be shared,
 * bookmarked, and closed with the back button.
 *
 * @example Controlled — the component owns `isOpen`
 * ```ts
 * import { Component, signal } from '@angular/core';
 * import {
 *   RkStoriesOverlayComponent,
 *   RkStoriesRingListComponent,
 *   type StoriesGroup,
 * } from '@reelkit/angular-stories-player';
 * import '@reelkit/angular-stories-player/styles.css';
 *
 * @Component({
 *   imports: [RkStoriesOverlayComponent, RkStoriesRingListComponent],
 *   template: `
 *     <rk-stories-ring-list [groups]="groups" (selected)="open($event)" />
 *     <rk-stories-overlay
 *       [isOpen]="isOpen()"
 *       [groups]="groups"
 *       [initialGroupIndex]="groupIndex()"
 *       (closed)="isOpen.set(false)"
 *     />
 *   `,
 * })
 * export class FeedComponent {
 *   protected readonly groups: StoriesGroup[] = [
 *     {
 *       author: { id: 'alice', name: 'Alice', avatar: '/alice.jpg' },
 *       stories: [{ id: 's1', mediaType: 'image', src: '/story-1.jpg' }],
 *     },
 *   ];
 *
 *   protected readonly isOpen = signal(false);
 *   protected readonly groupIndex = signal(0);
 *
 *   protected open(index: number): void {
 *     this.groupIndex.set(index);
 *     this.isOpen.set(true);
 *   }
 * }
 * ```
 *
 * @example URL-driven — opening is a link, back closes
 * ```ts
 * import { Component, inject, Injector, runInInjectionContext, type OnInit } from '@angular/core';
 * import {
 *   RkStoriesUrlOverlayComponent,
 *   type StoriesGroup,
 * } from '@reelkit/angular-stories-player';
 * import {
 *   createOverlayUrlState,
 *   urlIndexTwoAxisKey,
 *   type TwoAxisPosition,
 *   type UrlStateController,
 * } from '@reelkit/angular';
 * import { createRouterUrlAdapter } from '@reelkit/angular/ng-router-url-adapter';
 *
 * @Component({
 *   imports: [RkStoriesUrlOverlayComponent],
 *   template: `<rk-stories-url-overlay [controller]="stories" [groups]="groups" />`,
 * })
 * export class FeedComponent implements OnInit {
 *   private readonly injector = inject(Injector);
 *
 *   protected groups: StoriesGroup[] = [];
 *   protected stories!: UrlStateController<TwoAxisPosition>;
 *
 *   // Both the controller and the router adapter need an injection context,
 *   // and ngOnInit does not run in one, so borrow the component's.
 *   ngOnInit(): void {
 *     this.stories = runInInjectionContext(this.injector, () =>
 *       createOverlayUrlState({
 *         param: 'story',
 *         adapter: createRouterUrlAdapter(),
 *         ...urlIndexTwoAxisKey({
 *           outerCount: () => this.groups.length,
 *           innerCounts: () => this.groups.map((group) => group.stories.length),
 *         }),
 *       }),
 *     ) as UrlStateController<TwoAxisPosition>;
 *   }
 * }
 * ```
 */

export { RkStoriesOverlayComponent } from './lib/stories-overlay/stories-overlay.component';
export { RkStoriesUrlOverlayComponent } from './lib/stories-overlay/stories-url-overlay.component';
export {
  RkStoriesCarouselComponent,
  type CarouselSlide,
} from './lib/stories-carousel/stories-carousel.component';

export {
  RkStoriesSlideDirective,
  RkStoriesHeaderDirective,
  RkStoriesFooterDirective,
  RkStoriesProgressBarDirective,
  RkStoriesNavigationDirective,
  RkStoriesGroupPreviewDirective,
  RkStoriesLoadingDirective,
  RkStoriesErrorDirective,
  STORIES_TEMPLATE_SLOT_DIRECTIVES,
} from './lib/template-slots/stories-template-slots';

export { RkStoriesRingComponent } from './lib/stories-ring/stories-ring.component';
export { RkStoriesRingListComponent } from './lib/stories-ring-list/stories-ring-list.component';
export { RkStoryHeaderComponent } from './lib/story-header/story-header.component';
export { RkHeartAnimationComponent } from './lib/heart-animation/heart-animation.component';
export { RkCanvasProgressBarComponent } from './lib/canvas-progress-bar/canvas-progress-bar.component';
export { RkImageStorySlideComponent } from './lib/image-story-slide/image-story-slide.component';
export { RkVideoStorySlideComponent } from './lib/video-story-slide/video-story-slide.component';
export { attachViewedState } from './lib/viewed-state/attach-viewed-state';

export type {
  StoryItem,
  AuthorInfo,
  StoriesGroup,
  MediaType,
  StoriesHeaderContext,
  StoriesFooterContext,
  StoriesSlideContext,
  StoriesProgressBarContext,
  StoriesNavigationActions,
  StoriesNavigationContext,
  StoriesLoadingContext,
  StoriesErrorContext,
  StoriesGroupPreviewContext,
  DesktopLayout,
  ChromePlacement,
  StoriesApi,
} from './lib/types';

export {
  createStoriesViewedStateController,
  type StoriesViewedStateController,
  type StoriesViewedStateControllerConfig,
} from '@reelkit/stories-core';

export {
  createOverlayUrlState,
  urlIndexTwoAxisKey,
  urlStableIdTwoAxisKey,
  base64UrlCodec,
  createViewedStateController,
  twoAxisViewedTracking,
  createLocalStorageAdapter,
  createSessionStorageAdapter,
  createMemoryStorageAdapter,
  type OverlayUrlStateOptions,
  type UrlAdapter,
  type UrlCodec,
  type UrlLocator,
  type UrlKey,
  type UrlStateController,
  type TwoAxisPosition,
  type TwoAxisIdentity,
  type UrlIndexTwoAxisKeyOptions,
  type ViewedStateController,
  type ViewedStateOptions,
  type StorageAdapter,
} from '@reelkit/angular';
