// packages/reelkit-react-reel-player/src/lib/MediaSlide.tsx
import React, { type ReactNode } from 'react';
import type { ReelApi } from '@reelkit/react';
import type {
  BaseContentItem,
  NavigationRenderProps,
  NestedSlideRenderProps,
} from './types';
import ImageSlide from './ImageSlide';
import VideoSlide from './VideoSlide';
import NestedSlider from './NestedSlider';

/** @internal */
interface MediaSlideProps {
  content: BaseContentItem;
  isActive: boolean;
  size: [number, number];
  innerSliderRef: React.MutableRefObject<ReelApi | null>;
  enableWheel?: boolean;
  onVideoRef?: (ref: HTMLVideoElement | null) => void;
  onActiveMediaTypeChange?: (type: 'image' | 'video') => void;
  renderNestedNavigation?: (props: NavigationRenderProps) => ReactNode;
  renderNestedSlide?: (props: NestedSlideRenderProps) => ReactNode;
}

/**
 * Renders the appropriate media component based on the content item's media array.
 *
 * - Single image → {@link ImageSlide}
 * - Single video → {@link VideoSlide}
 * - Multiple items → {@link NestedSlider} (horizontal carousel within the vertical slide)
 *
 * @internal Used by `ReelPlayerContent` as the default slide renderer.
 */
const MediaSlide: React.FC<MediaSlideProps> = ({
  content,
  isActive,
  size,
  innerSliderRef,
  enableWheel,
  onVideoRef,
  onActiveMediaTypeChange,
  renderNestedNavigation,
  renderNestedSlide,
}) => {
  const { media } = content;

  // Single image
  if (media.length === 1 && media[0].type === 'image') {
    return <ImageSlide src={media[0].src} size={size} />;
  }

  // Single video
  if (media.length === 1 && media[0].type === 'video') {
    return (
      <VideoSlide
        src={media[0].src}
        poster={media[0].poster}
        aspectRatio={media[0].aspectRatio}
        size={size}
        isActive={isActive}
        slideKey={content.id}
        onVideoRef={onVideoRef}
      />
    );
  }

  // Multiple media items - use nested slider
  return (
    <NestedSlider
      media={media}
      isParentActive={isActive}
      size={size}
      contentId={content.id}
      innerSliderRef={innerSliderRef}
      enableWheel={enableWheel}
      onVideoRef={onVideoRef}
      onActiveMediaTypeChange={onActiveMediaTypeChange}
      renderNavigation={renderNestedNavigation}
      renderNestedSlide={renderNestedSlide}
    />
  );
};

export default MediaSlide;

// packages/reelkit-angular-reel-player/src/lib/media-slide/media-slide.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  TemplateRef,
  ViewEncapsulation,
  input,
  output,
  viewChild,
} from '@angular/core';
import { type ReelApi } from '@reelkit/angular';
import { RkImageSlideComponent } from '../image-slide/image-slide.component';
import { RkVideoSlideComponent } from '../video-slide/video-slide.component';
import { RkNestedSliderComponent } from '../nested-slider/nested-slider.component';
import type {
  BaseContentItem,
  MediaType,
  PlayerNestedNavigationContext,
  PlayerNestedSlideContext,
} from '../types';

/**
 * Dispatches to the appropriate slide component based on the content item's
 * media array:
 *
 * - Single image  → `rk-image-slide`
 * - Single video  → `rk-video-slide`
 * - Multiple items → `rk-nested-slider` (horizontal carousel)
 *
 * @internal Used by `RkReelPlayerOverlayComponent` as the default slide renderer.
 */
@Component({
  selector: 'rk-media-slide',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { style: 'display:block;width:100%;height:100%' },
  imports: [
    RkImageSlideComponent,
    RkVideoSlideComponent,
    RkNestedSliderComponent,
  ],
  styles: [
    `
      .rk-media-slide-empty {
        background-color: #000;
        display: block;
      }
    `,
  ],
  template: `
    @let m = content().media;

    @if (m.length === 0) {
      <div
        class="rk-media-slide-empty"
        [style.width.px]="width()"
        [style.height.px]="height()"
        aria-hidden="true"
      ></div>
    } @else if (m.length === 1 && m[0].type === 'image') {
      <rk-image-slide
        [src]="m[0].src"
        [poster]="m[0].poster"
        [width]="width()"
        [height]="height()"
        [isActive]="isActive()"
      />
    } @else if (m.length === 1 && m[0].type === 'video') {
      <rk-video-slide
        [src]="m[0].src"
        [poster]="m[0].poster"
        [aspectRatio]="m[0].aspectRatio"
        [width]="width()"
        [height]="height()"
        [isActive]="isActive()"
        [slideKey]="content().id"
        (videoRef)="videoRef.emit($event)"
      />
    } @else {
      <rk-nested-slider
        [media]="m"
        [isActive]="isActive()"
        [width]="width()"
        [height]="height()"
        [slideKey]="content().id"
        [enableWheel]="enableWheel()"
        [nestedSlideTemplate]="nestedSlideTemplate()"
        [nestedNavTemplate]="nestedNavTemplate()"
        (videoRef)="videoRef.emit($event)"
        (innerMediaType)="innerMediaType.emit($event)"
        (innerApiReady)="innerApiReady.emit($event)"
      />
    }
  `,
})
export class RkMediaSlideComponent {
  readonly content = input.required<BaseContentItem>();
  readonly isActive = input<boolean>(false);
  readonly width = input<number>(0);
  readonly height = input<number>(0);
  readonly enableWheel = input<boolean>(false);
  readonly nestedSlideTemplate =
    input<TemplateRef<PlayerNestedSlideContext> | null>(null);
  readonly nestedNavTemplate =
    input<TemplateRef<PlayerNestedNavigationContext> | null>(null);

  readonly videoRef = output<HTMLVideoElement | null>();
  readonly innerMediaType = output<MediaType>();
  readonly innerApiReady = output<ReelApi>();

  readonly nestedSlider = viewChild(RkNestedSliderComponent);
}
