// packages/reelkit-react-stories-player/src/lib/VideoStorySlide.tsx
/* eslint-disable react-hooks/exhaustive-deps */
import { type FC, useRef, useState, useEffect } from 'react';
import {
  createSharedVideo,
  createSignal,
  createDisposableList,
  observeDomEvent,
  observeMediaLoading,
  syncMutedToVideo,
  reaction,
  captureFrame,
  noop,
  Observe,
  useSoundState,
  type Signal,
} from '@reelkit/react';

/** Props for the {@link VideoStorySlide} component. */
export interface VideoStorySlideProps {
  /** Loaded only while this slide is the active one. */
  src: string;

  /** Shown until playback starts. A frame captured from an earlier play wins. */
  poster?: string;

  /** Where this slide sits. Matched against the two signals below. */
  groupIndex: number;

  /** Where this slide sits. Matched against the two signals below. */
  storyIndex: number;

  /** Both signals equal to the pair above means this slide owns the video. */
  activeGroupIndex: Signal<number>;

  /** Both signals equal to the pair above means this slide owns the video. */
  activeStoryIndex: Signal<number>;

  /** Called when video metadata loads, reporting duration in milliseconds. */
  onDurationReady?: (ms: number) => void;

  /** Called when the video starts playing (buffering complete). */
  onPlaying?: () => void;

  /** Called when the video stalls (buffering mid-playback). */
  onWaiting?: () => void;

  /** The story is over; the player moves on rather than waiting for the timer. */
  onEnded?: () => void;

  /** Covers a source that will not load and a play() the browser refused. */
  onError?: () => void;
}

export const shared = createSharedVideo({
  className: 'rk-stories-video-element',
  disableRemotePlayback: true,
  disablePictureInPicture: true,
});

/**
 * Renders a single video story slide using a shared `<video>` element
 * for iOS sound continuity across slide changes.
 *
 * Determines active state directly from controller signals via
 * `reaction`, bypassing React re-render timing. The shared element
 * is moved into the active slide's container and removed on deactivation.
 */
export const VideoStorySlide: FC<VideoStorySlideProps> = ({
  src,
  poster,
  groupIndex,
  storyIndex,
  activeGroupIndex,
  activeStoryIndex,
  onDurationReady,
  onPlaying,
  onWaiting,
  onEnded,
  onError,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const soundState = useSoundState();
  const [showPoster] = useState(() => createSignal(true));
  const resolvedPoster = shared.capturedFrames.get(src) ?? poster ?? '';
  const callbacksRef = useRef({
    onDurationReady,
    onPlaying,
    onWaiting,
    onEnded,
    onError,
  });
  callbacksRef.current = {
    onDurationReady,
    onPlaying,
    onWaiting,
    onEnded,
    onError,
  };

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    let active = false;
    const disposables = createDisposableList();
    let activeDisposables: ReturnType<typeof createDisposableList> | null =
      null;

    const activate = () => {
      const video = shared.getVideo();
      const srcChanged = !video.src.endsWith(src);

      showPoster.value = true;

      // Attach listeners BEFORE changing src/currentTime/play.
      // Changing src or seeking on a cached video can fire events
      // synchronously — listeners must be in place to catch them.
      activeDisposables = createDisposableList();
      activeDisposables.push(
        observeDomEvent(video, 'loadedmetadata', () => {
          if (video.duration && isFinite(video.duration)) {
            callbacksRef.current.onDurationReady?.(video.duration * 1000);
          }
        }),
        observeMediaLoading(video, {
          onReady: () => {
            callbacksRef.current.onPlaying?.();
          },
          onWaiting: () => {
            callbacksRef.current.onWaiting?.();
          },
          onPlaying: () => {
            showPoster.value = false;
          },
        }),
        observeDomEvent(video, 'ended', () => {
          callbacksRef.current.onEnded?.();
        }),
        observeDomEvent(video, 'error', () => {
          if (video.error) callbacksRef.current.onError?.();
        }),
      );

      if (srcChanged) video.src = src;
      video.currentTime = 0;
      video.muted = soundState.muted.value;
      video.loop = false;
      video.style.objectFit = 'cover';
      video.style.width = '100%';
      video.style.height = '100%';

      container.appendChild(video);

      if (video.readyState >= 1 && video.duration && isFinite(video.duration)) {
        callbacksRef.current.onDurationReady?.(video.duration * 1000);
      }

      video.play().catch(noop);
    };

    const deactivate = () => {
      activeDisposables?.dispose();
      activeDisposables = null;

      const video = shared.getVideo();
      // Only pause and remove if the video is still in THIS container.
      // Another slide's activate() may have already claimed the shared
      // video via appendChild (which auto-removes from the old parent).
      if (video.parentNode === container) {
        const frame = captureFrame(video);
        if (frame) shared.capturedFrames.set(src, frame);
        video.pause();
        container.removeChild(video);
      }
      showPoster.value = true;
    };

    disposables.push(
      reaction(
        () => [activeGroupIndex, activeStoryIndex],
        () => {
          const shouldBeActive =
            activeGroupIndex.value === groupIndex &&
            activeStoryIndex.value === storyIndex;

          if (shouldBeActive && !active) {
            active = true;
            activate();
          } else if (!shouldBeActive && active) {
            active = false;
            deactivate();
          }
        },
      ),
      () => {
        if (active) deactivate();
      },
    );

    // Check initial state
    if (
      activeGroupIndex.value === groupIndex &&
      activeStoryIndex.value === storyIndex
    ) {
      active = true;
      activate();
    }

    return disposables.dispose;
  }, [src, groupIndex, storyIndex]);

  useEffect(() => syncMutedToVideo(soundState, shared.getVideo()), []);

  return (
    <div ref={containerRef} className="rk-stories-video">
      {resolvedPoster && (
        <Observe signals={[showPoster]}>
          {() => (
            <img
              src={resolvedPoster}
              alt=""
              className={`rk-stories-video-poster ${showPoster.value ? 'rk-stories-video-poster--visible' : ''}`}
            />
          )}
        </Observe>
      )}
    </div>
  );
};

// packages/reelkit-angular-stories-player/src/lib/video-story-slide/video-story-slide.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  NgZone,
  ViewEncapsulation,
  afterRenderEffect,
  computed,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import {
  SoundStateService,
  captureFrame,
  createDisposableList,
  createSharedVideo,
  noop,
  observeDomEvent,
  observeMediaLoading,
  reaction,
  syncMutedToVideo,
  type CoreSignal,
  type DisposableList,
} from '@reelkit/angular';

/**
 * The one `<video>` every story slide borrows. A single element is what keeps
 * audio alive on iOS as the player moves from story to story; a fresh element
 * per slide loses the user gesture that allowed sound in the first place.
 */
const shared = createSharedVideo({
  className: 'rk-stories-video-element',
  disableRemotePlayback: true,
  disablePictureInPicture: true,
});

/**
 * The element the slides share, for the player itself: pausing playback when
 * the viewer holds a press reaches the same `<video>` the active slide holds.
 *
 * @internal
 */
export const sharedStoryVideo = (): HTMLVideoElement => shared.getVideo();

/**
 * One video story.
 *
 * Which slide owns the shared element is decided from the controller's own
 * signals rather than from rendering: a slide claims the video when both
 * indexes point at it, and hands it back when they move on. Going through
 * change detection instead would put a frame between the two, and the
 * viewer would see the gap.
 */
@Component({
  selector: 'rk-video-story-slide',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div #container class="rk-stories-video">
      @if (resolvedPoster()) {
        <img
          [src]="resolvedPoster()"
          alt=""
          class="rk-stories-video-poster"
          [class.rk-stories-video-poster--visible]="showPoster()"
        />
      }
    </div>
  `,
})
export class RkVideoStorySlideComponent {
  private readonly _ngZone = inject(NgZone);

  /**
   * Sound state the player provides. A slide rendered from a slot template
   * finds it too: the player renders every slot through its own injector, so
   * this resolves the same way whichever template drew the slide.
   */
  private readonly _soundState = inject(SoundStateService);

  private readonly _containerRef =
    viewChild.required<ElementRef<HTMLDivElement>>('container');

  /** Loaded only while this slide is the active one. */
  readonly src = input.required<string>();

  /** Shown until playback starts. A frame captured from an earlier play wins. */
  readonly poster = input<string | undefined>(undefined);

  /** Where this slide sits. Matched against the two signals below. */
  readonly groupIndex = input.required<number>();

  /** Where this slide sits. Matched against the two signals below. */
  readonly storyIndex = input.required<number>();

  /** Both signals equal to the pair above means this slide owns the video. */
  readonly activeGroupIndex = input.required<CoreSignal<number>>();

  /** Both signals equal to the pair above means this slide owns the video. */
  readonly activeStoryIndex = input.required<CoreSignal<number>>();

  /** Real length of the media, so the timer matches the video. */
  readonly durationReady = output<number>();

  /** Playback started: the story is on screen rather than buffering. */
  readonly playbackStarted = output<void>();

  /** Playback stalled mid-story. */
  readonly buffering = output<void>();

  /** The story is over; the player moves on rather than waiting for the timer. */
  readonly finished = output<void>();

  /** Covers a source that will not load and a play the browser refused. */
  readonly failed = output<void>();

  protected readonly showPoster = signal(true);

  protected readonly resolvedPoster = computed(
    () => shared.capturedFrames.get(this.src()) ?? this.poster() ?? '',
  );

  constructor() {
    afterRenderEffect(() => {
      const src = this.src();
      const groupIndex = this.groupIndex();
      const storyIndex = this.storyIndex();

      // Everything else is read untracked: this effect re-runs only when the
      // slide's own identity changes, never on a tick or a sound toggle.
      const container = untracked(() => this._containerRef().nativeElement);
      const activeGroupIndex = untracked(() => this.activeGroupIndex());
      const activeStoryIndex = untracked(() => this.activeStoryIndex());

      let active = false;
      let activeDisposables: DisposableList | null = null;

      const activate = (): void => {
        const video = shared.getVideo();
        const srcChanged = !video.src.endsWith(src);

        this.showPoster.set(true);

        // Listeners go on before src, currentTime or play are touched: a
        // cached video fires those events synchronously, and a listener
        // attached afterwards never hears them.
        activeDisposables = createDisposableList();
        activeDisposables.push(
          observeDomEvent(video, 'loadedmetadata', () => {
            if (video.duration && isFinite(video.duration)) {
              this._ngZone.run(() =>
                this.durationReady.emit(video.duration * 1000),
              );
            }
          }),
          observeMediaLoading(video, {
            onReady: () => this._ngZone.run(() => this.playbackStarted.emit()),
            onWaiting: () => this._ngZone.run(() => this.buffering.emit()),
            onPlaying: () => this._ngZone.run(() => this.showPoster.set(false)),
          }),
          observeDomEvent(video, 'ended', () =>
            this._ngZone.run(() => this.finished.emit()),
          ),
          observeDomEvent(video, 'error', () => {
            if (video.error) this._ngZone.run(() => this.failed.emit());
          }),
        );

        if (srcChanged) video.src = src;
        video.currentTime = 0;
        video.muted = untracked(() => this._soundState.muted());
        video.loop = false;
        video.style.objectFit = 'cover';
        video.style.width = '100%';
        video.style.height = '100%';

        container.appendChild(video);

        if (
          video.readyState >= 1 &&
          video.duration &&
          isFinite(video.duration)
        ) {
          this._ngZone.run(() =>
            this.durationReady.emit(video.duration * 1000),
          );
        }

        video.play().catch(noop);
      };

      const deactivate = (): void => {
        activeDisposables?.dispose();
        activeDisposables = null;

        const video = shared.getVideo();
        // Pause and detach only while the video is still here: the next
        // slide's activate may already have claimed it, since appendChild
        // takes it out of this container on its own.
        if (video.parentNode === container) {
          const frame = captureFrame(video);
          if (frame) shared.capturedFrames.set(src, frame);
          video.pause();
          container.removeChild(video);
        }
        this.showPoster.set(true);
      };

      const isMine = (): boolean =>
        activeGroupIndex.value === groupIndex &&
        activeStoryIndex.value === storyIndex;

      const disposables = createDisposableList();
      disposables.push(
        reaction(
          () => [activeGroupIndex, activeStoryIndex],
          () => {
            const shouldBeActive = isMine();
            if (shouldBeActive && !active) {
              active = true;
              activate();
            } else if (!shouldBeActive && active) {
              active = false;
              deactivate();
            }
          },
        ),
        syncMutedToVideo(
          untracked(() => this._soundState.controller),
          shared.getVideo(),
        ),
        () => {
          if (active) deactivate();
        },
      );

      if (isMine()) {
        active = true;
        activate();
      }

      return () => disposables.dispose();
    });
  }
}
