// packages/reelkit-react-stories-player/src/lib/StoriesRingList.tsx
import type { FC } from 'react';
import { Observe } from '@reelkit/react';
import {
  kStoriesRingListRingSize,
  type StoriesGroup,
  type StoriesViewedStateController,
} from '@reelkit/stories-core';
import { StoriesRing } from './StoriesRing';
import { useAttachViewedState } from './useAttachViewedState';
import './StoriesRingList.css';

/** Props for the {@link StoriesRingList} component. */
export interface StoriesRingListProps {
  /** Ordered list of story groups to display. */
  groups: StoriesGroup[];

  /**
   * What the viewer has seen, from `createStoriesViewedStateController`. The rings
   * follow it by themselves: a story marked seen repaints them and nothing
   * else, and the list reads the store while it is mounted. Without it every
   * ring shows the unwatched gradient. Hand the same controller to the player.
   */
  viewed?: StoriesViewedStateController;

  /**
   * Diameter for each ring in pixels.
   * @default 64
   */
  ringSize?: number;

  /** Callback fired when a ring is selected, with the group index. */
  onSelect: (groupIndex: number) => void;
}

/**
 * Horizontal scrollable row of {@link StoriesRing} components.
 *
 * Renders one ring per story group with the author's name truncated below.
 * Scroll is handled natively via `overflow-x: auto` with hidden scrollbars.
 */
export const StoriesRingList: FC<StoriesRingListProps> = ({
  groups,
  viewed,
  onSelect,
  ringSize = kStoriesRingListRingSize,
}) => {
  useAttachViewedState(viewed);

  return (
    <div className="rk-stories-ring-list">
      <Observe signals={viewed ? [viewed.viewedState] : []}>
        {() => {
          const counts = viewed?.viewedState.value;
          return (
            <>
              {groups.map((group, index) => (
                <div
                  key={group.author.id}
                  className="rk-stories-ring-list-item"
                >
                  <StoriesRing
                    author={group.author}
                    totalStories={group.stories.length}
                    viewedCount={counts?.get(group.author.id) ?? 0}
                    size={ringSize}
                    onClick={() => onSelect(index)}
                  />
                  <span
                    className="rk-stories-ring-list-name"
                    style={{ maxWidth: ringSize }}
                  >
                    {group.author.name}
                  </span>
                </div>
              ))}
            </>
          );
        }}
      </Observe>
    </div>
  );
};

// packages/reelkit-angular-stories-player/src/lib/stories-ring-list/stories-ring-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ViewEncapsulation,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { toAngularSignal } from '@reelkit/angular';
import {
  kStoriesRingListRingSize,
  type StoriesGroup,
  type StoriesViewedStateController,
} from '@reelkit/stories-core';
import { RkStoriesRingComponent } from '../stories-ring/stories-ring.component';
import { attachViewedState } from '../viewed-state/attach-viewed-state';

/**
 * Horizontal row of story rings, one per group, with the author's name under
 * each. Scrolling is native, with the scrollbar hidden.
 *
 * The rings follow the viewed store on their own: marking a story seen
 * repaints them and nothing else.
 */
@Component({
  selector: 'rk-stories-ring-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [RkStoriesRingComponent],
  template: `
    <div class="rk-stories-ring-list">
      @for (group of groups(); track group.author.id; let index = $index) {
        <div class="rk-stories-ring-list-item">
          <rk-stories-ring
            [author]="group.author"
            [totalStories]="group.stories.length"
            [viewedCount]="viewedCountOf(group.author.id)"
            [size]="ringSize()"
            (clicked)="selected.emit(index)"
          />
          <span
            class="rk-stories-ring-list-name"
            [style.max-width.px]="ringSize()"
            >{{ group.author.name }}</span
          >
        </div>
      }
    </div>
  `,
})
export class RkStoriesRingListComponent {
  private readonly _destroyRef = inject(DestroyRef);

  /** Ordered groups to draw. */
  readonly groups = input.required<StoriesGroup[]>();

  /**
   * What the viewer has seen, from `createStoriesViewedStateController`. The
   * list reads the store while it is on screen; without a controller every
   * ring shows the unwatched gradient. Hand the same controller to the player.
   */
  readonly viewed = input<StoriesViewedStateController | undefined>(undefined);

  /**
   * Diameter of each ring in pixels.
   *
   * @default 64
   */
  readonly ringSize = input(kStoriesRingListRingSize);

  /** Emitted with the group index when a ring is chosen. */
  readonly selected = output<number>();

  private readonly _viewedState = computed(() => {
    const controller = this.viewed();
    return controller
      ? toAngularSignal(controller.viewedState, this._destroyRef)
      : undefined;
  });

  constructor() {
    attachViewedState(this.viewed);
  }

  protected viewedCountOf(authorId: string): number {
    return this._viewedState()?.()?.get(authorId) ?? 0;
  }
}
